MODEL (
  name lenovo.ldo.system_update_report_seed_model,
  kind SEED (
    path '../seeds/seed_system_update_reports_cdc.csv'
  ),
  columns (
    _id STRING,
    scan_id STRING,
    org_id STRING,
    device_id STRING,
    package_id STRING,
    installation_status STRING,
    coreq_package_id STRING,
    package_name STRING,
    package_description STRING,
    package_version STRING,
    current_installed_version STRING,
    package_release_date BIGINT,
    package_vendor STRING,
    package_type STRING,
    package_severity STRING,
    package_reboot_type STRING,
    package_size BIGINT,
    disk_space_required BIGINT,
    package_tips STRING,
    readme_url STRING,
    license_url STRING,
    device_display_name STRING,
    device_serial_number STRING,
    device_product_name STRING,
    created_at BIGINT,
    last_modified_date BIGINT,
    device_local_event_date_time BIGINT,
    event_date_time BIGINT,
    _class STRING,
    filtering_group_name STRING,
    deleted STRING,
    _op STRING,
    _collection STRING,
    _source_ts_ms BIGINT,
    _db STRING,
    _nilus_load_id STRING,
    _nilus_id STRING,
    failure_reason STRING,
    failure_reason_details STRING,
    category STRING,
    time_zone STRING
  ),
  grains (_id, _nilus_id)
)

