-- Customer profile dimension with aggregated lifetime metrics
-- Provides complete customer analytics including purchase behavior and value metrics
MODEL (
    name curated.dim_customer_profile,
    kind FULL,
    cron '*/5 * * * *',
    grains (customer_id),
    tags (
        'dimension',
        'aggregated',
        'customer',
        'profile',
        'silver'
    ),
    terms (
        'customer.profile_analytics',
        'analytics.customer_lifetime'
    ),
    description 'Customer profile dimension containing lifetime aggregated metrics including purchase behavior, order patterns, revenue contribution, and product preferences for customer analytics and segmentation',
    column_descriptions (
        customer_id = 'Unique identifier for each customer',
        customer_name = 'Customer full name',
        email = 'Customer email address',
        region_id = 'Foreign key to regions table - customer home region',
        region_name = 'Name of customer home region',
        first_order_date = 'Date of customer first order - stored as TIMESTAMP',
        last_order_date = 'Date of customer most recent order - stored as TIMESTAMP',
        days_since_first_order = 'Number of days since first order (customer lifetime)',
        days_since_last_order = 'Number of days since last order (recency)',
        total_orders = 'Total number of orders placed by customer (lifetime)',
        total_items_purchased = 'Total quantity of items purchased (lifetime)',
        total_revenue = 'Total revenue generated by customer in USD (lifetime value)',
        avg_order_value = 'Average order value (total_revenue / total_orders)',
        avg_items_per_order = 'Average number of items per order',
        favorite_category = 'Product category most frequently purchased',
        total_shipments_received = 'Number of shipments received',
        customer_segment = 'Customer classification based on purchase behavior (High Value, Medium Value, Low Value, Churned)'
    ),
    column_tags (
        customer_id = (
            'primary_key',
            'identifier',
            'grain'
        ),
        customer_name = ('dimension', 'label', 'pii'),
        email = ('dimension', 'pii', 'contact'),
        region_id = (
            'foreign_key',
            'reference',
            'geography'
        ),
        region_name = ('dimension', 'label'),
        first_order_date = (
            'temporal',
            'date',
            'milestone'
        ),
        last_order_date = (
            'temporal',
            'date',
            'milestone'
        ),
        days_since_first_order = (
            'measure',
            'metric',
            'temporal'
        ),
        days_since_last_order = (
            'measure',
            'metric',
            'temporal'
        ),
        total_orders = ('measure', 'metric', 'count'),
        total_items_purchased = ('measure', 'metric', 'sum'),
        total_revenue = (
            'measure',
            'financial',
            'metric'
        ),
        avg_order_value = (
            'measure',
            'financial',
            'metric'
        ),
        avg_items_per_order = (
            'measure',
            'metric',
            'average'
        ),
        favorite_category = (
            'dimension',
            'label',
            'preference'
        ),
        customer_segment = (
            'dimension',
            'classification',
            'label'
        )
    ),
    column_terms (
        customer_id = (
            'customer.customer_id',
            'identity.customer_id'
        ),
        total_revenue = (
            'customer.ltv',
            'finance.customer_lifetime_value'
        ),
        avg_order_value = (
            'sales.aov',
            'finance.average_order_value'
        ),
        customer_segment = (
            'customer.segment',
            'classification.customer_tier'
        )
    ),
    assertions (
        unique_values (columns := customer_id),
        not_null (
            columns := (
                customer_id,
                customer_name,
                email,
                region_id,
                region_name
            )
        ),
        forall (
            criteria := (
                customer_id > 0,
                total_orders >= 0,
                total_items_purchased >= 0,
                total_revenue >= 0
            )
        ),
        accepted_values (
            column := customer_segment,
            is_in := (
                'High Value',
                'Medium Value',
                'Low Value',
                'Churned',
                'New'
            )
        )
    ),
    profiles (
        customer_name,
        email,
        region_name,
        total_orders,
        total_revenue,
        customer_segment
    )
);

WITH customer_orders AS (
  SELECT
    c.customer_id,
    c.name AS customer_name,
    c.email,
    c.region_id,
    r.region_name,
    MIN(DATE(o.order_date)) AS first_order_date,
    MAX(DATE(o.order_date)) AS last_order_date,
    COALESCE((CURRENT_DATE - MAX(DATE(o.order_date)))::INTEGER, 0) AS days_since_last_order,
    COALESCE((CURRENT_DATE - MIN(DATE(o.order_date)))::INTEGER, 0) AS days_since_first_order,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity) AS total_items_purchased,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
  from raw.customers AS c
  INNER JOIN bronze.regions AS r
    ON c.region_id = r.region_id
  LEFT JOIN bronze.orders AS o
    ON c.customer_id = o.customer_id
  LEFT JOIN bronze.order_items AS oi
    ON o.order_id = oi.order_id
  GROUP BY c.customer_id, c.name, c.email, c.region_id, r.region_name
),
customer_categories AS (
  SELECT
    c.customer_id,
    p.category,
    SUM(oi.quantity) AS category_quantity,
    ROW_NUMBER() OVER (PARTITION BY c.customer_id ORDER BY SUM(oi.quantity) DESC) AS category_rank
  from raw.customers AS c
  LEFT JOIN bronze.orders AS o
    ON c.customer_id = o.customer_id
  LEFT JOIN bronze.order_items AS oi
    ON o.order_id = oi.order_id
  LEFT JOIN bronze.products AS p
    ON oi.product_id = p.product_id
  GROUP BY c.customer_id, p.category
),
customer_shipments AS (
  SELECT
    c.customer_id,
    COUNT(DISTINCT s.shipment_id) AS total_shipments_received
  from raw.customers AS c
  LEFT JOIN bronze.orders AS o
    ON c.customer_id = o.customer_id
  LEFT JOIN bronze.shipments AS s
    ON o.order_id = s.order_id
  GROUP BY c.customer_id
)
SELECT
  co.customer_id,
  co.customer_name,
  co.email,
  co.region_id,
  co.region_name,
  CAST(co.first_order_date AS TIMESTAMP) AS first_order_date,
  CAST(co.last_order_date AS TIMESTAMP) AS last_order_date,
  co.days_since_first_order,
  co.days_since_last_order,
  COALESCE(co.total_orders, 0) AS total_orders,
  COALESCE(co.total_items_purchased, 0) AS total_items_purchased,
  ROUND(COALESCE(co.total_revenue, 0), 2) AS total_revenue,
  ROUND(co.total_revenue / NULLIF(co.total_orders, 0), 2) AS avg_order_value,
  ROUND(co.total_items_purchased::NUMERIC / NULLIF(co.total_orders, 0), 2) AS avg_items_per_order,
  COALESCE(cc.category, 'None') AS favorite_category,
  COALESCE(cs.total_shipments_received, 0) AS total_shipments_received,
  CASE
    WHEN co.total_revenue IS NULL OR co.total_orders = 0 THEN 'New'
    WHEN CURRENT_DATE - co.last_order_date > 90 THEN 'Churned'
    WHEN co.total_revenue >= 5000 THEN 'High Value'
    WHEN co.total_revenue >= 1000 THEN 'Medium Value'
    ELSE 'Low Value'
  END AS customer_segment
FROM customer_orders AS co
LEFT JOIN customer_categories AS cc
  ON co.customer_id = cc.customer_id
  AND cc.category_rank = 1
LEFT JOIN customer_shipments AS cs
  ON co.customer_id = cs.customer_id