MODEL (
  name lenovo.ldo.live_device_status,
  kind FULL,
  grains (UUID),
  tags ('device_inventory', 'live_status', 'device_groups', 'license_assignment', 'flattened'),
  terms ('device.status', 'inventory.management', 'license.allocation'),
  description 'Comprehensive live device status with flattened device groups and license assignments. Provides real-time device inventory including hardware details, OS information, network status, warranty information, assigned licenses, and group memberships for device management and license compliance',
  column_descriptions (
    uuid = 'Unique composite identifier for device-group-license combination',
    id = 'Primary device record identifier',
    org_id = 'Organization identifier owning the device',
    device_id = 'Unique device identifier',
    org_device_id = 'Organization-specific device identifier',
    subscription_id = 'Active subscription identifier',
    device_name = 'Display name of the device',
    manufacturer = 'Device manufacturer name',
    model_type = 'Device model/type',
    serial_number = 'Device serial number',
    family = 'Device family/product line',
    enclosure_type = 'Device enclosure type (desktop, laptop, tablet, etc.)',
    category = 'Device category classification',
    platform = 'Device platform type',
    os_name = 'Operating system name',
    network = 'Network connection status/type',
    timezone = 'Device timezone setting',
    status = 'Current device status (online, offline, etc.)',
    version = 'Device/software version',
    warranty_status = 'Current warranty status',
    warranty_expiration_date = 'Warranty expiration date',
    country_name = 'Device location country',
    device_group_id = 'Device group identifier (flattened)',
    device_group_name = 'Device group name (flattened)',
    billing_subscription_id = 'Billing subscription identifier for license (flattened)',
    license_type_id = 'License type identifier (flattened)',
    part_number = 'License part number (flattened)',
    trial = 'Trial license flag (flattened)',
    __deleted = 'CDC deletion flag',
    __op = 'CDC operation type',
    __source_ts_ms = 'Source system timestamp'
  ),
  column_tags (
    uuid = ('identifier', 'primary_key', 'composite'),
    id = ('identifier', 'device'),
    org_id = ('identifier', 'organization'),
    device_id = ('identifier', 'device', 'unique'),
    org_device_id = ('identifier', 'device', 'organization_specific'),
    subscription_id = ('identifier', 'subscription'),
    device_name = ('dimension', 'device'),
    manufacturer = ('dimension', 'device', 'vendor'),
    model_type = ('dimension', 'device', 'model'),
    serial_number = ('identifier', 'device', 'hardware'),
    family = ('dimension', 'device', 'product_line'),
    enclosure_type = ('dimension', 'device', 'form_factor'),
    category = ('dimension', 'classification'),
    platform = ('dimension', 'device', 'platform'),
    os_name = ('dimension', 'operating_system'),
    network = ('dimension', 'network', 'connectivity'),
    timezone = ('dimension', 'location'),
    status = ('dimension', 'status'),
    version = ('dimension', 'version'),
    warranty_status = ('dimension', 'warranty'),
    warranty_expiration_date = ('temporal', 'date', 'warranty'),
    country_name = ('dimension', 'geography'),
    device_group_id = ('identifier', 'group'),
    device_group_name = ('dimension', 'group'),
    billing_subscription_id = ('identifier', 'billing'),
    license_type_id = ('identifier', 'license'),
    part_number = ('identifier', 'sku'),
    trial = ('flag', 'license'),
    __deleted = ('metadata', 'cdc', 'flag'),
    __op = ('metadata', 'cdc'),
    __source_ts_ms = ('metadata', 'cdc', 'temporal')
  ),
  column_terms (
    uuid = ('entity.identifier', 'composite.key'),
    device_id = ('device.identifier', 'entity.reference'),
    org_id = ('organization.identifier', 'entity.owner'),
    manufacturer = ('device.manufacturer', 'vendor.name'),
    warranty_status = ('warranty.status', 'coverage.state'),
    device_group_id = ('group.identifier', 'assignment.group'),
    license_type_id = ('license.type', 'entitlement.classification'),
    __op = ('cdc.operation', 'event.type'),
    __deleted = ('cdc.deletion', 'event.flag')
  )
);

WITH cleaned_cdc_data AS (
  SELECT
    *
  FROM (
    SELECT
      _id AS id,
      org_id,
      device_id,
      org_device_id,
      subscription_id,
      device_name,
      manufacturer,
      model_type,
      serial_number,
      family,
      enclosure_type,
      category,
      platform,
      os_name,
      network,
      time_zone,
      status,
      version,
      warranty_status,
      TO_TIMESTAMP_NTZ(warranty_expiration_date / 1000) AS warranty_expiration_date,
      country_name,
      PARSE_JSON(device_groups) AS device_groups,
      PARSE_JSON(licenses) AS licenses,
      _op AS __op,
      TO_TIMESTAMP_NTZ(_source_ts_ms / 1000) AS __source_ts_ms,
      deleted AS __deleted,
      ROW_NUMBER() OVER (
        PARTITION BY _id
        ORDER BY CASE WHEN _op IS NOT NULL THEN 0 ELSE 1 END, CAST(_source_ts_ms AS BIGINT) DESC
      ) AS rn
    FROM lenovo.ldo.devices_seed_model
  )
  WHERE rn = 1
),
explode_licenses AS (
  SELECT
    id,
    org_id,
    device_id,
    org_device_id,
    subscription_id,
    device_name,
    manufacturer,
    model_type,
    serial_number,
    family,
    enclosure_type,
    category,
    platform,
    os_name,
    device_groups,
    f.value AS licenses_,
    network,
    time_zone AS timezone,
    status,
    version,
    warranty_status,
    warranty_expiration_date,
    country_name,
    __deleted,
    __op,
    __source_ts_ms
  FROM cleaned_cdc_data,
    LATERAL FLATTEN(input => licenses, outer => true) f
),
post_explode_licenses AS (
  SELECT
    id,
    org_id,
    device_id,
    org_device_id,
    subscription_id,
    device_name,
    manufacturer,
    model_type,
    serial_number,
    family,
    enclosure_type,
    category,
    platform,
    os_name,
    device_groups,
    licenses_:billingSubscriptionId::STRING AS billing_subscription_id,
    licenses_:licenseTypeId::STRING AS license_type_id,
    licenses_:partNumber::STRING AS part_number,
    licenses_:trial::BOOLEAN AS trial,
    network,
    timezone,
    status,
    version,
    warranty_status,
    warranty_expiration_date,
    country_name,
    __deleted,
    __op,
    __source_ts_ms
  FROM explode_licenses
),
explode_device_groups AS (
  SELECT
    id,
    org_id,
    device_id,
    org_device_id,
    subscription_id,
    device_name,
    manufacturer,
    model_type,
    serial_number,
    family,
    enclosure_type,
    category,
    platform,
    os_name,
    billing_subscription_id,
    license_type_id,
    part_number,
    trial,
    network,
    timezone,
    status,
    version,
    warranty_status,
    warranty_expiration_date,
    country_name,
    f.value AS device_groups_,
    __deleted,
    __op,
    __source_ts_ms
  FROM post_explode_licenses,
    LATERAL FLATTEN(input => device_groups, outer => true) f
),
post_explode_device_groups AS (
  SELECT
    id,
    org_id,
    device_id,
    org_device_id,
    subscription_id,
    device_name,
    manufacturer,
    model_type,
    serial_number,
    family,
    enclosure_type,
    category,
    platform,
    os_name,
    network,
    timezone,
    status,
    version,
    warranty_status,
    warranty_expiration_date,
    country_name,
    device_groups_:groupId::STRING AS device_group_id,
    device_groups_:groupName::STRING AS device_group_name,
    billing_subscription_id,
    license_type_id,
    part_number,
    trial,
    __deleted,
    __op,
    __source_ts_ms
  FROM explode_device_groups
),
final AS (
  SELECT
    CONCAT(
      id,
      '_',
      device_id,
      '_',
      COALESCE(device_group_id, 'DGID'),
      '_',
      COALESCE(billing_subscription_id, 'BSID')
    ) AS uuid,
    id,
    org_id,
    device_id,
    org_device_id,
    subscription_id,
    device_name,
    manufacturer,
    model_type,
    serial_number,
    family,
    enclosure_type,
    category,
    platform,
    os_name,
    network,
    timezone,
    status,
    version,
    warranty_status,
    warranty_expiration_date,
    country_name,
    device_group_id,
    device_group_name,
    billing_subscription_id,
    license_type_id,
    part_number,
    trial,
    __deleted,
    __op,
    __source_ts_ms
  FROM post_explode_device_groups
  WHERE __deleted = 'False'
)
SELECT * FROM final