MODEL (
  name web_analytics_seeds.PRODUCT_DETAILS,
  kind SEED (
    path '../../seeds/product_details.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Product catalog seed data with item details and classifications',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('product_details'),
  columns (
        _metadata VARCHAR,
        premise VARCHAR,
        corp_status VARCHAR,
        product_name_sc VARCHAR,
        product_name_cust VARCHAR,
        itemnumber BIGINT,
        itemnamenbr VARCHAR,
        corpitemupc VARCHAR,
        productnumber VARCHAR,
        pim_product_name VARCHAR,
        level_1_hierarchy VARCHAR,
        level_2_supplier_hierarchy VARCHAR,
        level_2_region_hierarchy VARCHAR,
        level_2_region_hierarchy_extended VARCHAR,
        imageurl VARCHAR,
        defaultimageurl VARCHAR,
        region VARCHAR,
        country_of_origin VARCHAR,
        sub_region VARCHAR,
        size VARCHAR,
        closuretype VARCHAR,
        containertype VARCHAR,
        corporate_units_per_case BIGINT,
        ready_to_drink_rtd VARCHAR,
        category VARCHAR,
        corporate_item_type VARCHAR,
        corporate_item_subtype VARCHAR,
        item_class VARCHAR,
        brand VARCHAR,
        supplier VARCHAR,
        alcohol_by_volume DECIMAL(18, 4),
        alcohol_by_volume_bucket VARCHAR,
        proof VARCHAR,
        service_category_in_pim VARCHAR,
        varietal VARCHAR,
        appellation VARCHAR,
        vintage BIGINT,
        vineyard VARCHAR,
        producer VARCHAR,
        corp_item_flavor VARCHAR,
        diversity_brand VARCHAR,
        pim_replacement_item_effective_dt VARCHAR,
        pim_replacement_id VARCHAR,
        proprietary VARCHAR,
        ready_to_delete_flag VARCHAR,
        value_added_pack VARCHAR,
        fine_wine_flag VARCHAR,
        romantic_description VARCHAR,
        diet_specialty VARCHAR,
        style VARCHAR,
        rating BIGINT,
        rating_source VARCHAR,
        pim_item_class_desc VARCHAR,
        pim_item_sub_class_desc VARCHAR,
        corp_item_scc VARCHAR,
        special_container VARCHAR,
        outer_packaging VARCHAR,
        units_per_inner_pack BIGINT,
        inner_packs_per_case BIGINT,
        cases_per_pallet BIGINT,
        level_1_hierarchy_revised VARCHAR,
        dataos_load_dt VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: PRODUCT_DETAILS
-- ============================================================================

SELECT
  _metadata,
  premise,
  corp_status,
  product_name_sc,
  product_name_cust,
  itemnumber,
  itemnamenbr,
  corpitemupc,
  productnumber,
  pim_product_name,
  level_1_hierarchy,
  level_2_supplier_hierarchy,
  level_2_region_hierarchy,
  level_2_region_hierarchy_extended,
  imageurl,
  defaultimageurl,
  region,
  country_of_origin,
  sub_region,
  size,
  closuretype,
  containertype,
  corporate_units_per_case,
  ready_to_drink_rtd,
  category,
  corporate_item_type,
  corporate_item_subtype,
  item_class,
  brand,
  supplier,
  alcohol_by_volume,
  alcohol_by_volume_bucket,
  proof,
  service_category_in_pim,
  varietal,
  appellation,
  vintage,
  vineyard,
  producer,
  corp_item_flavor,
  diversity_brand,
  pim_replacement_item_effective_dt,
  pim_replacement_id,
  proprietary,
  ready_to_delete_flag,
  value_added_pack,
  fine_wine_flag,
  romantic_description,
  diet_specialty,
  style,
  rating,
  rating_source,
  pim_item_class_desc,
  pim_item_sub_class_desc,
  corp_item_scc,
  special_container,
  outer_packaging,
  units_per_inner_pack,
  inner_packs_per_case,
  cases_per_pallet,
  level_1_hierarchy_revised,
  dataos_load_dt
FROM SEED();
