MODEL (
  name web_analytics_seeds.V_D_CURR_CORP_ITEM,
  kind SEED (
    path '../../seeds/v_d_curr_corp_item.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Product catalog seed data with item details and classifications',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('v_d_curr_corp_item'),
  columns (
        corp_item_no BIGINT,
        corp_item_desc BIGINT,
        corp_item_long_desc VARCHAR,
        corp_item_prod_num VARCHAR,
        corp_item_brand VARCHAR,
        corp_item_brand_name VARCHAR,
        corp_item_suppl VARCHAR,
        corp_item_suppl_name VARCHAR,
        corp_item_prod_cat VARCHAR,
        corp_item_prod_cat_name VARCHAR,
        corp_item_prod_cat_cd VARCHAR,
        corp_item_prod_class VARCHAR,
        corp_item_prod_class_name VARCHAR,
        corp_item_prod_group VARCHAR,
        corp_item_pgrp_name VARCHAR,
        corp_item_prod_subg VARCHAR,
        corp_item_prod_sb_nm VARCHAR,
        corp_item_prod_super_group VARCHAR,
        corp_item_prod_super_group_name VARCHAR,
        corp_item_sup_suppl VARCHAR,
        corp_item_vintage VARCHAR,
        corp_item_flavor_cd VARCHAR,
        corp_item_flavor VARCHAR,
        corp_item_region VARCHAR,
        corp_item_region_name VARCHAR,
        corp_item_appelation VARCHAR,
        corp_item_appel_name VARCHAR,
        corp_item_cnty_orign VARCHAR,
        corp_item_cnty_name VARCHAR,
        corp_item_size VARCHAR,
        corp_item_uom VARCHAR,
        corp_item_wine_gal VARCHAR,
        corp_item_unit_vol VARCHAR,
        corp_item_proof VARCHAR,
        corp_item_unit_cbvol VARCHAR,
        corp_item_unit_heigt VARCHAR,
        corp_item_unit_width VARCHAR,
        corp_item_unit_legth VARCHAR,
        corp_item_unit_swght VARCHAR,
        corp_item_units_layr VARCHAR,
        corp_item_layer_palt VARCHAR,
        corp_item_bot_pack VARCHAR,
        corp_item_pack_case VARCHAR,
        corp_item_bttls_pcas VARCHAR,
        corp_item_upc VARCHAR,
        corp_item_scc VARCHAR,
        corp_item_pack_upc VARCHAR,
        corp_item_rep_cas_rt VARCHAR,
        corp_item_holgft_itm VARCHAR,
        corp_item_copack_itm VARCHAR,
        corp_item_pvtlbl_itm VARCHAR,
        corp_item_lblimg_fil VARCHAR,
        corp_item_prdimg_fil VARCHAR,
        corp_item_rating VARCHAR,
        corp_item_status VARCHAR,
        corp_item_alcoh_perc VARCHAR,
        corp_item_link_code VARCHAR,
        corp_item_crt_date VARCHAR,
        corp_item_crt_time VARCHAR,
        corp_item_crt_user VARCHAR,
        corp_item_upd_date VARCHAR,
        corp_item_upd_time VARCHAR,
        corp_item_upd_user VARCHAR,
        corp_item_ounc_unit VARCHAR,
        corp_item_ntype VARCHAR,
        corp_suppl_name VARCHAR,
        corp_suppl_ss_flag VARCHAR,
        corp_suppl_f_month VARCHAR,
        corp_suppl_vendor VARCHAR,
        corp_suppl_sapvnd_num VARCHAR,
        corp_suppl_mainvnd_num VARCHAR,
        corp_suppl_name2 VARCHAR,
        corp_suppl_address1 VARCHAR,
        corp_suppl_address2 VARCHAR,
        corp_suppl_address3 VARCHAR,
        corp_suppl_city VARCHAR,
        corp_suppl_region VARCHAR,
        corp_suppl_country VARCHAR,
        corp_suppl_zip VARCHAR,
        corp_suppl_zip_ext VARCHAR,
        corp_suppl_phone VARCHAR,
        corp_suppl_fax VARCHAR,
        corp_suppl_edi VARCHAR,
        corp_suppl_status VARCHAR,
        corp_suppl_listed_ind VARCHAR,
        corp_brand_group_flag VARCHAR,
        corp_brand_sup_brand VARCHAR,
        suppl_brand_name VARCHAR,
        type_code VARCHAR,
        subtyp_cod VARCHAR,
        reg_subreg VARCHAR,
        apel_villg_cod VARCHAR,
        apel_villg VARCHAR,
        accolades VARCHAR,
        age_statmt VARCHAR,
        mvintg_flg VARCHAR,
        mvintg_dsc VARCHAR,
        kosher_cod VARCHAR,
        kosher VARCHAR,
        materl_cod VARCHAR,
        material VARCHAR,
        packge_dsc VARCHAR,
        bot_height VARCHAR,
        bot_width VARCHAR,
        bot_length VARCHAR,
        bot_type_cod VARCHAR,
        bot_type VARCHAR,
        cas_ppallt VARCHAR,
        palt_dimns VARCHAR,
        palt_height VARCHAR,
        palt_lngth VARCHAR,
        palt_width VARCHAR,
        box_type_cod VARCHAR,
        box_type VARCHAR,
        closur_cod VARCHAR,
        closure VARCHAR,
        color_cod VARCHAR,
        color VARCHAR,
        design_cod VARCHAR,
        designation VARCHAR,
        dom_imp VARCHAR,
        fob_price DECIMAL(18, 2),
        green_code VARCHAR,
        green VARCHAR,
        cert_green VARCHAR,
        cert_agncy VARCHAR,
        green_detl VARCHAR,
        prodcr_cod VARCHAR,
        producer VARCHAR,
        proprietary VARCHAR,
        shelf_life VARCHAR,
        ttb_code VARCHAR,
        sme_descr VARCHAR,
        classif_by VARCHAR,
        request_by VARCHAR,
        reqby_tims VARCHAR,
        approv_by VARCHAR,
        aprby_tims VARCHAR,
        varietal_code VARCHAR,
        varietal VARCHAR,
        reg_subreg_desc VARCHAR,
        type_desc VARCHAR,
        subtyp_desc VARCHAR,
        dom_botl VARCHAR,
        misc_cod VARCHAR,
        sa_code VARCHAR,
        sa_desc VARCHAR,
        rainbow_item_flag VARCHAR,
        rainbow_component_set_flag VARCHAR,
        is_deleted VARCHAR,
        purch_item_no BIGINT,
        nir_ind VARCHAR,
        national_service_model VARCHAR,
        national_brand_manager VARCHAR,
        corp_suppl_f_periodstart VARCHAR,
        corp_item_status_desc VARCHAR,
        pim_item_no BIGINT,
        pim_item_category_cd VARCHAR,
        pim_item_category_desc VARCHAR,
        pim_item_class_cd VARCHAR,
        pim_item_class_desc VARCHAR,
        pim_item_sub_class_cd VARCHAR,
        pim_item_sub_class_desc VARCHAR,
        pim_suppl_item_desc VARCHAR,
        pim_suppl_item_status VARCHAR,
        pim_suppl_item_discontinued_dt VARCHAR,
        pim_brand_effective_dt VARCHAR,
        pim_requested_label_brand VARCHAR,
        pim_replacement_item_effective_dt VARCHAR,
        pim_ready_approval_ind VARCHAR,
        pim_sample_ind VARCHAR,
        pim_tasting_notes BIGINT,
        age_statmt_uom VARCHAR,
        pim_proof_gallons VARCHAR,
        pim_proof_liters VARCHAR,
        sub_material_cd VARCHAR,
        sub_material_desc VARCHAR,
        pim_cork_type VARCHAR,
        corp_item_rating_dt VARCHAR,
        pim_ttb_cola_id_valid_ind VARCHAR,
        marketing_cd VARCHAR,
        marketing_desc VARCHAR,
        pim_collector_special_label VARCHAR,
        pim_gift_component VARCHAR,
        nielsen_upc VARCHAR,
        pim_premise_type VARCHAR,
        pim_special_container VARCHAR,
        pim_dom_imp_desc VARCHAR,
        pim_bottling_packge_country VARCHAR,
        pim_volume_uom_desc VARCHAR,
        pim_volume_uom_cd VARCHAR,
        corp_item_unit_height_uom VARCHAR,
        corp_item_unit_length_depth_uom VARCHAR,
        corp_item_unit_width_uom VARCHAR,
        corp_item_liter_per_unit VARCHAR,
        corp_item_case_weight_uom VARCHAR,
        corp_item_case_height_uom VARCHAR,
        corp_item_case_length_depth_uom VARCHAR,
        corp_item_case_width_uom VARCHAR,
        corp_item_pallet_height_uom VARCHAR,
        corp_item_pallet_length_depth_uom VARCHAR,
        corp_item_pallet_width_uom VARCHAR,
        corp_item_pack_upc_effective_dt VARCHAR,
        corp_item_pack_upc_override VARCHAR,
        corp_item_pack_ean VARCHAR,
        corp_item_pack_ean_effective_dt VARCHAR,
        corp_item_upc_override VARCHAR,
        corp_item_upc_effective_dt VARCHAR,
        corp_item_ean VARCHAR,
        corp_item_ean_effective_dt VARCHAR,
        corp_item_scc_override VARCHAR,
        corp_item_scc_effective_dt VARCHAR,
        pim_reason_cd VARCHAR,
        pim_reason_desc VARCHAR,
        pim_replacement_id_type_cd VARCHAR,
        pim_replacement_id_type_desc VARCHAR,
        pim_item_status_setup VARCHAR,
        pim_replacement_id VARCHAR,
        pim_replaced_by_user_name VARCHAR,
        pim_notes BIGINT,
        pim_supplier_item_comment VARCHAR,
        pim_supplier_item_comment_dt VARCHAR,
        pim_supplier_item_comment_desc VARCHAR,
        pim_workflow_item_status VARCHAR,
        pim_workflow_item_timestamp VARCHAR,
        pim_workflow_item_user_name VARCHAR,
        supplierid VARCHAR,
        supplier VARCHAR,
        pim_standard_case_conversion VARCHAR,
        pim_batf_case_conversion VARCHAR,
        pim_9l_case_conversion VARCHAR,
        pim_item_juice_perc VARCHAR,
        federal_beverage_tax_cd VARCHAR,
        federal_beverage_tax_cd_desc VARCHAR,
        pim_sizevolume VARCHAR,
        pim_product_num VARCHAR,
        pim_review_source_1 VARCHAR,
        pim_rating_1 VARCHAR,
        pim_review_1 VARCHAR,
        pim_rating_1_dt VARCHAR,
        pim_reviewer_1 VARCHAR,
        pim_review_source_2 VARCHAR,
        pim_rating_2 VARCHAR,
        pim_review_2 VARCHAR,
        pim_rating_2_dt VARCHAR,
        pim_reviewer_2 VARCHAR,
        pim_review_source_3 VARCHAR,
        pim_rating_3 VARCHAR,
        pim_review_3 VARCHAR,
        pim_rating_3_dt VARCHAR,
        pim_reviewer_3 VARCHAR,
        pim_review_source_4 VARCHAR,
        pim_rating_4 VARCHAR,
        pim_review_4 VARCHAR,
        pim_rating_4_dt VARCHAR,
        pim_reviewer_4 VARCHAR,
        pim_producer_desc VARCHAR,
        pim_varieta_desc VARCHAR,
        pim_country_desc VARCHAR,
        pim_region_desc VARCHAR,
        pim_appellation_desc VARCHAR,
        pim_romantic_desc VARCHAR,
        corp_item_unit_weight VARCHAR,
        corp_item_unit_weight_uom VARCHAR,
        corp_item_pallet_weight VARCHAR,
        corp_item_pallet_weight_uom VARCHAR,
        pim_comment_subject VARCHAR,
        pim_vintage_brand VARCHAR,
        corp_item_holiday_gift VARCHAR,
        corp_item_outer_pack VARCHAR,
        pim_client_request VARCHAR,
        pim_region_cd VARCHAR,
        pim_sub_region_cd VARCHAR,
        pim_appellation_cd VARCHAR,
        pim_apel_villg_cd VARCHAR,
        pim_product_label_brand_cd VARCHAR,
        pim_product_label_brand_desc VARCHAR,
        pim_product_name VARCHAR,
        pim_product_material_cd VARCHAR,
        pim_product_material_desc VARCHAR,
        pim_product_sub_material_cd VARCHAR,
        pim_product_sub_material_desc VARCHAR,
        pim_product_varietal_cd VARCHAR,
        pim_product_varietal VARCHAR,
        pim_product_flavor_cd VARCHAR,
        pim_product_flavor VARCHAR,
        pim_product_proof VARCHAR,
        pim_product_age_statement VARCHAR,
        pim_product_age_statement_uom VARCHAR,
        pim_product_geo_designation_cd VARCHAR,
        pim_product_geo_designation_desc VARCHAR,
        pim_product_color_cd VARCHAR,
        pim_product_color VARCHAR,
        pim_product_creation_dt VARCHAR,
        pim_product_modified_dt VARCHAR,
        corp_item_sup_suppl_name VARCHAR,
        corp_item_sup_suppl_f_month VARCHAR,
        pim_item_long_desc VARCHAR,
        pim_suppl_name VARCHAR,
        pim_cicategory VARCHAR,
        pim_region VARCHAR,
        pim_country_of_origin VARCHAR,
        pim_sub_region_desc VARCHAR,
        pim_citype VARCHAR,
        pim_cisubtype VARCHAR,
        pim_root_node BIGINT,
        pim_root VARCHAR,
        pim_type_cd VARCHAR,
        pim_type_desc VARCHAR,
        pim_sub_type_cd VARCHAR,
        pim_sub_type_desc VARCHAR,
        pim_cannabinoids_type VARCHAR,
        pim_total_potency VARCHAR,
        pim_dosage VARCHAR,
        pim_fragrance VARCHAR,
        pim_cultivation VARCHAR,
        pim_terpenes VARCHAR,
        pim_anatomy VARCHAR,
        pim_gender VARCHAR,
        pim_count VARCHAR,
        pim_brand_type VARCHAR,
        pim_species VARCHAR,
        pim_strain VARCHAR,
        pim_extract_type VARCHAR,
        corp_suppl_zip_global VARCHAR,
        corp_suppl_zip_ext_global VARCHAR,
        pim_producer_cd VARCHAR,
        corp_item_size_long_desc VARCHAR,
        pim_item_varietal_cd VARCHAR,
        pim_item_varietal_desc VARCHAR,
        pim_item_upc_gtin_12 VARCHAR,
        pim_item_inner_pack_upc_gtin_12 VARCHAR,
        pim_item_is_deleted VARCHAR,
        pim_service_category VARCHAR,
        ready_to_drink_ind VARCHAR,
        rtd_manual_override_ind VARCHAR,
        organic_desc VARCHAR,
        biodynamic_desc VARCHAR,
        sustainable_desc VARCHAR,
        green_other_desc VARCHAR,
        kosher_type_desc VARCHAR,
        brand_ownership_type_desc VARCHAR,
        nutritional_information_desc VARCHAR,
        trade_practices_desc VARCHAR,
        wine_specific_desc VARCHAR,
        bordeaux_wine_classifications_desc VARCHAR,
        beer_spirits_specific_desc VARCHAR,
        supersession_ultimate_corp_item_no BIGINT,
        supersession_corp_item_seq_level VARCHAR,
        supersession_type_desc VARCHAR,
        national_service_model_sub_division VARCHAR,
        managing_director VARCHAR,
        regional_manager_east VARCHAR,
        regional_manager_central VARCHAR,
        regional_manager_west VARCHAR,
        avg_price_per_750_bottle_amt DECIMAL(18, 2),
        mixed_label_brand_flag VARCHAR,
        supplier_item_number VARCHAR,
        pim_item_inner_pack_scc VARCHAR,
        brand_preferred_case_conversion VARCHAR,
        formal_planning_scope_ind VARCHAR,
        pod_id VARCHAR,
        pod_name VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: V_D_CURR_CORP_ITEM
-- ============================================================================

SELECT
  corp_item_no,
  corp_item_desc,
  corp_item_long_desc,
  corp_item_prod_num,
  corp_item_brand,
  corp_item_brand_name,
  corp_item_suppl,
  corp_item_suppl_name,
  corp_item_prod_cat,
  corp_item_prod_cat_name,
  corp_item_prod_cat_cd,
  corp_item_prod_class,
  corp_item_prod_class_name,
  corp_item_prod_group,
  corp_item_pgrp_name,
  corp_item_prod_subg,
  corp_item_prod_sb_nm,
  corp_item_prod_super_group,
  corp_item_prod_super_group_name,
  corp_item_sup_suppl,
  corp_item_vintage,
  corp_item_flavor_cd,
  corp_item_flavor,
  corp_item_region,
  corp_item_region_name,
  corp_item_appelation,
  corp_item_appel_name,
  corp_item_cnty_orign,
  corp_item_cnty_name,
  corp_item_size,
  corp_item_uom,
  corp_item_wine_gal,
  corp_item_unit_vol,
  corp_item_proof,
  corp_item_unit_cbvol,
  corp_item_unit_heigt,
  corp_item_unit_width,
  corp_item_unit_legth,
  corp_item_unit_swght,
  corp_item_units_layr,
  corp_item_layer_palt,
  corp_item_bot_pack,
  corp_item_pack_case,
  corp_item_bttls_pcas,
  corp_item_upc,
  corp_item_scc,
  corp_item_pack_upc,
  corp_item_rep_cas_rt,
  corp_item_holgft_itm,
  corp_item_copack_itm,
  corp_item_pvtlbl_itm,
  corp_item_lblimg_fil,
  corp_item_prdimg_fil,
  corp_item_rating,
  corp_item_status,
  corp_item_alcoh_perc,
  corp_item_link_code,
  corp_item_crt_date,
  corp_item_crt_time,
  corp_item_crt_user,
  corp_item_upd_date,
  corp_item_upd_time,
  corp_item_upd_user,
  corp_item_ounc_unit,
  corp_item_ntype,
  corp_suppl_name,
  corp_suppl_ss_flag,
  corp_suppl_f_month,
  corp_suppl_vendor,
  corp_suppl_sapvnd_num,
  corp_suppl_mainvnd_num,
  corp_suppl_name2,
  corp_suppl_address1,
  corp_suppl_address2,
  corp_suppl_address3,
  corp_suppl_city,
  corp_suppl_region,
  corp_suppl_country,
  corp_suppl_zip,
  corp_suppl_zip_ext,
  corp_suppl_phone,
  corp_suppl_fax,
  corp_suppl_edi,
  corp_suppl_status,
  corp_suppl_listed_ind,
  corp_brand_group_flag,
  corp_brand_sup_brand,
  suppl_brand_name,
  type_code,
  subtyp_cod,
  reg_subreg,
  apel_villg_cod,
  apel_villg,
  accolades,
  age_statmt,
  mvintg_flg,
  mvintg_dsc,
  kosher_cod,
  kosher,
  materl_cod,
  material,
  packge_dsc,
  bot_height,
  bot_width,
  bot_length,
  bot_type_cod,
  bot_type,
  cas_ppallt,
  palt_dimns,
  palt_height,
  palt_lngth,
  palt_width,
  box_type_cod,
  box_type,
  closur_cod,
  closure,
  color_cod,
  color,
  design_cod,
  designation,
  dom_imp,
  fob_price,
  green_code,
  green,
  cert_green,
  cert_agncy,
  green_detl,
  prodcr_cod,
  producer,
  proprietary,
  shelf_life,
  ttb_code,
  sme_descr,
  classif_by,
  request_by,
  reqby_tims,
  approv_by,
  aprby_tims,
  varietal_code,
  varietal,
  reg_subreg_desc,
  type_desc,
  subtyp_desc,
  dom_botl,
  misc_cod,
  sa_code,
  sa_desc,
  rainbow_item_flag,
  rainbow_component_set_flag,
  is_deleted,
  purch_item_no,
  nir_ind,
  national_service_model,
  national_brand_manager,
  corp_suppl_f_periodstart,
  corp_item_status_desc,
  pim_item_no,
  pim_item_category_cd,
  pim_item_category_desc,
  pim_item_class_cd,
  pim_item_class_desc,
  pim_item_sub_class_cd,
  pim_item_sub_class_desc,
  pim_suppl_item_desc,
  pim_suppl_item_status,
  pim_suppl_item_discontinued_dt,
  pim_brand_effective_dt,
  pim_requested_label_brand,
  pim_replacement_item_effective_dt,
  pim_ready_approval_ind,
  pim_sample_ind,
  pim_tasting_notes,
  age_statmt_uom,
  pim_proof_gallons,
  pim_proof_liters,
  sub_material_cd,
  sub_material_desc,
  pim_cork_type,
  corp_item_rating_dt,
  pim_ttb_cola_id_valid_ind,
  marketing_cd,
  marketing_desc,
  pim_collector_special_label,
  pim_gift_component,
  nielsen_upc,
  pim_premise_type,
  pim_special_container,
  pim_dom_imp_desc,
  pim_bottling_packge_country,
  pim_volume_uom_desc,
  pim_volume_uom_cd,
  corp_item_unit_height_uom,
  corp_item_unit_length_depth_uom,
  corp_item_unit_width_uom,
  corp_item_liter_per_unit,
  corp_item_case_weight_uom,
  corp_item_case_height_uom,
  corp_item_case_length_depth_uom,
  corp_item_case_width_uom,
  corp_item_pallet_height_uom,
  corp_item_pallet_length_depth_uom,
  corp_item_pallet_width_uom,
  corp_item_pack_upc_effective_dt,
  corp_item_pack_upc_override,
  corp_item_pack_ean,
  corp_item_pack_ean_effective_dt,
  corp_item_upc_override,
  corp_item_upc_effective_dt,
  corp_item_ean,
  corp_item_ean_effective_dt,
  corp_item_scc_override,
  corp_item_scc_effective_dt,
  pim_reason_cd,
  pim_reason_desc,
  pim_replacement_id_type_cd,
  pim_replacement_id_type_desc,
  pim_item_status_setup,
  pim_replacement_id,
  pim_replaced_by_user_name,
  pim_notes,
  pim_supplier_item_comment,
  pim_supplier_item_comment_dt,
  pim_supplier_item_comment_desc,
  pim_workflow_item_status,
  pim_workflow_item_timestamp,
  pim_workflow_item_user_name,
  supplierid,
  supplier,
  pim_standard_case_conversion,
  pim_batf_case_conversion,
  pim_9l_case_conversion,
  pim_item_juice_perc,
  federal_beverage_tax_cd,
  federal_beverage_tax_cd_desc,
  pim_sizevolume,
  pim_product_num,
  pim_review_source_1,
  pim_rating_1,
  pim_review_1,
  pim_rating_1_dt,
  pim_reviewer_1,
  pim_review_source_2,
  pim_rating_2,
  pim_review_2,
  pim_rating_2_dt,
  pim_reviewer_2,
  pim_review_source_3,
  pim_rating_3,
  pim_review_3,
  pim_rating_3_dt,
  pim_reviewer_3,
  pim_review_source_4,
  pim_rating_4,
  pim_review_4,
  pim_rating_4_dt,
  pim_reviewer_4,
  pim_producer_desc,
  pim_varieta_desc,
  pim_country_desc,
  pim_region_desc,
  pim_appellation_desc,
  pim_romantic_desc,
  corp_item_unit_weight,
  corp_item_unit_weight_uom,
  corp_item_pallet_weight,
  corp_item_pallet_weight_uom,
  pim_comment_subject,
  pim_vintage_brand,
  corp_item_holiday_gift,
  corp_item_outer_pack,
  pim_client_request,
  pim_region_cd,
  pim_sub_region_cd,
  pim_appellation_cd,
  pim_apel_villg_cd,
  pim_product_label_brand_cd,
  pim_product_label_brand_desc,
  pim_product_name,
  pim_product_material_cd,
  pim_product_material_desc,
  pim_product_sub_material_cd,
  pim_product_sub_material_desc,
  pim_product_varietal_cd,
  pim_product_varietal,
  pim_product_flavor_cd,
  pim_product_flavor,
  pim_product_proof,
  pim_product_age_statement,
  pim_product_age_statement_uom,
  pim_product_geo_designation_cd,
  pim_product_geo_designation_desc,
  pim_product_color_cd,
  pim_product_color,
  pim_product_creation_dt,
  pim_product_modified_dt,
  corp_item_sup_suppl_name,
  corp_item_sup_suppl_f_month,
  pim_item_long_desc,
  pim_suppl_name,
  pim_cicategory,
  pim_region,
  pim_country_of_origin,
  pim_sub_region_desc,
  pim_citype,
  pim_cisubtype,
  pim_root_node,
  pim_root,
  pim_type_cd,
  pim_type_desc,
  pim_sub_type_cd,
  pim_sub_type_desc,
  pim_cannabinoids_type,
  pim_total_potency,
  pim_dosage,
  pim_fragrance,
  pim_cultivation,
  pim_terpenes,
  pim_anatomy,
  pim_gender,
  pim_count,
  pim_brand_type,
  pim_species,
  pim_strain,
  pim_extract_type,
  corp_suppl_zip_global,
  corp_suppl_zip_ext_global,
  pim_producer_cd,
  corp_item_size_long_desc,
  pim_item_varietal_cd,
  pim_item_varietal_desc,
  pim_item_upc_gtin_12,
  pim_item_inner_pack_upc_gtin_12,
  pim_item_is_deleted,
  pim_service_category,
  ready_to_drink_ind,
  rtd_manual_override_ind,
  organic_desc,
  biodynamic_desc,
  sustainable_desc,
  green_other_desc,
  kosher_type_desc,
  brand_ownership_type_desc,
  nutritional_information_desc,
  trade_practices_desc,
  wine_specific_desc,
  bordeaux_wine_classifications_desc,
  beer_spirits_specific_desc,
  supersession_ultimate_corp_item_no,
  supersession_corp_item_seq_level,
  supersession_type_desc,
  national_service_model_sub_division,
  managing_director,
  regional_manager_east,
  regional_manager_central,
  regional_manager_west,
  avg_price_per_750_bottle_amt,
  mixed_label_brand_flag,
  supplier_item_number,
  pim_item_inner_pack_scc,
  brand_preferred_case_conversion,
  formal_planning_scope_ind,
  pod_id,
  pod_name
FROM SEED();
