MODEL (
  name web_analytics_seeds.V_D_CUSTOMER,
  kind SEED (
    path '../../seeds/v_d_customer.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Static customer reference data from source system',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('v_d_customer'),
  -- ID columns as VARCHAR so alphanumeric values (e.g. S3H3XLW4IUQPV) load without error; silver coerces to numeric
  columns (
        customer_sk VARCHAR,
        site VARCHAR,
        customer_no VARCHAR,
        customer_name VARCHAR,
        address_1 VARCHAR,
        address_2 VARCHAR,
        city VARCHAR,
        state VARCHAR,
        zip BIGINT,
        county BIGINT,
        premise_code VARCHAR,
        liquor_rating BIGINT,
        wine_rating BIGINT,
        status VARCHAR,
        selling_div_sk BIGINT,
        selling_div_no BIGINT,
        bdn_license_type VARCHAR,
        rating VARCHAR,
        family_code VARCHAR,
        family_name VARCHAR,
        location VARCHAR,
        location_name VARCHAR,
        merchandiser1 VARCHAR,
        merchandiser2 VARCHAR,
        merchandiser3 VARCHAR,
        ethnic_type VARCHAR,
        ethnic_type_desc VARCHAR,
        license_type VARCHAR,
        license_class VARCHAR,
        license_name VARCHAR,
        class_name VARCHAR,
        store_type VARCHAR,
        store_type_desc VARCHAR,
        liquor_case_vol DECIMAL(18, 4),
        wine_case_vol DECIMAL(18, 4),
        total_case_vol DECIMAL(18, 4),
        liquor_dlr_vol DECIMAL(18, 4),
        wine_dollar_vol DECIMAL(18, 4),
        tot_dollar_vol DECIMAL(18, 4),
        phone_no VARCHAR,
        contact VARCHAR,
        new_customer_no VARCHAR,
        old_customer_no VARCHAR,
        chain_id VARCHAR,
        chain_name VARCHAR,
        chain_type VARCHAR,
        chain_class VARCHAR,
        chain_class_desc VARCHAR,
        chain_type_desc VARCHAR,
        chain_active_cd VARCHAR,
        state_chain_no BIGINT,
        state_chain_name VARCHAR,
        corp_chain_no BIGINT,
        corp_chain_name VARCHAR,
        corp_chain_class VARCHAR,
        corp_chain_class_desc VARCHAR,
        corp_chain_type VARCHAR,
        corp_chain_type_desc VARCHAR,
        corp_sp_prem_cd VARCHAR,
        corp_sp_premise VARCHAR,
        corp_prty_cd VARCHAR,
        corp_rpt_type VARCHAR,
        ar_group_acct_no BIGINT,
        chain_supvsr_no BIGINT,
        lockbox VARCHAR,
        deactivate_dt VARCHAR,
        sfa_include VARCHAR,
        fax_no VARCHAR,
        license_classification VARCHAR,
        zip_ext VARCHAR,
        bill_to_cust_no BIGINT,
        check_avrg VARCHAR,
        wine_list_size VARCHAR,
        by_the_glass VARCHAR,
        well_pct VARCHAR,
        wine_list_pct VARCHAR,
        floor_mrch_lvl VARCHAR,
        bck_room_strg_lvl VARCHAR,
        wine_prservsys_flg VARCHAR,
        vis_back_bar_flg VARCHAR,
        table_tent_flg VARCHAR,
        cord_drnklst_flg VARCHAR,
        cndct_promo_flg VARCHAR,
        hgh_prof_chef_flg VARCHAR,
        mini_bar_flg VARCHAR,
        cold_box_flg VARCHAR,
        chalet_flg VARCHAR,
        cntrl_whs_flg VARCHAR,
        gen_hse_wine_flg VARCHAR,
        variet_hse_wine_flg VARCHAR,
        imprt_hse_wine_flg VARCHAR,
        dmstic_hse_wine_flg VARCHAR,
        dmstic_imprt_flg VARCHAR,
        newspapr_adv_flg VARCHAR,
        newsletr_adv_flg VARCHAR,
        stre_adv_flg VARCHAR,
        window_adv_flg VARCHAR,
        tv_adv_flg VARCHAR,
        radio_adv_flg VARCHAR,
        magazine_adv_flg VARCHAR,
        flyr_adv_flg VARCHAR,
        commissionable_acct_flg VARCHAR,
        last_ord_dt VARCHAR,
        acct_type_cd VARCHAR,
        stdlinxscd VARCHAR,
        county_name VARCHAR,
        commission_acct VARCHAR,
        credit_cd VARCHAR,
        credit_limit DECIMAL(18, 4),
        dist_cluster VARCHAR,
        on_sales_ind VARCHAR,
        past_due_flg VARCHAR,
        priority_cd VARCHAR,
        prog_cluster VARCHAR,
        terms_cd VARCHAR,
        user_name VARCHAR,
        modified_user VARCHAR,
        effective_from_dt VARCHAR,
        effective_thru_dt VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR,
        current_ind VARCHAR,
        src_desc VARCHAR,
        active_ind VARCHAR,
        license VARCHAR,
        univ_customer_no VARCHAR,
        corp_vip_chain_cd VARCHAR,
        customer_create_date VARCHAR,
        rpt_sales_org_code VARCHAR,
        rpt_sales_org_desc VARCHAR,
        rpt_sales_org_short_desc VARCHAR,
        rpt_channel_code VARCHAR,
        rpt_channel_desc VARCHAR,
        rpt_channel_short_desc VARCHAR,
        rpt_sub_channel_code VARCHAR,
        rpt_sub_channel_desc VARCHAR,
        rpt_sub_channel_short_desc VARCHAR,
        rpt_ship_type_code VARCHAR,
        rpt_ship_type_desc VARCHAR,
        rpt_ship_type_short_desc VARCHAR,
        alt_license_number VARCHAR,
        billto_customer_name VARCHAR,
        billto_address_1 VARCHAR,
        billto_address_2 VARCHAR,
        billto_city VARCHAR,
        billto_state VARCHAR,
        billto_zip VARCHAR,
        billto_county VARCHAR,
        billto_county_name VARCHAR,
        primary_email_address VARCHAR,
        deliquent_flg VARCHAR,
        delv_day_ind VARCHAR,
        sun_delv VARCHAR,
        mon_delv VARCHAR,
        tue_delv VARCHAR,
        wed_delv VARCHAR,
        thu_delv VARCHAR,
        fri_delv VARCHAR,
        sat_delv VARCHAR,
        delv_wind1_start VARCHAR,
        delv_wind1_end VARCHAR,
        delv_wind2_start VARCHAR,
        delv_wind2_end VARCHAR,
        billing_zone VARCHAR,
        license_exp_date VARCHAR,
        alcohol_license_status VARCHAR,
        current_ar_bal DECIMAL(18, 4),
        ar_aging_p1_bal DECIMAL(18, 4),
        ar_aging_p2_bal DECIMAL(18, 4),
        ar_aging_p3_bal DECIMAL(18, 4),
        ar_aging_p4_bal DECIMAL(18, 4),
        ar_aging_p1_desc VARCHAR,
        ar_aging_p2_desc VARCHAR,
        ar_aging_p3_desc VARCHAR,
        ar_aging_p4_desc VARCHAR,
        total_ar_bal DECIMAL(18, 4),
        ar_past_due_amt DECIMAL(18, 2),
        rtm_national_chain_code VARCHAR,
        rtm_national_chain_desc VARCHAR,
        rtm_national_channel_code VARCHAR,
        rtm_national_channel_desc VARCHAR,
        rtm_national_sub_channel_code VARCHAR,
        rtm_national_sub_channel_desc VARCHAR,
        rtm_emerging_ind VARCHAR,
        rtm_national_acct_vp VARCHAR,
        rtm_national_acct_director VARCHAR,
        rtm_national_acct_ops_analyst VARCHAR,
        source_system VARCHAR,
        check_sum VARCHAR,
        bdn_license_type_desc VARCHAR,
        credit_cd_desc VARCHAR,
        terms_cd_desc VARCHAR,
        selling_div_name VARCHAR,
        is_deleted VARCHAR,
        selling_div_group_name VARCHAR,
        cust_level1_no BIGINT,
        cust_level1_name VARCHAR,
        cust_level3_no BIGINT,
        cust_level3_name VARCHAR,
        customer_route_no VARCHAR,
        customer_promo_cd VARCHAR,
        customer_price_list_cd VARCHAR,
        beer_traffic_cd VARCHAR,
        spirit_traffic_cd VARCHAR,
        wine_traffic_cd VARCHAR,
        item_authorization_list_id VARCHAR,
        primary_warehouse VARCHAR,
        cod_terms_code_flg VARCHAR,
        ar_terms_code VARCHAR,
        ar_terms_code_desc VARCHAR,
        cod_reason_code VARCHAR,
        cod_reason_code_desc VARCHAR,
        cust_updated_flg VARCHAR,
        cust_special_price_flg VARCHAR,
        cust_street_deals_flg VARCHAR,
        cust_lock_profile_flg VARCHAR,
        customer_latitude DECIMAL(18, 4),
        customer_longitude DECIMAL(18, 4),
        customer_service_level VARCHAR,
        delivery_priority VARCHAR,
        customer_acct_type_desc VARCHAR,
        ar_group_custmast_acct_no BIGINT,
        ar_group_custmast_business_name VARCHAR,
        ar_group_business_name VARCHAR,
        chain_store_no BIGINT,
        chain_embed_delivery_charge_ind VARCHAR,
        chain_delivery_charge_override_amt DECIMAL(18, 2),
        chain_discount_profile_on_premise VARCHAR,
        chain_discount_profile_off_premise VARCHAR,
        activated_acct VARCHAR,
        registered_acct VARCHAR,
        proof_of_eligible_acct VARCHAR,
        multi_account_flg VARCHAR,
        average_days_pay_count VARCHAR,
        ar_account_type VARCHAR,
        credit_clerk_cd VARCHAR,
        commits_overdue_flg VARCHAR,
        ar_credit_condition_cd_2 VARCHAR,
        ar_credit_condition_cd_3 VARCHAR,
        nsf_flg VARCHAR,
        ar_write_off_amt DECIMAL(18, 2),
        last_write_off_dt VARCHAR,
        write_off_charge_service_bad_debt_ind VARCHAR,
        items_authorized_ind VARCHAR,
        bill_to_phone_no VARCHAR,
        outlet_type_short_desc VARCHAR,
        dms_flg VARCHAR,
        accepts_cases_only_ind VARCHAR,
        customer_route_desc VARCHAR,
        chain_broad_mkt_allocation VARCHAR,
        primary_salesperson_no BIGINT,
        last_pay_date VARCHAR,
        billto_zip_ext VARCHAR,
        delivery_freq_code VARCHAR,
        delivery_freq_desc VARCHAR,
        owner_name VARCHAR,
        owner_address1 VARCHAR,
        owner_address2 VARCHAR,
        owner_city VARCHAR,
        owner_state VARCHAR,
        owner_zip_cd VARCHAR,
        owner_zip_cd_plus VARCHAR,
        license_effective_dt VARCHAR,
        state_excise_tax_exempt_cd VARCHAR,
        license_status_short_desc VARCHAR,
        license_status_long_desc VARCHAR,
        dual_license_ind VARCHAR,
        credit_clerk_name VARCHAR,
        ar_credit_condition_long_desc_1 VARCHAR,
        ar_credit_condition_short_desc_1 VARCHAR,
        ar_credit_condition_long_desc_2 VARCHAR,
        ar_credit_condition_short_desc_2 VARCHAR,
        ar_credit_condition_long_desc_3 VARCHAR,
        ar_credit_condition_short_desc_3 VARCHAR,
        discount_profile VARCHAR,
        state_sales_tax_no BIGINT,
        cust_split_by_product_type_ind VARCHAR,
        bypass_state_reporting_ind VARCHAR,
        chain_cust_split_by_product_type_ind VARCHAR,
        chain_bypass_state_reporting_ind VARCHAR,
        credit_comments VARCHAR,
        next_delivery_date VARCHAR,
        price_code VARCHAR,
        delivery_route_stops_cnt VARCHAR,
        time_open_for_business VARCHAR,
        time_closed_for_business VARCHAR,
        delivery_instruction_1 VARCHAR,
        delivery_instruction_2 VARCHAR,
        bill_to_email_address VARCHAR,
        bill_to_email_address_2 VARCHAR,
        po_no_required_ind BIGINT,
        actual_credit_limit DECIMAL(18, 4),
        seasonal_credit_limit DECIMAL(18, 4),
        seasonal_credit_limit_start_dt VARCHAR,
        seasonal_credit_limit_end_dt VARCHAR,
        added_by_user_name VARCHAR,
        warehouse_permit_no BIGINT
  )
);

-- ============================================================================
-- SEED DATA: V_D_CUSTOMER
-- ============================================================================

SELECT
  customer_sk,
  site,
  customer_no,
  customer_name,
  address_1,
  address_2,
  city,
  state,
  zip,
  county,
  premise_code,
  liquor_rating,
  wine_rating,
  status,
  selling_div_sk,
  selling_div_no,
  bdn_license_type,
  rating,
  family_code,
  family_name,
  location,
  location_name,
  merchandiser1,
  merchandiser2,
  merchandiser3,
  ethnic_type,
  ethnic_type_desc,
  license_type,
  license_class,
  license_name,
  class_name,
  store_type,
  store_type_desc,
  liquor_case_vol,
  wine_case_vol,
  total_case_vol,
  liquor_dlr_vol,
  wine_dollar_vol,
  tot_dollar_vol,
  phone_no,
  contact,
  new_customer_no,
  old_customer_no,
  chain_id,
  chain_name,
  chain_type,
  chain_class,
  chain_class_desc,
  chain_type_desc,
  chain_active_cd,
  state_chain_no,
  state_chain_name,
  corp_chain_no,
  corp_chain_name,
  corp_chain_class,
  corp_chain_class_desc,
  corp_chain_type,
  corp_chain_type_desc,
  corp_sp_prem_cd,
  corp_sp_premise,
  corp_prty_cd,
  corp_rpt_type,
  ar_group_acct_no,
  chain_supvsr_no,
  lockbox,
  deactivate_dt,
  sfa_include,
  fax_no,
  license_classification,
  zip_ext,
  bill_to_cust_no,
  check_avrg,
  wine_list_size,
  by_the_glass,
  well_pct,
  wine_list_pct,
  floor_mrch_lvl,
  bck_room_strg_lvl,
  wine_prservsys_flg,
  vis_back_bar_flg,
  table_tent_flg,
  cord_drnklst_flg,
  cndct_promo_flg,
  hgh_prof_chef_flg,
  mini_bar_flg,
  cold_box_flg,
  chalet_flg,
  cntrl_whs_flg,
  gen_hse_wine_flg,
  variet_hse_wine_flg,
  imprt_hse_wine_flg,
  dmstic_hse_wine_flg,
  dmstic_imprt_flg,
  newspapr_adv_flg,
  newsletr_adv_flg,
  stre_adv_flg,
  window_adv_flg,
  tv_adv_flg,
  radio_adv_flg,
  magazine_adv_flg,
  flyr_adv_flg,
  commissionable_acct_flg,
  last_ord_dt,
  acct_type_cd,
  stdlinxscd,
  county_name,
  commission_acct,
  credit_cd,
  credit_limit,
  dist_cluster,
  on_sales_ind,
  past_due_flg,
  priority_cd,
  prog_cluster,
  terms_cd,
  user_name,
  modified_user,
  effective_from_dt,
  effective_thru_dt,
  load_dt,
  modified_dt,
  current_ind,
  src_desc,
  active_ind,
  license,
  univ_customer_no,
  corp_vip_chain_cd,
  customer_create_date,
  rpt_sales_org_code,
  rpt_sales_org_desc,
  rpt_sales_org_short_desc,
  rpt_channel_code,
  rpt_channel_desc,
  rpt_channel_short_desc,
  rpt_sub_channel_code,
  rpt_sub_channel_desc,
  rpt_sub_channel_short_desc,
  rpt_ship_type_code,
  rpt_ship_type_desc,
  rpt_ship_type_short_desc,
  alt_license_number,
  billto_customer_name,
  billto_address_1,
  billto_address_2,
  billto_city,
  billto_state,
  billto_zip,
  billto_county,
  billto_county_name,
  primary_email_address,
  deliquent_flg,
  delv_day_ind,
  sun_delv,
  mon_delv,
  tue_delv,
  wed_delv,
  thu_delv,
  fri_delv,
  sat_delv,
  delv_wind1_start,
  delv_wind1_end,
  delv_wind2_start,
  delv_wind2_end,
  billing_zone,
  license_exp_date,
  alcohol_license_status,
  current_ar_bal,
  ar_aging_p1_bal,
  ar_aging_p2_bal,
  ar_aging_p3_bal,
  ar_aging_p4_bal,
  ar_aging_p1_desc,
  ar_aging_p2_desc,
  ar_aging_p3_desc,
  ar_aging_p4_desc,
  total_ar_bal,
  ar_past_due_amt,
  rtm_national_chain_code,
  rtm_national_chain_desc,
  rtm_national_channel_code,
  rtm_national_channel_desc,
  rtm_national_sub_channel_code,
  rtm_national_sub_channel_desc,
  rtm_emerging_ind,
  rtm_national_acct_vp,
  rtm_national_acct_director,
  rtm_national_acct_ops_analyst,
  source_system,
  check_sum,
  bdn_license_type_desc,
  credit_cd_desc,
  terms_cd_desc,
  selling_div_name,
  is_deleted,
  selling_div_group_name,
  cust_level1_no,
  cust_level1_name,
  cust_level3_no,
  cust_level3_name,
  customer_route_no,
  customer_promo_cd,
  customer_price_list_cd,
  beer_traffic_cd,
  spirit_traffic_cd,
  wine_traffic_cd,
  item_authorization_list_id,
  primary_warehouse,
  cod_terms_code_flg,
  ar_terms_code,
  ar_terms_code_desc,
  cod_reason_code,
  cod_reason_code_desc,
  cust_updated_flg,
  cust_special_price_flg,
  cust_street_deals_flg,
  cust_lock_profile_flg,
  customer_latitude,
  customer_longitude,
  customer_service_level,
  delivery_priority,
  customer_acct_type_desc,
  ar_group_custmast_acct_no,
  ar_group_custmast_business_name,
  ar_group_business_name,
  chain_store_no,
  chain_embed_delivery_charge_ind,
  chain_delivery_charge_override_amt,
  chain_discount_profile_on_premise,
  chain_discount_profile_off_premise,
  activated_acct,
  registered_acct,
  proof_of_eligible_acct,
  multi_account_flg,
  average_days_pay_count,
  ar_account_type,
  credit_clerk_cd,
  commits_overdue_flg,
  ar_credit_condition_cd_2,
  ar_credit_condition_cd_3,
  nsf_flg,
  ar_write_off_amt,
  last_write_off_dt,
  write_off_charge_service_bad_debt_ind,
  items_authorized_ind,
  bill_to_phone_no,
  outlet_type_short_desc,
  dms_flg,
  accepts_cases_only_ind,
  customer_route_desc,
  chain_broad_mkt_allocation,
  primary_salesperson_no,
  last_pay_date,
  billto_zip_ext,
  delivery_freq_code,
  delivery_freq_desc,
  owner_name,
  owner_address1,
  owner_address2,
  owner_city,
  owner_state,
  owner_zip_cd,
  owner_zip_cd_plus,
  license_effective_dt,
  state_excise_tax_exempt_cd,
  license_status_short_desc,
  license_status_long_desc,
  dual_license_ind,
  credit_clerk_name,
  ar_credit_condition_long_desc_1,
  ar_credit_condition_short_desc_1,
  ar_credit_condition_long_desc_2,
  ar_credit_condition_short_desc_2,
  ar_credit_condition_long_desc_3,
  ar_credit_condition_short_desc_3,
  discount_profile,
  state_sales_tax_no,
  cust_split_by_product_type_ind,
  bypass_state_reporting_ind,
  chain_cust_split_by_product_type_ind,
  chain_bypass_state_reporting_ind,
  credit_comments,
  next_delivery_date,
  price_code,
  delivery_route_stops_cnt,
  time_open_for_business,
  time_closed_for_business,
  delivery_instruction_1,
  delivery_instruction_2,
  bill_to_email_address,
  bill_to_email_address_2,
  po_no_required_ind,
  actual_credit_limit,
  seasonal_credit_limit,
  seasonal_credit_limit_start_dt,
  seasonal_credit_limit_end_dt,
  added_by_user_name,
  warehouse_permit_no
FROM SEED();
