MODEL (
  name web_analytics_seeds.F_ORDER_ALL,
  kind SEED (
    path '../../seeds/f_order_all.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Historical order transaction seed data for testing and development',
  tags ('seed', 'reference_data', 'transactional', 'testing'),
  terms ('f_order_all'),
  columns (
        order_sk BIGINT,
        site_sk BIGINT,
        posting_prd_sk BIGINT,
        item_sk BIGINT,
        customer_sk BIGINT,
        warehouse_sk BIGINT,
        order_reject_sk BIGINT,
        order_status_sk BIGINT,
        site_id VARCHAR,
        item_no VARCHAR,
        posting_period BIGINT,
        customer_no VARCHAR,
        order_no VARCHAR,
        order_line_no BIGINT,
        order_status_cd VARCHAR,
        order_entry_dt DATE,
        order_entry_time BIGINT,
        order_entry_cd VARCHAR,
        order_entered_by VARCHAR,
        order_cases_qty BIGINT,
        order_bottle_qty BIGINT,
        cases_dec_equivalent DECIMAL(15, 3),
        order_price_per_case DECIMAL(18, 2),
        order_dsct_per_case DECIMAL(18, 4),
        order_net_amt DECIMAL(18, 2),
        order_reject_cd VARCHAR,
        order_reject_dt DATE,
        order_reject_time BIGINT,
        order_reject_by VARCHAR,
        invoice_no BIGINT,
        invoice_line_no BIGINT,
        invoice_dt DATE,
        warehouse_no BIGINT,
        load_dt VARCHAR,
        load_id BIGINT,
        modified_dt VARCHAR,
        modified_user VARCHAR,
        src_desc VARCHAR,
        sales_sk BIGINT,
        source_system VARCHAR,
        request_delivery_dt_sk DATE,
        order_type_sk BIGINT,
        order_type_cd VARCHAR,
        order_category VARCHAR,
        order_line_category VARCHAR,
        order_doc_object_cd VARCHAR,
        order_unit_cd VARCHAR,
        order_reject_reason_sk BIGINT,
        order_reject_reason_cd VARCHAR,
        order_salesperson_sk BIGINT,
        order_salesperson VARCHAR,
        order_ref_doc_no BIGINT,
        order_ref_line_no BIGINT,
        is_deleted VARCHAR,
        credit_chk_status VARCHAR,
        overall_delivery_status VARCHAR,
        order_delivery_block_cd VARCHAR,
        order_external_id VARCHAR,
        order_cancel_error_msg VARCHAR,
        order_billing_type VARCHAR,
        order_invoice_type VARCHAR,
        order_bill_hold_flag VARCHAR,
        purcahse_order_no VARCHAR,
        order_special_instructions_1 VARCHAR,
        order_special_instructions_2 VARCHAR,
        order_line_cost_amt DECIMAL(18, 2),
        combo_promo_buy_get_flag VARCHAR,
        order_route_no BIGINT,
        order_depot_no BIGINT,
        order_route_sk BIGINT,
        order_depot_sk BIGINT,
        order_billing_status_cd VARCHAR,
        order_entered_by_salesperson_no BIGINT,
        order_promo_no BIGINT,
        order_reserve_stock_status VARCHAR,
        backorder_bottles_qty BIGINT,
        backorder_cases_qty BIGINT,
        credit_reason_cd BIGINT,
        inv_subtype_cd VARCHAR,
        ship_via_cd VARCHAR,
        call_in_sales_rep_no BIGINT,
        customer_delivery_priority BIGINT,
        ref_promo_sequence_no BIGINT,
        ref_promo_no BIGINT,
        ref_promo_discount_cd VARCHAR,
        ref_promo_buy_get_ind VARCHAR,
        order_approval_status VARCHAR,
        original_item_number BIGINT,
        approved_by_user VARCHAR,
        water_invoice_yes_or_no VARCHAR,
        entered_by_user VARCHAR,
        orig_order_case_qty BIGINT,
        orig_order_bottle_qty BIGINT,
        adj_order_case_qty BIGINT,
        adj_order_bottle_qty BIGINT,
        adj_order_qty_dec_equ DECIMAL(15, 3),
        orig_order_qty_dec_equ DECIMAL(15, 3)
  )
);

-- ============================================================================
-- SEED DATA: F_ORDER_ALL
-- ============================================================================

SELECT
  order_sk,
  site_sk,
  posting_prd_sk,
  item_sk,
  customer_sk,
  warehouse_sk,
  order_reject_sk,
  order_status_sk,
  site_id,
  item_no,
  posting_period,
  customer_no,
  order_no,
  order_line_no,
  order_status_cd,
  order_entry_dt,
  order_entry_time,
  order_entry_cd,
  order_entered_by,
  order_cases_qty,
  order_bottle_qty,
  cases_dec_equivalent,
  order_price_per_case,
  order_dsct_per_case,
  order_net_amt,
  order_reject_cd,
  order_reject_dt,
  order_reject_time,
  order_reject_by,
  invoice_no,
  invoice_line_no,
  invoice_dt,
  warehouse_no,
  load_dt,
  load_id,
  modified_dt,
  modified_user,
  src_desc,
  sales_sk,
  source_system,
  request_delivery_dt_sk,
  order_type_sk,
  order_type_cd,
  order_category,
  order_line_category,
  order_doc_object_cd,
  order_unit_cd,
  order_reject_reason_sk,
  order_reject_reason_cd,
  order_salesperson_sk,
  order_salesperson,
  order_ref_doc_no,
  order_ref_line_no,
  is_deleted,
  credit_chk_status,
  overall_delivery_status,
  order_delivery_block_cd,
  order_external_id,
  order_cancel_error_msg,
  order_billing_type,
  order_invoice_type,
  order_bill_hold_flag,
  purcahse_order_no,
  order_special_instructions_1,
  order_special_instructions_2,
  order_line_cost_amt,
  combo_promo_buy_get_flag,
  order_route_no,
  order_depot_no,
  order_route_sk,
  order_depot_sk,
  order_billing_status_cd,
  order_entered_by_salesperson_no,
  order_promo_no,
  order_reserve_stock_status,
  backorder_bottles_qty,
  backorder_cases_qty,
  credit_reason_cd,
  inv_subtype_cd,
  ship_via_cd,
  call_in_sales_rep_no,
  customer_delivery_priority,
  ref_promo_sequence_no,
  ref_promo_no,
  ref_promo_discount_cd,
  ref_promo_buy_get_ind,
  order_approval_status,
  original_item_number,
  approved_by_user,
  water_invoice_yes_or_no,
  entered_by_user,
  orig_order_case_qty,
  orig_order_bottle_qty,
  adj_order_case_qty,
  adj_order_bottle_qty,
  adj_order_qty_dec_equ,
  orig_order_qty_dec_equ
FROM SEED();
