MODEL (
  name web_analytics_seeds.F_SALES_ALL,
  kind SEED (
    path '../../seeds/f_sales_all.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Historical sales transaction seed data for testing and development',
  tags ('seed', 'reference_data', 'transactional', 'testing'),
  terms ('f_sales_all'),
  columns (
        sales_sk BIGINT,
        posting_prd_sk BIGINT,
        posting_dt_sk DATE,
        item_sk BIGINT,
        customer_sk BIGINT,
        warehouse_sk BIGINT,
        current_salesperson_sk BIGINT,
        salesperson_sk BIGINT,
        invoice_dt_sk DATE,
        invoice_no BIGINT,
        sequence_no BIGINT,
        ref_inv_no BIGINT,
        qty_dec_equ DECIMAL(15, 3),
        ext_net DECIMAL(18, 2),
        ext_cost DECIMAL(18, 2),
        ext_dsct DECIMAL(18, 4),
        ext_participation DECIMAL(18, 4),
        ext_depl_allow DECIMAL(18, 4),
        cases BIGINT,
        bottles BIGINT,
        combo_no VARCHAR,
        purcahse_order_no VARCHAR,
        dsct_qualifier BIGINT,
        orig_case_qty BIGINT,
        dsct_per_case DECIMAL(18, 4),
        unit_breakage_amt DECIMAL(18, 2),
        recovery_amt DECIMAL(18, 2),
        ext_guaranteed_adj DECIMAL(18, 4),
        reference_dt DATE,
        orig_bottle_qty BIGINT,
        converted_cases DECIMAL(15, 3),
        unit_price DECIMAL(18, 2),
        master_bill VARCHAR,
        orig_inv_line_item_no BIGINT,
        orig_inv_pst_per BIGINT,
        orig_inv_warehouse BIGINT,
        ship_dt VARCHAR,
        state_tax DECIMAL(18, 4),
        sws_cqd_amt DECIMAL(18, 2),
        cqd_amt DECIMAL(18, 2),
        chksum VARCHAR,
        modified_user VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR,
        src_desc VARCHAR,
        site_sk BIGINT,
        route_no VARCHAR,
        stop_no VARCHAR,
        driver_no VARCHAR,
        whs_ship_loc VARCHAR,
        depot_no BIGINT,
        site VARCHAR,
        warehouse_no VARCHAR,
        customer_no VARCHAR,
        item_no VARCHAR,
        tpz_combo BIGINT,
        salesman_no VARCHAR,
        source_system VARCHAR,
        document_type VARCHAR,
        reason_cd VARCHAR,
        combo_option VARCHAR,
        discount_origin VARCHAR,
        adjustment_cd VARCHAR,
        dsct_category VARCHAR,
        entry_origin VARCHAR,
        day_bill_cd VARCHAR,
        void_cd VARCHAR,
        manifest_flg VARCHAR,
        reg_nght_shp_flg VARCHAR,
        ship_line_type VARCHAR,
        inv_subtype_cd VARCHAR,
        delivery_pickup_flg VARCHAR,
        billing_type_cd VARCHAR,
        slstax_chrgbk_flg VARCHAR,
        posting_prd BIGINT,
        item_hist_sk BIGINT,
        customer_hist_sk BIGINT,
        warehouse_hist_sk BIGINT,
        salesperson_hist_sk BIGINT,
        current_salesperson_hist_sk BIGINT,
        profit_center_sk BIGINT,
        profit_center_cd VARCHAR,
        order_no BIGINT,
        order_line_no BIGINT,
        invoice_sales_unit_cd VARCHAR,
        state_tax_exempt_amt DECIMAL(18, 2),
        cost_goods_sold_amt DECIMAL(18, 2),
        da_amt DECIMAL(18, 2),
        nda_amt DECIMAL(18, 2),
        tax_chargeback_amt DECIMAL(18, 2),
        total_breakage_amt DECIMAL(18, 2),
        call_in_sales_rep_no BIGINT,
        ship_via_cd VARCHAR,
        front_line_price_id VARCHAR,
        discount_id VARCHAR,
        deal_id VARCHAR,
        qnm_eligible_ind VARCHAR,
        marketing_group_buying_chain BIGINT,
        marketing_group_type VARCHAR,
        chain_period VARCHAR,
        price_category VARCHAR,
        invoice_discount_level VARCHAR,
        accumulate_by_chain_ind VARCHAR,
        front_line_price_per_case DECIMAL(18, 2),
        qnm_process_ind VARCHAR,
        parent_discount_id VARCHAR,
        item_accumulation_group_cd VARCHAR,
        deal_level_id VARCHAR,
        recovery_program_id BIGINT,
        recovery_group_id BIGINT,
        order_master_reference VARCHAR,
        sales_deal_id DECIMAL(18, 4),
        discount_per_unit VARCHAR,
        special_instructions_1 VARCHAR,
        special_instructions_2 VARCHAR,
        state_excise_tax_exemption_cd DECIMAL(18, 4),
        other_tax_cost_amt BIGINT,
        actual_ship_dt VARCHAR,
        water_invoice_ind VARCHAR,
        credit_status_approved_by_user_id VARCHAR,
        entered_by_user_id VARCHAR,
        billing_batch_id VARCHAR,
        combo_id BIGINT,
        core_combo_id BIGINT,
        adj_order_bottle_qty BIGINT,
        adj_order_case_qty BIGINT,
        adj_order_qty_dec_equ DECIMAL(15, 3),
        orig_order_qty_dec_equ DECIMAL(15, 3),
        discount_start_dt DATE,
        discount_end_dt DATE
  )
);

-- ============================================================================
-- SEED DATA: F_SALES_ALL
-- ============================================================================

SELECT
  sales_sk,
  posting_prd_sk,
  posting_dt_sk,
  item_sk,
  customer_sk,
  warehouse_sk,
  current_salesperson_sk,
  salesperson_sk,
  invoice_dt_sk,
  invoice_no,
  sequence_no,
  ref_inv_no,
  qty_dec_equ,
  ext_net,
  ext_cost,
  ext_dsct,
  ext_participation,
  ext_depl_allow,
  cases,
  bottles,
  combo_no,
  purcahse_order_no,
  dsct_qualifier,
  orig_case_qty,
  dsct_per_case,
  unit_breakage_amt,
  recovery_amt,
  ext_guaranteed_adj,
  reference_dt,
  orig_bottle_qty,
  converted_cases,
  unit_price,
  master_bill,
  orig_inv_line_item_no,
  orig_inv_pst_per,
  orig_inv_warehouse,
  ship_dt,
  state_tax,
  sws_cqd_amt,
  cqd_amt,
  chksum,
  modified_user,
  load_dt,
  modified_dt,
  src_desc,
  site_sk,
  route_no,
  stop_no,
  driver_no,
  whs_ship_loc,
  depot_no,
  site,
  warehouse_no,
  customer_no,
  item_no,
  tpz_combo,
  salesman_no,
  source_system,
  document_type,
  reason_cd,
  combo_option,
  discount_origin,
  adjustment_cd,
  dsct_category,
  entry_origin,
  day_bill_cd,
  void_cd,
  manifest_flg,
  reg_nght_shp_flg,
  ship_line_type,
  inv_subtype_cd,
  delivery_pickup_flg,
  billing_type_cd,
  slstax_chrgbk_flg,
  posting_prd,
  item_hist_sk,
  customer_hist_sk,
  warehouse_hist_sk,
  salesperson_hist_sk,
  current_salesperson_hist_sk,
  profit_center_sk,
  profit_center_cd,
  order_no,
  order_line_no,
  invoice_sales_unit_cd,
  state_tax_exempt_amt,
  cost_goods_sold_amt,
  da_amt,
  nda_amt,
  tax_chargeback_amt,
  total_breakage_amt,
  call_in_sales_rep_no,
  ship_via_cd,
  front_line_price_id,
  discount_id,
  deal_id,
  qnm_eligible_ind,
  marketing_group_buying_chain,
  marketing_group_type,
  chain_period,
  price_category,
  invoice_discount_level,
  accumulate_by_chain_ind,
  front_line_price_per_case,
  qnm_process_ind,
  parent_discount_id,
  item_accumulation_group_cd,
  deal_level_id,
  recovery_program_id,
  recovery_group_id,
  order_master_reference,
  sales_deal_id,
  discount_per_unit,
  special_instructions_1,
  special_instructions_2,
  state_excise_tax_exemption_cd,
  other_tax_cost_amt,
  actual_ship_dt,
  water_invoice_ind,
  credit_status_approved_by_user_id,
  entered_by_user_id,
  billing_batch_id,
  combo_id,
  core_combo_id,
  adj_order_bottle_qty,
  adj_order_case_qty,
  adj_order_qty_dec_equ,
  orig_order_qty_dec_equ,
  discount_start_dt,
  discount_end_dt
FROM SEED();
