MODEL (
  name web_analytics_seeds.HIT_DATA,
  kind SEED (
    path '../../seeds/hit_data_with_headers.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Adobe Analytics clickstream raw hit data seed',
  tags ('seed', 'reference_data', 'lookup'),
  terms ('hit_data'),
  columns (
        accept_language VARCHAR,
        adclassificationcreative VARCHAR,
        adload VARCHAR,
        aemassetid VARCHAR,
        aemassetsource VARCHAR,
        aemclickedassetid VARCHAR,
        browser BIGINT,
        browser_height VARCHAR,
        browser_width VARCHAR,
        c_color VARCHAR,
        campaign VARCHAR,
        carrier VARCHAR,
        ch_hdr VARCHAR,
        ch_js VARCHAR,
        channel VARCHAR,
        click_action VARCHAR,
        click_action_type VARCHAR,
        click_context VARCHAR,
        click_context_type VARCHAR,
        click_sourceid VARCHAR,
        click_tag VARCHAR,
        clickmaplink VARCHAR,
        clickmaplinkbyregion VARCHAR,
        clickmappage VARCHAR,
        clickmapregion VARCHAR,
        code_ver VARCHAR,
        color BIGINT,
        connection_type BIGINT,
        cookies VARCHAR,
        country BIGINT,
        ct_connect_type VARCHAR,
        curr_factor VARCHAR,
        curr_rate VARCHAR,
        currency VARCHAR,
        cust_hit_time_gmt BIGINT,
        cust_visid VARCHAR,
        daily_visitor VARCHAR,
        dataprivacyconsentoptin VARCHAR,
        dataprivacyconsentoptout VARCHAR,
        date_time VARCHAR,
        domain VARCHAR,
        duplicate_events VARCHAR,
        duplicate_purchase VARCHAR,
        duplicated_from VARCHAR,
        ef_id VARCHAR,
        evar1 VARCHAR,
        evar2 VARCHAR,
        evar3 VARCHAR,
        evar4 VARCHAR,
        evar5 VARCHAR,
        evar6 VARCHAR,
        evar7 VARCHAR,
        evar8 VARCHAR,
        evar9 VARCHAR,
        evar10 VARCHAR,
        evar11 VARCHAR,
        evar12 VARCHAR,
        evar13 VARCHAR,
        evar14 VARCHAR,
        evar15 VARCHAR,
        evar16 VARCHAR,
        evar17 VARCHAR,
        evar18 VARCHAR,
        evar19 VARCHAR,
        evar20 VARCHAR,
        evar21 VARCHAR,
        evar22 VARCHAR,
        evar23 VARCHAR,
        evar24 VARCHAR,
        evar25 VARCHAR,
        evar26 VARCHAR,
        evar27 VARCHAR,
        evar28 VARCHAR,
        evar29 VARCHAR,
        evar30 VARCHAR,
        evar31 VARCHAR,
        evar32 VARCHAR,
        evar33 VARCHAR,
        evar34 VARCHAR,
        evar35 VARCHAR,
        evar36 VARCHAR,
        evar37 VARCHAR,
        evar38 VARCHAR,
        evar39 VARCHAR,
        evar40 VARCHAR,
        evar41 VARCHAR,
        evar42 VARCHAR,
        evar43 VARCHAR,
        evar44 VARCHAR,
        evar45 VARCHAR,
        evar46 VARCHAR,
        evar47 VARCHAR,
        evar48 VARCHAR,
        evar49 VARCHAR,
        evar50 VARCHAR,
        evar51 VARCHAR,
        evar52 VARCHAR,
        evar53 VARCHAR,
        evar54 VARCHAR,
        evar55 VARCHAR,
        evar56 VARCHAR,
        evar57 VARCHAR,
        evar58 VARCHAR,
        evar59 VARCHAR,
        evar60 VARCHAR,
        evar61 VARCHAR,
        evar62 VARCHAR,
        evar63 VARCHAR,
        evar64 VARCHAR,
        evar65 VARCHAR,
        evar66 VARCHAR,
        evar67 VARCHAR,
        evar68 VARCHAR,
        evar69 VARCHAR,
        evar70 VARCHAR,
        evar71 VARCHAR,
        evar72 VARCHAR,
        evar73 VARCHAR,
        evar74 VARCHAR,
        evar75 VARCHAR,
        evar76 VARCHAR,
        evar77 VARCHAR,
        evar78 VARCHAR,
        evar79 VARCHAR,
        evar80 VARCHAR,
        evar81 VARCHAR,
        evar82 VARCHAR,
        evar83 VARCHAR,
        evar84 VARCHAR,
        evar85 VARCHAR,
        evar86 VARCHAR,
        evar87 VARCHAR,
        evar88 VARCHAR,
        evar89 VARCHAR,
        evar90 VARCHAR,
        evar91 VARCHAR,
        evar92 VARCHAR,
        evar93 VARCHAR,
        evar94 VARCHAR,
        evar95 VARCHAR,
        evar96 VARCHAR,
        evar97 VARCHAR,
        evar98 VARCHAR,
        evar99 VARCHAR,
        evar100 VARCHAR,
        evar101 VARCHAR,
        evar102 VARCHAR,
        evar103 VARCHAR,
        evar104 VARCHAR,
        evar105 VARCHAR,
        evar106 VARCHAR,
        evar107 VARCHAR,
        evar108 VARCHAR,
        evar109 VARCHAR,
        evar110 VARCHAR,
        evar111 VARCHAR,
        evar112 VARCHAR,
        evar113 VARCHAR,
        evar114 VARCHAR,
        evar115 VARCHAR,
        evar116 VARCHAR,
        evar117 VARCHAR,
        evar118 VARCHAR,
        evar119 VARCHAR,
        evar120 VARCHAR,
        evar121 VARCHAR,
        evar122 VARCHAR,
        evar123 VARCHAR,
        evar124 VARCHAR,
        evar125 VARCHAR,
        evar126 VARCHAR,
        evar127 VARCHAR,
        evar128 VARCHAR,
        evar129 VARCHAR,
        evar130 VARCHAR,
        evar131 VARCHAR,
        evar132 VARCHAR,
        evar133 VARCHAR,
        evar134 VARCHAR,
        evar135 VARCHAR,
        evar136 VARCHAR,
        evar137 VARCHAR,
        evar138 VARCHAR,
        evar139 VARCHAR,
        evar140 VARCHAR,
        evar141 VARCHAR,
        evar142 VARCHAR,
        evar143 VARCHAR,
        evar144 VARCHAR,
        evar145 VARCHAR,
        evar146 VARCHAR,
        evar147 VARCHAR,
        evar148 VARCHAR,
        evar149 VARCHAR,
        evar150 VARCHAR,
        evar151 VARCHAR,
        evar152 VARCHAR,
        evar153 VARCHAR,
        evar154 VARCHAR,
        evar155 VARCHAR,
        evar156 VARCHAR,
        evar157 VARCHAR,
        evar158 VARCHAR,
        evar159 VARCHAR,
        evar160 VARCHAR,
        evar161 VARCHAR,
        evar162 VARCHAR,
        evar163 VARCHAR,
        evar164 VARCHAR,
        evar165 VARCHAR,
        evar166 VARCHAR,
        evar167 VARCHAR,
        evar168 VARCHAR,
        evar169 VARCHAR,
        evar170 VARCHAR,
        evar171 VARCHAR,
        evar172 VARCHAR,
        evar173 VARCHAR,
        evar174 VARCHAR,
        evar175 VARCHAR,
        evar176 VARCHAR,
        evar177 VARCHAR,
        evar178 VARCHAR,
        evar179 VARCHAR,
        evar180 VARCHAR,
        evar181 VARCHAR,
        evar182 VARCHAR,
        evar183 VARCHAR,
        evar184 VARCHAR,
        evar185 VARCHAR,
        evar186 VARCHAR,
        evar187 VARCHAR,
        evar188 VARCHAR,
        evar189 VARCHAR,
        evar190 VARCHAR,
        evar191 VARCHAR,
        evar192 VARCHAR,
        evar193 VARCHAR,
        evar194 VARCHAR,
        evar195 VARCHAR,
        evar196 VARCHAR,
        evar197 VARCHAR,
        evar198 VARCHAR,
        evar199 VARCHAR,
        evar200 VARCHAR,
        evar201 VARCHAR,
        evar202 VARCHAR,
        evar203 VARCHAR,
        evar204 VARCHAR,
        evar205 VARCHAR,
        evar206 VARCHAR,
        evar207 VARCHAR,
        evar208 VARCHAR,
        evar209 VARCHAR,
        evar210 VARCHAR,
        evar211 VARCHAR,
        evar212 VARCHAR,
        evar213 VARCHAR,
        evar214 VARCHAR,
        evar215 VARCHAR,
        evar216 VARCHAR,
        evar217 VARCHAR,
        evar218 VARCHAR,
        evar219 VARCHAR,
        evar220 VARCHAR,
        evar221 VARCHAR,
        evar222 VARCHAR,
        evar223 VARCHAR,
        evar224 VARCHAR,
        evar225 VARCHAR,
        evar226 VARCHAR,
        evar227 VARCHAR,
        evar228 VARCHAR,
        evar229 VARCHAR,
        evar230 VARCHAR,
        evar231 VARCHAR,
        evar232 VARCHAR,
        evar233 VARCHAR,
        evar234 VARCHAR,
        evar235 VARCHAR,
        evar236 VARCHAR,
        evar237 VARCHAR,
        evar238 VARCHAR,
        evar239 VARCHAR,
        evar240 VARCHAR,
        evar241 VARCHAR,
        evar242 VARCHAR,
        evar243 VARCHAR,
        evar244 VARCHAR,
        evar245 VARCHAR,
        evar246 VARCHAR,
        evar247 VARCHAR,
        evar248 VARCHAR,
        evar249 VARCHAR,
        evar250 VARCHAR,
        event_list VARCHAR,
        exclude_hit VARCHAR,
        first_hit_page_url VARCHAR,
        first_hit_pagename VARCHAR,
        first_hit_ref_domain VARCHAR,
        first_hit_ref_type VARCHAR,
        first_hit_referrer VARCHAR,
        first_hit_time_gmt BIGINT,
        geo_city VARCHAR,
        geo_country VARCHAR,
        geo_dma VARCHAR,
        geo_region VARCHAR,
        geo_zip VARCHAR,
        hier1 VARCHAR,
        hier2 VARCHAR,
        hier3 VARCHAR,
        hier4 VARCHAR,
        hier5 VARCHAR,
        hit_source BIGINT,
        hit_time_gmt BIGINT,
        hitid_high BIGINT,
        hitid_low BIGINT,
        homepage VARCHAR,
        hourly_visitor VARCHAR,
        ip VARCHAR,
        ip2 VARCHAR,
        ipv6 VARCHAR,
        j_jscript VARCHAR,
        java_enabled VARCHAR,
        javascript BIGINT,
        language BIGINT,
        last_hit_time_gmt VARCHAR,
        last_purchase_num VARCHAR,
        last_purchase_time_gmt VARCHAR,
        latlon1 VARCHAR,
        latlon23 VARCHAR,
        latlon45 VARCHAR,
        mc_audiences VARCHAR,
        mcvisid VARCHAR,
        mobile_id VARCHAR,
        mobileacquisitionclicks VARCHAR,
        mobileaction VARCHAR,
        mobileactioninapptime VARCHAR,
        mobileactiontotaltime VARCHAR,
        mobileappid VARCHAR,
        mobileappperformanceaffectedusers VARCHAR,
        mobileappperformanceappid VARCHAR,
        mobileappperformanceappid_app_perf_app_name VARCHAR,
        mobileappperformanceappid_app_perf_platform VARCHAR,
        mobileappperformancecrashes VARCHAR,
        mobileappperformancecrashid VARCHAR,
        mobileappperformancecrashid_app_perf_crash_name VARCHAR,
        mobileappperformanceloads VARCHAR,
        mobileappstoreavgrating VARCHAR,
        mobileappstoredownloads VARCHAR,
        mobileappstoreinapprevenue VARCHAR,
        mobileappstoreinapproyalties VARCHAR,
        mobileappstoreobjectid VARCHAR,
        mobileappstoreobjectid_app_store_user VARCHAR,
        mobileappstoreobjectid_application_name VARCHAR,
        mobileappstoreobjectid_application_version VARCHAR,
        mobileappstoreobjectid_appstore_name VARCHAR,
        mobileappstoreobjectid_category_name VARCHAR,
        mobileappstoreobjectid_country_name VARCHAR,
        mobileappstoreobjectid_device_manufacturer VARCHAR,
        mobileappstoreobjectid_device_name VARCHAR,
        mobileappstoreobjectid_in_app_name VARCHAR,
        mobileappstoreobjectid_platform_name_version VARCHAR,
        mobileappstoreobjectid_rank_category_type VARCHAR,
        mobileappstoreobjectid_region_name VARCHAR,
        mobileappstoreobjectid_review_comment VARCHAR,
        mobileappstoreobjectid_review_title VARCHAR,
        mobileappstoreoneoffrevenue VARCHAR,
        mobileappstoreoneoffroyalties VARCHAR,
        mobileappstorepurchases VARCHAR,
        mobileappstorerank VARCHAR,
        mobileappstorerankdivisor VARCHAR,
        mobileappstorerating VARCHAR,
        mobileappstoreratingdivisor VARCHAR,
        mobileavgprevsessionlength VARCHAR,
        mobilebeaconmajor VARCHAR,
        mobilebeaconminor VARCHAR,
        mobilebeaconproximity VARCHAR,
        mobilebeaconuuid VARCHAR,
        mobilecampaigncontent VARCHAR,
        mobilecampaignmedium VARCHAR,
        mobilecampaignname VARCHAR,
        mobilecampaignsource VARCHAR,
        mobilecampaignterm VARCHAR,
        mobilecrashes VARCHAR,
        mobilecrashrate VARCHAR,
        mobiledailyengagedusers VARCHAR,
        mobiledayofweek VARCHAR,
        mobiledayssincefirstuse VARCHAR,
        mobiledayssincelastupgrade VARCHAR,
        mobiledayssincelastuse VARCHAR,
        mobiledeeplinkid VARCHAR,
        mobiledeeplinkid_name VARCHAR,
        mobiledevice VARCHAR,
        mobilehourofday VARCHAR,
        mobileinstalldate VARCHAR,
        mobileinstalls VARCHAR,
        mobilelaunches VARCHAR,
        mobilelaunchessincelastupgrade VARCHAR,
        mobilelaunchnumber VARCHAR,
        mobileltv VARCHAR,
        mobileltvtotal VARCHAR,
        mobilemessagebuttonname VARCHAR,
        mobilemessageclicks VARCHAR,
        mobilemessageid VARCHAR,
        mobilemessageid_dest VARCHAR,
        mobilemessageid_name VARCHAR,
        mobilemessageid_type VARCHAR,
        mobilemessageimpressions VARCHAR,
        mobilemessageonline VARCHAR,
        mobilemessagepushoptin VARCHAR,
        mobilemessagepushpayloadid VARCHAR,
        mobilemessagepushpayloadid_name VARCHAR,
        mobilemessageviews VARCHAR,
        mobilemonthlyengagedusers VARCHAR,
        mobileosenvironment VARCHAR,
        mobileosversion VARCHAR,
        mobileplaceaccuracy VARCHAR,
        mobileplacecategory VARCHAR,
        mobileplacedwelltime VARCHAR,
        mobileplaceentry VARCHAR,
        mobileplaceexit VARCHAR,
        mobileplaceid VARCHAR,
        mobileprevsessionlength VARCHAR,
        mobilepushoptin VARCHAR,
        mobilepushpayloadid VARCHAR,
        mobilerelaunchcampaigncontent VARCHAR,
        mobilerelaunchcampaignmedium VARCHAR,
        mobilerelaunchcampaignsource VARCHAR,
        mobilerelaunchcampaignterm VARCHAR,
        mobilerelaunchcampaigntrackingcode VARCHAR,
        mobilerelaunchcampaigntrackingcode_name VARCHAR,
        mobileresolution VARCHAR,
        mobileupgrades VARCHAR,
        monthly_visitor VARCHAR,
        mvvar1 VARCHAR,
        mvvar1_instances VARCHAR,
        mvvar2 VARCHAR,
        mvvar2_instances VARCHAR,
        mvvar3 VARCHAR,
        mvvar3_instances VARCHAR,
        namespace VARCHAR,
        new_visit BIGINT,
        os BIGINT,
        p_plugins VARCHAR,
        page_event BIGINT,
        page_event_var1 VARCHAR,
        page_event_var2 VARCHAR,
        page_event_var3 VARCHAR,
        page_type VARCHAR,
        page_url VARCHAR,
        pagename VARCHAR,
        paid_search VARCHAR,
        partner_plugins VARCHAR,
        persistent_cookie VARCHAR,
        plugins BIGINT,
        pointofinterest VARCHAR,
        pointofinterestdistance VARCHAR,
        post_adclassificationcreative VARCHAR,
        post_adload VARCHAR,
        post_browser_height VARCHAR,
        post_browser_width VARCHAR,
        post_campaign VARCHAR,
        post_channel VARCHAR,
        post_clickmaplink VARCHAR,
        post_clickmaplinkbyregion VARCHAR,
        post_clickmappage VARCHAR,
        post_clickmapregion VARCHAR,
        post_cookies VARCHAR,
        post_currency VARCHAR,
        post_cust_hit_time_gmt BIGINT,
        post_cust_visid VARCHAR,
        post_ef_id VARCHAR,
        post_evar1 VARCHAR,
        post_evar2 VARCHAR,
        post_evar3 VARCHAR,
        post_evar4 VARCHAR,
        post_evar5 VARCHAR,
        post_evar6 VARCHAR,
        post_evar7 VARCHAR,
        post_evar8 VARCHAR,
        post_evar9 VARCHAR,
        post_evar10 VARCHAR,
        post_evar11 VARCHAR,
        post_evar12 VARCHAR,
        post_evar13 VARCHAR,
        post_evar14 VARCHAR,
        post_evar15 VARCHAR,
        post_evar16 VARCHAR,
        post_evar17 VARCHAR,
        post_evar18 VARCHAR,
        post_evar19 VARCHAR,
        post_evar20 VARCHAR,
        post_evar21 VARCHAR,
        post_evar22 VARCHAR,
        post_evar23 VARCHAR,
        post_evar24 VARCHAR,
        post_evar25 VARCHAR,
        post_evar26 VARCHAR,
        post_evar27 VARCHAR,
        post_evar28 VARCHAR,
        post_evar29 VARCHAR,
        post_evar30 VARCHAR,
        post_evar31 VARCHAR,
        post_evar32 VARCHAR,
        post_evar33 VARCHAR,
        post_evar34 VARCHAR,
        post_evar35 VARCHAR,
        post_evar36 VARCHAR,
        post_evar37 VARCHAR,
        post_evar38 VARCHAR,
        post_evar39 VARCHAR,
        post_evar40 VARCHAR,
        post_evar41 VARCHAR,
        post_evar42 VARCHAR,
        post_evar43 VARCHAR,
        post_evar44 VARCHAR,
        post_evar45 VARCHAR,
        post_evar46 VARCHAR,
        post_evar47 VARCHAR,
        post_evar48 VARCHAR,
        post_evar49 VARCHAR,
        post_evar50 VARCHAR,
        post_evar51 VARCHAR,
        post_evar52 VARCHAR,
        post_evar53 VARCHAR,
        post_evar54 VARCHAR,
        post_evar55 VARCHAR,
        post_evar56 VARCHAR,
        post_evar57 VARCHAR,
        post_evar58 VARCHAR,
        post_evar59 VARCHAR,
        post_evar60 VARCHAR,
        post_evar61 VARCHAR,
        post_evar62 VARCHAR,
        post_evar63 VARCHAR,
        post_evar64 VARCHAR,
        post_evar65 VARCHAR,
        post_evar66 VARCHAR,
        post_evar67 VARCHAR,
        post_evar68 VARCHAR,
        post_evar69 VARCHAR,
        post_evar70 VARCHAR,
        post_evar71 VARCHAR,
        post_evar72 VARCHAR,
        post_evar73 VARCHAR,
        post_evar74 VARCHAR,
        post_evar75 VARCHAR,
        post_evar76 VARCHAR,
        post_evar77 VARCHAR,
        post_evar78 VARCHAR,
        post_evar79 VARCHAR,
        post_evar80 VARCHAR,
        post_evar81 VARCHAR,
        post_evar82 VARCHAR,
        post_evar83 VARCHAR,
        post_evar84 VARCHAR,
        post_evar85 VARCHAR,
        post_evar86 VARCHAR,
        post_evar87 VARCHAR,
        post_evar88 VARCHAR,
        post_evar89 VARCHAR,
        post_evar90 VARCHAR,
        post_evar91 VARCHAR,
        post_evar92 VARCHAR,
        post_evar93 VARCHAR,
        post_evar94 VARCHAR,
        post_evar95 VARCHAR,
        post_evar96 VARCHAR,
        post_evar97 VARCHAR,
        post_evar98 VARCHAR,
        post_evar99 VARCHAR,
        post_evar100 VARCHAR,
        post_evar101 VARCHAR,
        post_evar102 VARCHAR,
        post_evar103 VARCHAR,
        post_evar104 VARCHAR,
        post_evar105 VARCHAR,
        post_evar106 VARCHAR,
        post_evar107 VARCHAR,
        post_evar108 VARCHAR,
        post_evar109 VARCHAR,
        post_evar110 VARCHAR,
        post_evar111 VARCHAR,
        post_evar112 VARCHAR,
        post_evar113 VARCHAR,
        post_evar114 VARCHAR,
        post_evar115 VARCHAR,
        post_evar116 VARCHAR,
        post_evar117 VARCHAR,
        post_evar118 VARCHAR,
        post_evar119 VARCHAR,
        post_evar120 VARCHAR,
        post_evar121 VARCHAR,
        post_evar122 VARCHAR,
        post_evar123 VARCHAR,
        post_evar124 VARCHAR,
        post_evar125 VARCHAR,
        post_evar126 VARCHAR,
        post_evar127 VARCHAR,
        post_evar128 VARCHAR,
        post_evar129 VARCHAR,
        post_evar130 VARCHAR,
        post_evar131 VARCHAR,
        post_evar132 VARCHAR,
        post_evar133 VARCHAR,
        post_evar134 VARCHAR,
        post_evar135 VARCHAR,
        post_evar136 VARCHAR,
        post_evar137 VARCHAR,
        post_evar138 VARCHAR,
        post_evar139 VARCHAR,
        post_evar140 VARCHAR,
        post_evar141 VARCHAR,
        post_evar142 VARCHAR,
        post_evar143 VARCHAR,
        post_evar144 VARCHAR,
        post_evar145 VARCHAR,
        post_evar146 VARCHAR,
        post_evar147 VARCHAR,
        post_evar148 VARCHAR,
        post_evar149 VARCHAR,
        post_evar150 VARCHAR,
        post_evar151 VARCHAR,
        post_evar152 VARCHAR,
        post_evar153 VARCHAR,
        post_evar154 VARCHAR,
        post_evar155 VARCHAR,
        post_evar156 VARCHAR,
        post_evar157 VARCHAR,
        post_evar158 VARCHAR,
        post_evar159 VARCHAR,
        post_evar160 VARCHAR,
        post_evar161 VARCHAR,
        post_evar162 VARCHAR,
        post_evar163 VARCHAR,
        post_evar164 VARCHAR,
        post_evar165 VARCHAR,
        post_evar166 VARCHAR,
        post_evar167 VARCHAR,
        post_evar168 VARCHAR,
        post_evar169 VARCHAR,
        post_evar170 VARCHAR,
        post_evar171 VARCHAR,
        post_evar172 VARCHAR,
        post_evar173 VARCHAR,
        post_evar174 VARCHAR,
        post_evar175 VARCHAR,
        post_evar176 VARCHAR,
        post_evar177 VARCHAR,
        post_evar178 VARCHAR,
        post_evar179 VARCHAR,
        post_evar180 VARCHAR,
        post_evar181 VARCHAR,
        post_evar182 VARCHAR,
        post_evar183 VARCHAR,
        post_evar184 VARCHAR,
        post_evar185 VARCHAR,
        post_evar186 VARCHAR,
        post_evar187 VARCHAR,
        post_evar188 VARCHAR,
        post_evar189 VARCHAR,
        post_evar190 VARCHAR,
        post_evar191 VARCHAR,
        post_evar192 VARCHAR,
        post_evar193 VARCHAR,
        post_evar194 VARCHAR,
        post_evar195 VARCHAR,
        post_evar196 VARCHAR,
        post_evar197 VARCHAR,
        post_evar198 VARCHAR,
        post_evar199 VARCHAR,
        post_evar200 VARCHAR,
        post_evar201 VARCHAR,
        post_evar202 VARCHAR,
        post_evar203 VARCHAR,
        post_evar204 VARCHAR,
        post_evar205 VARCHAR,
        post_evar206 VARCHAR,
        post_evar207 VARCHAR,
        post_evar208 VARCHAR,
        post_evar209 VARCHAR,
        post_evar210 VARCHAR,
        post_evar211 VARCHAR,
        post_evar212 VARCHAR,
        post_evar213 VARCHAR,
        post_evar214 VARCHAR,
        post_evar215 VARCHAR,
        post_evar216 VARCHAR,
        post_evar217 VARCHAR,
        post_evar218 VARCHAR,
        post_evar219 VARCHAR,
        post_evar220 VARCHAR,
        post_evar221 VARCHAR,
        post_evar222 VARCHAR,
        post_evar223 VARCHAR,
        post_evar224 VARCHAR,
        post_evar225 VARCHAR,
        post_evar226 VARCHAR,
        post_evar227 VARCHAR,
        post_evar228 VARCHAR,
        post_evar229 VARCHAR,
        post_evar230 VARCHAR,
        post_evar231 VARCHAR,
        post_evar232 VARCHAR,
        post_evar233 VARCHAR,
        post_evar234 VARCHAR,
        post_evar235 VARCHAR,
        post_evar236 VARCHAR,
        post_evar237 VARCHAR,
        post_evar238 VARCHAR,
        post_evar239 VARCHAR,
        post_evar240 VARCHAR,
        post_evar241 VARCHAR,
        post_evar242 VARCHAR,
        post_evar243 VARCHAR,
        post_evar244 VARCHAR,
        post_evar245 VARCHAR,
        post_evar246 VARCHAR,
        post_evar247 VARCHAR,
        post_evar248 VARCHAR,
        post_evar249 VARCHAR,
        post_evar250 VARCHAR,
        post_event_list VARCHAR,
        post_hier1 VARCHAR,
        post_hier2 VARCHAR,
        post_hier3 VARCHAR,
        post_hier4 VARCHAR,
        post_hier5 VARCHAR,
        post_java_enabled VARCHAR,
        post_keywords VARCHAR,
        post_mc_audiences VARCHAR,
        post_mobileaction VARCHAR,
        post_mobileappid VARCHAR,
        post_mobilecampaigncontent VARCHAR,
        post_mobilecampaignmedium VARCHAR,
        post_mobilecampaignname VARCHAR,
        post_mobilecampaignsource VARCHAR,
        post_mobilecampaignterm VARCHAR,
        post_mobiledayofweek VARCHAR,
        post_mobiledayssincefirstuse VARCHAR,
        post_mobiledayssincelastuse VARCHAR,
        post_mobiledevice VARCHAR,
        post_mobilehourofday VARCHAR,
        post_mobileinstalldate VARCHAR,
        post_mobilelaunchnumber VARCHAR,
        post_mobileltv VARCHAR,
        post_mobilemessagebuttonname VARCHAR,
        post_mobilemessageclicks VARCHAR,
        post_mobilemessageid VARCHAR,
        post_mobilemessageid_dest VARCHAR,
        post_mobilemessageid_name VARCHAR,
        post_mobilemessageid_type VARCHAR,
        post_mobilemessageimpressions VARCHAR,
        post_mobilemessageonline VARCHAR,
        post_mobilemessagepushoptin VARCHAR,
        post_mobilemessagepushpayloadid VARCHAR,
        post_mobilemessagepushpayloadid_name VARCHAR,
        post_mobilemessageviews VARCHAR,
        post_mobileosversion VARCHAR,
        post_mobilepushoptin VARCHAR,
        post_mobilepushpayloadid VARCHAR,
        post_mobileresolution VARCHAR,
        post_mvvar1 VARCHAR,
        post_mvvar1_instances VARCHAR,
        post_mvvar2 VARCHAR,
        post_mvvar2_instances VARCHAR,
        post_mvvar3 VARCHAR,
        post_mvvar3_instances VARCHAR,
        post_page_event BIGINT,
        post_page_event_var1 VARCHAR,
        post_page_event_var2 VARCHAR,
        post_page_event_var3 VARCHAR,
        post_page_type VARCHAR,
        post_page_url VARCHAR,
        post_pagename VARCHAR,
        post_pagename_no_url VARCHAR,
        post_partner_plugins VARCHAR,
        post_persistent_cookie VARCHAR,
        post_pointofinterest VARCHAR,
        post_pointofinterestdistance VARCHAR,
        post_product_list VARCHAR,
        post_prop1 VARCHAR,
        post_prop2 VARCHAR,
        post_prop3 VARCHAR,
        post_prop4 VARCHAR,
        post_prop5 VARCHAR,
        post_prop6 VARCHAR,
        post_prop7 VARCHAR,
        post_prop8 VARCHAR,
        post_prop9 VARCHAR,
        post_prop10 VARCHAR,
        post_prop11 VARCHAR,
        post_prop12 VARCHAR,
        post_prop13 VARCHAR,
        post_prop14 VARCHAR,
        post_prop15 VARCHAR,
        post_prop16 VARCHAR,
        post_prop17 VARCHAR,
        post_prop18 VARCHAR,
        post_prop19 VARCHAR,
        post_prop20 VARCHAR,
        post_prop21 VARCHAR,
        post_prop22 VARCHAR,
        post_prop23 VARCHAR,
        post_prop24 VARCHAR,
        post_prop25 VARCHAR,
        post_prop26 VARCHAR,
        post_prop27 VARCHAR,
        post_prop28 VARCHAR,
        post_prop29 VARCHAR,
        post_prop30 VARCHAR,
        post_prop31 VARCHAR,
        post_prop32 VARCHAR,
        post_prop33 VARCHAR,
        post_prop34 VARCHAR,
        post_prop35 VARCHAR,
        post_prop36 VARCHAR,
        post_prop37 VARCHAR,
        post_prop38 VARCHAR,
        post_prop39 VARCHAR,
        post_prop40 VARCHAR,
        post_prop41 VARCHAR,
        post_prop42 VARCHAR,
        post_prop43 VARCHAR,
        post_prop44 VARCHAR,
        post_prop45 VARCHAR,
        post_prop46 VARCHAR,
        post_prop47 VARCHAR,
        post_prop48 VARCHAR,
        post_prop49 VARCHAR,
        post_prop50 VARCHAR,
        post_prop51 VARCHAR,
        post_prop52 VARCHAR,
        post_prop53 VARCHAR,
        post_prop54 VARCHAR,
        post_prop55 VARCHAR,
        post_prop56 VARCHAR,
        post_prop57 VARCHAR,
        post_prop58 VARCHAR,
        post_prop59 VARCHAR,
        post_prop60 VARCHAR,
        post_prop61 VARCHAR,
        post_prop62 VARCHAR,
        post_prop63 VARCHAR,
        post_prop64 VARCHAR,
        post_prop65 VARCHAR,
        post_prop66 VARCHAR,
        post_prop67 VARCHAR,
        post_prop68 VARCHAR,
        post_prop69 VARCHAR,
        post_prop70 VARCHAR,
        post_prop71 VARCHAR,
        post_prop72 VARCHAR,
        post_prop73 VARCHAR,
        post_prop74 VARCHAR,
        post_prop75 VARCHAR,
        post_purchaseid VARCHAR,
        post_referrer VARCHAR,
        post_s_kwcid VARCHAR,
        post_search_engine VARCHAR,
        post_socialaccountandappids VARCHAR,
        post_socialassettrackingcode VARCHAR,
        post_socialauthor VARCHAR,
        post_socialaveragesentiment VARCHAR,
        post_socialaveragesentiment_deprecated VARCHAR,
        post_socialcontentprovider VARCHAR,
        post_socialfbstories VARCHAR,
        post_socialfbstorytellers VARCHAR,
        post_socialinteractioncount VARCHAR,
        post_socialinteractiontype VARCHAR,
        post_sociallanguage VARCHAR,
        post_sociallatlong VARCHAR,
        post_sociallikeadds VARCHAR,
        post_sociallink VARCHAR,
        post_sociallink_deprecated VARCHAR,
        post_socialmentions VARCHAR,
        post_socialowneddefinitioninsighttype VARCHAR,
        post_socialowneddefinitioninsightvalue VARCHAR,
        post_socialowneddefinitionmetric VARCHAR,
        post_socialowneddefinitionpropertyvspost VARCHAR,
        post_socialownedpostids VARCHAR,
        post_socialownedpropertyid VARCHAR,
        post_socialownedpropertyname VARCHAR,
        post_socialownedpropertypropertyvsapp VARCHAR,
        post_socialpageviews VARCHAR,
        post_socialpostviews VARCHAR,
        post_socialproperty VARCHAR,
        post_socialproperty_deprecated VARCHAR,
        post_socialpubcomments VARCHAR,
        post_socialpubposts VARCHAR,
        post_socialpubrecommends VARCHAR,
        post_socialpubsubscribers VARCHAR,
        post_socialterm VARCHAR,
        post_socialtermslist VARCHAR,
        post_socialtermslist_deprecated VARCHAR,
        post_socialtotalsentiment VARCHAR,
        post_state VARCHAR,
        post_survey VARCHAR,
        post_t_time_info VARCHAR,
        post_tnt VARCHAR,
        post_tnt_action VARCHAR,
        post_transactionid VARCHAR,
        post_user_server VARCHAR,
        post_video VARCHAR,
        post_videoad VARCHAR,
        post_videoadinpod VARCHAR,
        post_videoadlength VARCHAR,
        post_videoadname VARCHAR,
        post_videoadplayername VARCHAR,
        post_videoadpod VARCHAR,
        post_videoadvertiser VARCHAR,
        post_videoauthorized VARCHAR,
        post_videocampaign VARCHAR,
        post_videochannel VARCHAR,
        post_videochapter VARCHAR,
        post_videocontenttype VARCHAR,
        post_videodaypart VARCHAR,
        post_videoepisode VARCHAR,
        post_videofeedtype VARCHAR,
        post_videogenre VARCHAR,
        post_videolength VARCHAR,
        post_videomvpd VARCHAR,
        post_videoname VARCHAR,
        post_videonetwork VARCHAR,
        post_videopath VARCHAR,
        post_videoplayername VARCHAR,
        post_videoqoebitrateaverageevar VARCHAR,
        post_videoqoebitratechangecountevar VARCHAR,
        post_videoqoebuffercountevar VARCHAR,
        post_videoqoebuffertimeevar VARCHAR,
        post_videoqoedroppedframecountevar VARCHAR,
        post_videoqoeerrorcountevar VARCHAR,
        post_videoqoeplayersdkerrors VARCHAR,
        post_videoqoetimetostartevar VARCHAR,
        post_videoseason VARCHAR,
        post_videosegment VARCHAR,
        post_videoshow VARCHAR,
        post_videoshowtype VARCHAR,
        post_visid_high BIGINT,
        post_visid_low BIGINT,
        post_visid_type VARCHAR,
        post_zip VARCHAR,
        prev_page VARCHAR,
        product_list VARCHAR,
        product_merchandising VARCHAR,
        prop1 VARCHAR,
        prop2 VARCHAR,
        prop3 VARCHAR,
        prop4 VARCHAR,
        prop5 VARCHAR,
        prop6 VARCHAR,
        prop7 VARCHAR,
        prop8 VARCHAR,
        prop9 VARCHAR,
        prop10 VARCHAR,
        prop11 VARCHAR,
        prop12 VARCHAR,
        prop13 VARCHAR,
        prop14 VARCHAR,
        prop15 VARCHAR,
        prop16 VARCHAR,
        prop17 VARCHAR,
        prop18 VARCHAR,
        prop19 VARCHAR,
        prop20 VARCHAR,
        prop21 VARCHAR,
        prop22 VARCHAR,
        prop23 VARCHAR,
        prop24 VARCHAR,
        prop25 VARCHAR,
        prop26 VARCHAR,
        prop27 VARCHAR,
        prop28 VARCHAR,
        prop29 VARCHAR,
        prop30 VARCHAR,
        prop31 VARCHAR,
        prop32 VARCHAR,
        prop33 VARCHAR,
        prop34 VARCHAR,
        prop35 VARCHAR,
        prop36 VARCHAR,
        prop37 VARCHAR,
        prop38 VARCHAR,
        prop39 VARCHAR,
        prop40 VARCHAR,
        prop41 VARCHAR,
        prop42 VARCHAR,
        prop43 VARCHAR,
        prop44 VARCHAR,
        prop45 VARCHAR,
        prop46 VARCHAR,
        prop47 VARCHAR,
        prop48 VARCHAR,
        prop49 VARCHAR,
        prop50 VARCHAR,
        prop51 VARCHAR,
        prop52 VARCHAR,
        prop53 VARCHAR,
        prop54 VARCHAR,
        prop55 VARCHAR,
        prop56 VARCHAR,
        prop57 VARCHAR,
        prop58 VARCHAR,
        prop59 VARCHAR,
        prop60 VARCHAR,
        prop61 VARCHAR,
        prop62 VARCHAR,
        prop63 VARCHAR,
        prop64 VARCHAR,
        prop65 VARCHAR,
        prop66 VARCHAR,
        prop67 VARCHAR,
        prop68 VARCHAR,
        prop69 VARCHAR,
        prop70 VARCHAR,
        prop71 VARCHAR,
        prop72 VARCHAR,
        prop73 VARCHAR,
        prop74 VARCHAR,
        prop75 VARCHAR,
        purchaseid VARCHAR,
        quarterly_visitor VARCHAR,
        ref_domain VARCHAR,
        ref_type BIGINT,
        referrer VARCHAR,
        resolution BIGINT,
        s_kwcid VARCHAR,
        s_resolution VARCHAR,
        sampled_hit VARCHAR,
        search_engine BIGINT,
        search_page_num VARCHAR,
        secondary_hit VARCHAR,
        service VARCHAR,
        socialaccountandappids VARCHAR,
        socialassettrackingcode VARCHAR,
        socialauthor VARCHAR,
        socialaveragesentiment VARCHAR,
        socialaveragesentiment_deprecated VARCHAR,
        socialcontentprovider VARCHAR,
        socialfbstories VARCHAR,
        socialfbstorytellers VARCHAR,
        socialinteractioncount VARCHAR,
        socialinteractiontype VARCHAR,
        sociallanguage VARCHAR,
        sociallatlong VARCHAR,
        sociallikeadds VARCHAR,
        sociallink VARCHAR,
        sociallink_deprecated VARCHAR,
        socialmentions VARCHAR,
        socialowneddefinitioninsighttype VARCHAR,
        socialowneddefinitioninsightvalue VARCHAR,
        socialowneddefinitionmetric VARCHAR,
        socialowneddefinitionpropertyvspost VARCHAR,
        socialownedpostids VARCHAR,
        socialownedpropertyid VARCHAR,
        socialownedpropertyname VARCHAR,
        socialownedpropertypropertyvsapp VARCHAR,
        socialpageviews VARCHAR,
        socialpostviews VARCHAR,
        socialproperty VARCHAR,
        socialproperty_deprecated VARCHAR,
        socialpubcomments VARCHAR,
        socialpubposts VARCHAR,
        socialpubrecommends VARCHAR,
        socialpubsubscribers VARCHAR,
        socialterm VARCHAR,
        socialtermslist VARCHAR,
        socialtermslist_deprecated VARCHAR,
        socialtotalsentiment VARCHAR,
        sourceid VARCHAR,
        state VARCHAR,
        stats_server VARCHAR,
        survey_instances VARCHAR,
        t_time_info VARCHAR,
        tnt VARCHAR,
        tnt_action VARCHAR,
        tnt_instances VARCHAR,
        tnt_post_vista VARCHAR,
        transactionid VARCHAR,
        truncated_hit VARCHAR,
        ua_color VARCHAR,
        ua_os VARCHAR,
        ua_pixels VARCHAR,
        user_agent VARCHAR,
        user_hash VARCHAR,
        user_server VARCHAR,
        userid VARCHAR,
        username VARCHAR,
        va_closer_detail VARCHAR,
        va_closer_id VARCHAR,
        va_finder_detail VARCHAR,
        va_finder_id VARCHAR,
        va_instance_event VARCHAR,
        va_new_engagement VARCHAR,
        video VARCHAR,
        videoad VARCHAR,
        videoadinpod VARCHAR,
        videoadlength VARCHAR,
        videoadname VARCHAR,
        videoadplayername VARCHAR,
        videoadpod VARCHAR,
        videoadvertiser VARCHAR,
        videoaudioalbum VARCHAR,
        videoaudioartist VARCHAR,
        videoaudioauthor VARCHAR,
        videoaudiolabel VARCHAR,
        videoaudiopublisher VARCHAR,
        videoaudiostation VARCHAR,
        videoauthorized VARCHAR,
        videoaverageminuteaudience VARCHAR,
        videocampaign VARCHAR,
        videochannel VARCHAR,
        videochapter VARCHAR,
        videochaptercomplete VARCHAR,
        videochapterstart VARCHAR,
        videochaptertime VARCHAR,
        videocontenttype VARCHAR,
        videodaypart VARCHAR,
        videoepisode VARCHAR,
        videofeedtype VARCHAR,
        videogenre VARCHAR,
        videolength VARCHAR,
        videomvpd VARCHAR,
        videoname VARCHAR,
        videonetwork VARCHAR,
        videopath VARCHAR,
        videopause VARCHAR,
        videopausecount VARCHAR,
        videopausetime VARCHAR,
        videoplay VARCHAR,
        videoplayername VARCHAR,
        videoprogress10 VARCHAR,
        videoprogress25 VARCHAR,
        videoprogress50 VARCHAR,
        videoprogress75 VARCHAR,
        videoprogress96 VARCHAR,
        videoqoebitrateaverage VARCHAR,
        videoqoebitrateaverageevar VARCHAR,
        videoqoebitratechange VARCHAR,
        videoqoebitratechangecountevar VARCHAR,
        videoqoebuffer VARCHAR,
        videoqoebuffercountevar VARCHAR,
        videoqoebuffertimeevar VARCHAR,
        videoqoedropbeforestart VARCHAR,
        videoqoedroppedframecountevar VARCHAR,
        videoqoedroppedframes VARCHAR,
        videoqoeerror VARCHAR,
        videoqoeerrorcountevar VARCHAR,
        videoqoeextneralerrors VARCHAR,
        videoqoeplayersdkerrors VARCHAR,
        videoqoetimetostartevar VARCHAR,
        videoresume VARCHAR,
        videoseason VARCHAR,
        videosegment VARCHAR,
        videoshow VARCHAR,
        videoshowtype VARCHAR,
        videostreamtype VARCHAR,
        videototaltime VARCHAR,
        videouniquetimeplayed VARCHAR,
        visid_high BIGINT,
        visid_low BIGINT,
        visid_new VARCHAR,
        visid_timestamp VARCHAR,
        visid_type VARCHAR,
        visit_keywords VARCHAR,
        visit_num BIGINT,
        visit_page_num BIGINT,
        visit_ref_domain VARCHAR,
        visit_ref_type VARCHAR,
        visit_referrer VARCHAR,
        visit_search_engine VARCHAR,
        visit_start_page_url VARCHAR,
        visit_start_pagename VARCHAR,
        visit_start_time_gmt BIGINT,
        weekly_visitor VARCHAR,
        yearly_visitor VARCHAR,
        zip VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: HIT_DATA
-- ============================================================================

SELECT
  accept_language,
  adclassificationcreative,
  adload,
  aemassetid,
  aemassetsource,
  aemclickedassetid,
  browser,
  browser_height,
  browser_width,
  c_color,
  campaign,
  carrier,
  ch_hdr,
  ch_js,
  channel,
  click_action,
  click_action_type,
  click_context,
  click_context_type,
  click_sourceid,
  click_tag,
  clickmaplink,
  clickmaplinkbyregion,
  clickmappage,
  clickmapregion,
  code_ver,
  color,
  connection_type,
  cookies,
  country,
  ct_connect_type,
  curr_factor,
  curr_rate,
  currency,
  cust_hit_time_gmt,
  cust_visid,
  daily_visitor,
  dataprivacyconsentoptin,
  dataprivacyconsentoptout,
  date_time,
  domain,
  duplicate_events,
  duplicate_purchase,
  duplicated_from,
  ef_id,
  evar1,
  evar2,
  evar3,
  evar4,
  evar5,
  evar6,
  evar7,
  evar8,
  evar9,
  evar10,
  evar11,
  evar12,
  evar13,
  evar14,
  evar15,
  evar16,
  evar17,
  evar18,
  evar19,
  evar20,
  evar21,
  evar22,
  evar23,
  evar24,
  evar25,
  evar26,
  evar27,
  evar28,
  evar29,
  evar30,
  evar31,
  evar32,
  evar33,
  evar34,
  evar35,
  evar36,
  evar37,
  evar38,
  evar39,
  evar40,
  evar41,
  evar42,
  evar43,
  evar44,
  evar45,
  evar46,
  evar47,
  evar48,
  evar49,
  evar50,
  evar51,
  evar52,
  evar53,
  evar54,
  evar55,
  evar56,
  evar57,
  evar58,
  evar59,
  evar60,
  evar61,
  evar62,
  evar63,
  evar64,
  evar65,
  evar66,
  evar67,
  evar68,
  evar69,
  evar70,
  evar71,
  evar72,
  evar73,
  evar74,
  evar75,
  evar76,
  evar77,
  evar78,
  evar79,
  evar80,
  evar81,
  evar82,
  evar83,
  evar84,
  evar85,
  evar86,
  evar87,
  evar88,
  evar89,
  evar90,
  evar91,
  evar92,
  evar93,
  evar94,
  evar95,
  evar96,
  evar97,
  evar98,
  evar99,
  evar100,
  evar101,
  evar102,
  evar103,
  evar104,
  evar105,
  evar106,
  evar107,
  evar108,
  evar109,
  evar110,
  evar111,
  evar112,
  evar113,
  evar114,
  evar115,
  evar116,
  evar117,
  evar118,
  evar119,
  evar120,
  evar121,
  evar122,
  evar123,
  evar124,
  evar125,
  evar126,
  evar127,
  evar128,
  evar129,
  evar130,
  evar131,
  evar132,
  evar133,
  evar134,
  evar135,
  evar136,
  evar137,
  evar138,
  evar139,
  evar140,
  evar141,
  evar142,
  evar143,
  evar144,
  evar145,
  evar146,
  evar147,
  evar148,
  evar149,
  evar150,
  evar151,
  evar152,
  evar153,
  evar154,
  evar155,
  evar156,
  evar157,
  evar158,
  evar159,
  evar160,
  evar161,
  evar162,
  evar163,
  evar164,
  evar165,
  evar166,
  evar167,
  evar168,
  evar169,
  evar170,
  evar171,
  evar172,
  evar173,
  evar174,
  evar175,
  evar176,
  evar177,
  evar178,
  evar179,
  evar180,
  evar181,
  evar182,
  evar183,
  evar184,
  evar185,
  evar186,
  evar187,
  evar188,
  evar189,
  evar190,
  evar191,
  evar192,
  evar193,
  evar194,
  evar195,
  evar196,
  evar197,
  evar198,
  evar199,
  evar200,
  evar201,
  evar202,
  evar203,
  evar204,
  evar205,
  evar206,
  evar207,
  evar208,
  evar209,
  evar210,
  evar211,
  evar212,
  evar213,
  evar214,
  evar215,
  evar216,
  evar217,
  evar218,
  evar219,
  evar220,
  evar221,
  evar222,
  evar223,
  evar224,
  evar225,
  evar226,
  evar227,
  evar228,
  evar229,
  evar230,
  evar231,
  evar232,
  evar233,
  evar234,
  evar235,
  evar236,
  evar237,
  evar238,
  evar239,
  evar240,
  evar241,
  evar242,
  evar243,
  evar244,
  evar245,
  evar246,
  evar247,
  evar248,
  evar249,
  evar250,
  event_list,
  exclude_hit,
  first_hit_page_url,
  first_hit_pagename,
  first_hit_ref_domain,
  first_hit_ref_type,
  first_hit_referrer,
  first_hit_time_gmt,
  geo_city,
  geo_country,
  geo_dma,
  geo_region,
  geo_zip,
  hier1,
  hier2,
  hier3,
  hier4,
  hier5,
  hit_source,
  hit_time_gmt,
  hitid_high,
  hitid_low,
  homepage,
  hourly_visitor,
  ip,
  ip2,
  ipv6,
  j_jscript,
  java_enabled,
  javascript,
  language,
  last_hit_time_gmt,
  last_purchase_num,
  last_purchase_time_gmt,
  latlon1,
  latlon23,
  latlon45,
  mc_audiences,
  mcvisid,
  mobile_id,
  mobileacquisitionclicks,
  mobileaction,
  mobileactioninapptime,
  mobileactiontotaltime,
  mobileappid,
  mobileappperformanceaffectedusers,
  mobileappperformanceappid,
  mobileappperformanceappid_app_perf_app_name,
  mobileappperformanceappid_app_perf_platform,
  mobileappperformancecrashes,
  mobileappperformancecrashid,
  mobileappperformancecrashid_app_perf_crash_name,
  mobileappperformanceloads,
  mobileappstoreavgrating,
  mobileappstoredownloads,
  mobileappstoreinapprevenue,
  mobileappstoreinapproyalties,
  mobileappstoreobjectid,
  mobileappstoreobjectid_app_store_user,
  mobileappstoreobjectid_application_name,
  mobileappstoreobjectid_application_version,
  mobileappstoreobjectid_appstore_name,
  mobileappstoreobjectid_category_name,
  mobileappstoreobjectid_country_name,
  mobileappstoreobjectid_device_manufacturer,
  mobileappstoreobjectid_device_name,
  mobileappstoreobjectid_in_app_name,
  mobileappstoreobjectid_platform_name_version,
  mobileappstoreobjectid_rank_category_type,
  mobileappstoreobjectid_region_name,
  mobileappstoreobjectid_review_comment,
  mobileappstoreobjectid_review_title,
  mobileappstoreoneoffrevenue,
  mobileappstoreoneoffroyalties,
  mobileappstorepurchases,
  mobileappstorerank,
  mobileappstorerankdivisor,
  mobileappstorerating,
  mobileappstoreratingdivisor,
  mobileavgprevsessionlength,
  mobilebeaconmajor,
  mobilebeaconminor,
  mobilebeaconproximity,
  mobilebeaconuuid,
  mobilecampaigncontent,
  mobilecampaignmedium,
  mobilecampaignname,
  mobilecampaignsource,
  mobilecampaignterm,
  mobilecrashes,
  mobilecrashrate,
  mobiledailyengagedusers,
  mobiledayofweek,
  mobiledayssincefirstuse,
  mobiledayssincelastupgrade,
  mobiledayssincelastuse,
  mobiledeeplinkid,
  mobiledeeplinkid_name,
  mobiledevice,
  mobilehourofday,
  mobileinstalldate,
  mobileinstalls,
  mobilelaunches,
  mobilelaunchessincelastupgrade,
  mobilelaunchnumber,
  mobileltv,
  mobileltvtotal,
  mobilemessagebuttonname,
  mobilemessageclicks,
  mobilemessageid,
  mobilemessageid_dest,
  mobilemessageid_name,
  mobilemessageid_type,
  mobilemessageimpressions,
  mobilemessageonline,
  mobilemessagepushoptin,
  mobilemessagepushpayloadid,
  mobilemessagepushpayloadid_name,
  mobilemessageviews,
  mobilemonthlyengagedusers,
  mobileosenvironment,
  mobileosversion,
  mobileplaceaccuracy,
  mobileplacecategory,
  mobileplacedwelltime,
  mobileplaceentry,
  mobileplaceexit,
  mobileplaceid,
  mobileprevsessionlength,
  mobilepushoptin,
  mobilepushpayloadid,
  mobilerelaunchcampaigncontent,
  mobilerelaunchcampaignmedium,
  mobilerelaunchcampaignsource,
  mobilerelaunchcampaignterm,
  mobilerelaunchcampaigntrackingcode,
  mobilerelaunchcampaigntrackingcode_name,
  mobileresolution,
  mobileupgrades,
  monthly_visitor,
  mvvar1,
  mvvar1_instances,
  mvvar2,
  mvvar2_instances,
  mvvar3,
  mvvar3_instances,
  namespace,
  new_visit,
  os,
  p_plugins,
  page_event,
  page_event_var1,
  page_event_var2,
  page_event_var3,
  page_type,
  page_url,
  pagename,
  paid_search,
  partner_plugins,
  persistent_cookie,
  plugins,
  pointofinterest,
  pointofinterestdistance,
  post_adclassificationcreative,
  post_adload,
  post_browser_height,
  post_browser_width,
  post_campaign,
  post_channel,
  post_clickmaplink,
  post_clickmaplinkbyregion,
  post_clickmappage,
  post_clickmapregion,
  post_cookies,
  post_currency,
  post_cust_hit_time_gmt,
  post_cust_visid,
  post_ef_id,
  post_evar1,
  post_evar2,
  post_evar3,
  post_evar4,
  post_evar5,
  post_evar6,
  post_evar7,
  post_evar8,
  post_evar9,
  post_evar10,
  post_evar11,
  post_evar12,
  post_evar13,
  post_evar14,
  post_evar15,
  post_evar16,
  post_evar17,
  post_evar18,
  post_evar19,
  post_evar20,
  post_evar21,
  post_evar22,
  post_evar23,
  post_evar24,
  post_evar25,
  post_evar26,
  post_evar27,
  post_evar28,
  post_evar29,
  post_evar30,
  post_evar31,
  post_evar32,
  post_evar33,
  post_evar34,
  post_evar35,
  post_evar36,
  post_evar37,
  post_evar38,
  post_evar39,
  post_evar40,
  post_evar41,
  post_evar42,
  post_evar43,
  post_evar44,
  post_evar45,
  post_evar46,
  post_evar47,
  post_evar48,
  post_evar49,
  post_evar50,
  post_evar51,
  post_evar52,
  post_evar53,
  post_evar54,
  post_evar55,
  post_evar56,
  post_evar57,
  post_evar58,
  post_evar59,
  post_evar60,
  post_evar61,
  post_evar62,
  post_evar63,
  post_evar64,
  post_evar65,
  post_evar66,
  post_evar67,
  post_evar68,
  post_evar69,
  post_evar70,
  post_evar71,
  post_evar72,
  post_evar73,
  post_evar74,
  post_evar75,
  post_evar76,
  post_evar77,
  post_evar78,
  post_evar79,
  post_evar80,
  post_evar81,
  post_evar82,
  post_evar83,
  post_evar84,
  post_evar85,
  post_evar86,
  post_evar87,
  post_evar88,
  post_evar89,
  post_evar90,
  post_evar91,
  post_evar92,
  post_evar93,
  post_evar94,
  post_evar95,
  post_evar96,
  post_evar97,
  post_evar98,
  post_evar99,
  post_evar100,
  post_evar101,
  post_evar102,
  post_evar103,
  post_evar104,
  post_evar105,
  post_evar106,
  post_evar107,
  post_evar108,
  post_evar109,
  post_evar110,
  post_evar111,
  post_evar112,
  post_evar113,
  post_evar114,
  post_evar115,
  post_evar116,
  post_evar117,
  post_evar118,
  post_evar119,
  post_evar120,
  post_evar121,
  post_evar122,
  post_evar123,
  post_evar124,
  post_evar125,
  post_evar126,
  post_evar127,
  post_evar128,
  post_evar129,
  post_evar130,
  post_evar131,
  post_evar132,
  post_evar133,
  post_evar134,
  post_evar135,
  post_evar136,
  post_evar137,
  post_evar138,
  post_evar139,
  post_evar140,
  post_evar141,
  post_evar142,
  post_evar143,
  post_evar144,
  post_evar145,
  post_evar146,
  post_evar147,
  post_evar148,
  post_evar149,
  post_evar150,
  post_evar151,
  post_evar152,
  post_evar153,
  post_evar154,
  post_evar155,
  post_evar156,
  post_evar157,
  post_evar158,
  post_evar159,
  post_evar160,
  post_evar161,
  post_evar162,
  post_evar163,
  post_evar164,
  post_evar165,
  post_evar166,
  post_evar167,
  post_evar168,
  post_evar169,
  post_evar170,
  post_evar171,
  post_evar172,
  post_evar173,
  post_evar174,
  post_evar175,
  post_evar176,
  post_evar177,
  post_evar178,
  post_evar179,
  post_evar180,
  post_evar181,
  post_evar182,
  post_evar183,
  post_evar184,
  post_evar185,
  post_evar186,
  post_evar187,
  post_evar188,
  post_evar189,
  post_evar190,
  post_evar191,
  post_evar192,
  post_evar193,
  post_evar194,
  post_evar195,
  post_evar196,
  post_evar197,
  post_evar198,
  post_evar199,
  post_evar200,
  post_evar201,
  post_evar202,
  post_evar203,
  post_evar204,
  post_evar205,
  post_evar206,
  post_evar207,
  post_evar208,
  post_evar209,
  post_evar210,
  post_evar211,
  post_evar212,
  post_evar213,
  post_evar214,
  post_evar215,
  post_evar216,
  post_evar217,
  post_evar218,
  post_evar219,
  post_evar220,
  post_evar221,
  post_evar222,
  post_evar223,
  post_evar224,
  post_evar225,
  post_evar226,
  post_evar227,
  post_evar228,
  post_evar229,
  post_evar230,
  post_evar231,
  post_evar232,
  post_evar233,
  post_evar234,
  post_evar235,
  post_evar236,
  post_evar237,
  post_evar238,
  post_evar239,
  post_evar240,
  post_evar241,
  post_evar242,
  post_evar243,
  post_evar244,
  post_evar245,
  post_evar246,
  post_evar247,
  post_evar248,
  post_evar249,
  post_evar250,
  post_event_list,
  post_hier1,
  post_hier2,
  post_hier3,
  post_hier4,
  post_hier5,
  post_java_enabled,
  post_keywords,
  post_mc_audiences,
  post_mobileaction,
  post_mobileappid,
  post_mobilecampaigncontent,
  post_mobilecampaignmedium,
  post_mobilecampaignname,
  post_mobilecampaignsource,
  post_mobilecampaignterm,
  post_mobiledayofweek,
  post_mobiledayssincefirstuse,
  post_mobiledayssincelastuse,
  post_mobiledevice,
  post_mobilehourofday,
  post_mobileinstalldate,
  post_mobilelaunchnumber,
  post_mobileltv,
  post_mobilemessagebuttonname,
  post_mobilemessageclicks,
  post_mobilemessageid,
  post_mobilemessageid_dest,
  post_mobilemessageid_name,
  post_mobilemessageid_type,
  post_mobilemessageimpressions,
  post_mobilemessageonline,
  post_mobilemessagepushoptin,
  post_mobilemessagepushpayloadid,
  post_mobilemessagepushpayloadid_name,
  post_mobilemessageviews,
  post_mobileosversion,
  post_mobilepushoptin,
  post_mobilepushpayloadid,
  post_mobileresolution,
  post_mvvar1,
  post_mvvar1_instances,
  post_mvvar2,
  post_mvvar2_instances,
  post_mvvar3,
  post_mvvar3_instances,
  post_page_event,
  post_page_event_var1,
  post_page_event_var2,
  post_page_event_var3,
  post_page_type,
  post_page_url,
  post_pagename,
  post_pagename_no_url,
  post_partner_plugins,
  post_persistent_cookie,
  post_pointofinterest,
  post_pointofinterestdistance,
  post_product_list,
  post_prop1,
  post_prop2,
  post_prop3,
  post_prop4,
  post_prop5,
  post_prop6,
  post_prop7,
  post_prop8,
  post_prop9,
  post_prop10,
  post_prop11,
  post_prop12,
  post_prop13,
  post_prop14,
  post_prop15,
  post_prop16,
  post_prop17,
  post_prop18,
  post_prop19,
  post_prop20,
  post_prop21,
  post_prop22,
  post_prop23,
  post_prop24,
  post_prop25,
  post_prop26,
  post_prop27,
  post_prop28,
  post_prop29,
  post_prop30,
  post_prop31,
  post_prop32,
  post_prop33,
  post_prop34,
  post_prop35,
  post_prop36,
  post_prop37,
  post_prop38,
  post_prop39,
  post_prop40,
  post_prop41,
  post_prop42,
  post_prop43,
  post_prop44,
  post_prop45,
  post_prop46,
  post_prop47,
  post_prop48,
  post_prop49,
  post_prop50,
  post_prop51,
  post_prop52,
  post_prop53,
  post_prop54,
  post_prop55,
  post_prop56,
  post_prop57,
  post_prop58,
  post_prop59,
  post_prop60,
  post_prop61,
  post_prop62,
  post_prop63,
  post_prop64,
  post_prop65,
  post_prop66,
  post_prop67,
  post_prop68,
  post_prop69,
  post_prop70,
  post_prop71,
  post_prop72,
  post_prop73,
  post_prop74,
  post_prop75,
  post_purchaseid,
  post_referrer,
  post_s_kwcid,
  post_search_engine,
  post_socialaccountandappids,
  post_socialassettrackingcode,
  post_socialauthor,
  post_socialaveragesentiment,
  post_socialaveragesentiment_deprecated,
  post_socialcontentprovider,
  post_socialfbstories,
  post_socialfbstorytellers,
  post_socialinteractioncount,
  post_socialinteractiontype,
  post_sociallanguage,
  post_sociallatlong,
  post_sociallikeadds,
  post_sociallink,
  post_sociallink_deprecated,
  post_socialmentions,
  post_socialowneddefinitioninsighttype,
  post_socialowneddefinitioninsightvalue,
  post_socialowneddefinitionmetric,
  post_socialowneddefinitionpropertyvspost,
  post_socialownedpostids,
  post_socialownedpropertyid,
  post_socialownedpropertyname,
  post_socialownedpropertypropertyvsapp,
  post_socialpageviews,
  post_socialpostviews,
  post_socialproperty,
  post_socialproperty_deprecated,
  post_socialpubcomments,
  post_socialpubposts,
  post_socialpubrecommends,
  post_socialpubsubscribers,
  post_socialterm,
  post_socialtermslist,
  post_socialtermslist_deprecated,
  post_socialtotalsentiment,
  post_state,
  post_survey,
  post_t_time_info,
  post_tnt,
  post_tnt_action,
  post_transactionid,
  post_user_server,
  post_video,
  post_videoad,
  post_videoadinpod,
  post_videoadlength,
  post_videoadname,
  post_videoadplayername,
  post_videoadpod,
  post_videoadvertiser,
  post_videoauthorized,
  post_videocampaign,
  post_videochannel,
  post_videochapter,
  post_videocontenttype,
  post_videodaypart,
  post_videoepisode,
  post_videofeedtype,
  post_videogenre,
  post_videolength,
  post_videomvpd,
  post_videoname,
  post_videonetwork,
  post_videopath,
  post_videoplayername,
  post_videoqoebitrateaverageevar,
  post_videoqoebitratechangecountevar,
  post_videoqoebuffercountevar,
  post_videoqoebuffertimeevar,
  post_videoqoedroppedframecountevar,
  post_videoqoeerrorcountevar,
  post_videoqoeplayersdkerrors,
  post_videoqoetimetostartevar,
  post_videoseason,
  post_videosegment,
  post_videoshow,
  post_videoshowtype,
  post_visid_high,
  post_visid_low,
  post_visid_type,
  post_zip,
  prev_page,
  product_list,
  product_merchandising,
  prop1,
  prop2,
  prop3,
  prop4,
  prop5,
  prop6,
  prop7,
  prop8,
  prop9,
  prop10,
  prop11,
  prop12,
  prop13,
  prop14,
  prop15,
  prop16,
  prop17,
  prop18,
  prop19,
  prop20,
  prop21,
  prop22,
  prop23,
  prop24,
  prop25,
  prop26,
  prop27,
  prop28,
  prop29,
  prop30,
  prop31,
  prop32,
  prop33,
  prop34,
  prop35,
  prop36,
  prop37,
  prop38,
  prop39,
  prop40,
  prop41,
  prop42,
  prop43,
  prop44,
  prop45,
  prop46,
  prop47,
  prop48,
  prop49,
  prop50,
  prop51,
  prop52,
  prop53,
  prop54,
  prop55,
  prop56,
  prop57,
  prop58,
  prop59,
  prop60,
  prop61,
  prop62,
  prop63,
  prop64,
  prop65,
  prop66,
  prop67,
  prop68,
  prop69,
  prop70,
  prop71,
  prop72,
  prop73,
  prop74,
  prop75,
  purchaseid,
  quarterly_visitor,
  ref_domain,
  ref_type,
  referrer,
  resolution,
  s_kwcid,
  s_resolution,
  sampled_hit,
  search_engine,
  search_page_num,
  secondary_hit,
  service,
  socialaccountandappids,
  socialassettrackingcode,
  socialauthor,
  socialaveragesentiment,
  socialaveragesentiment_deprecated,
  socialcontentprovider,
  socialfbstories,
  socialfbstorytellers,
  socialinteractioncount,
  socialinteractiontype,
  sociallanguage,
  sociallatlong,
  sociallikeadds,
  sociallink,
  sociallink_deprecated,
  socialmentions,
  socialowneddefinitioninsighttype,
  socialowneddefinitioninsightvalue,
  socialowneddefinitionmetric,
  socialowneddefinitionpropertyvspost,
  socialownedpostids,
  socialownedpropertyid,
  socialownedpropertyname,
  socialownedpropertypropertyvsapp,
  socialpageviews,
  socialpostviews,
  socialproperty,
  socialproperty_deprecated,
  socialpubcomments,
  socialpubposts,
  socialpubrecommends,
  socialpubsubscribers,
  socialterm,
  socialtermslist,
  socialtermslist_deprecated,
  socialtotalsentiment,
  sourceid,
  state,
  stats_server,
  survey_instances,
  t_time_info,
  tnt,
  tnt_action,
  tnt_instances,
  tnt_post_vista,
  transactionid,
  truncated_hit,
  ua_color,
  ua_os,
  ua_pixels,
  user_agent,
  user_hash,
  user_server,
  userid,
  username,
  va_closer_detail,
  va_closer_id,
  va_finder_detail,
  va_finder_id,
  va_instance_event,
  va_new_engagement,
  video,
  videoad,
  videoadinpod,
  videoadlength,
  videoadname,
  videoadplayername,
  videoadpod,
  videoadvertiser,
  videoaudioalbum,
  videoaudioartist,
  videoaudioauthor,
  videoaudiolabel,
  videoaudiopublisher,
  videoaudiostation,
  videoauthorized,
  videoaverageminuteaudience,
  videocampaign,
  videochannel,
  videochapter,
  videochaptercomplete,
  videochapterstart,
  videochaptertime,
  videocontenttype,
  videodaypart,
  videoepisode,
  videofeedtype,
  videogenre,
  videolength,
  videomvpd,
  videoname,
  videonetwork,
  videopath,
  videopause,
  videopausecount,
  videopausetime,
  videoplay,
  videoplayername,
  videoprogress10,
  videoprogress25,
  videoprogress50,
  videoprogress75,
  videoprogress96,
  videoqoebitrateaverage,
  videoqoebitrateaverageevar,
  videoqoebitratechange,
  videoqoebitratechangecountevar,
  videoqoebuffer,
  videoqoebuffercountevar,
  videoqoebuffertimeevar,
  videoqoedropbeforestart,
  videoqoedroppedframecountevar,
  videoqoedroppedframes,
  videoqoeerror,
  videoqoeerrorcountevar,
  videoqoeextneralerrors,
  videoqoeplayersdkerrors,
  videoqoetimetostartevar,
  videoresume,
  videoseason,
  videosegment,
  videoshow,
  videoshowtype,
  videostreamtype,
  videototaltime,
  videouniquetimeplayed,
  visid_high,
  visid_low,
  visid_new,
  visid_timestamp,
  visid_type,
  visit_keywords,
  visit_num,
  visit_page_num,
  visit_ref_domain,
  visit_ref_type,
  visit_referrer,
  visit_search_engine,
  visit_start_page_url,
  visit_start_pagename,
  visit_start_time_gmt,
  weekly_visitor,
  yearly_visitor,
  zip
FROM SEED();
