MODEL (
  name web_analytics_seeds.SITE_PRODUCT_DETAILS,
  kind SEED (
    path '../../seeds/site_product_details.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Product catalog seed data with item details and classifications',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('site_product_details'),
  columns (
        _metadata VARCHAR,
        site_item_pk_product VARCHAR,
        proof_flag_item VARCHAR,
        publish_flag VARCHAR,
        reservetype VARCHAR,
        sitecode VARCHAR,
        sitename VARCHAR,
        site_number BIGINT,
        itemnumber BIGINT,
        item_status VARCHAR,
        site_product_premise VARCHAR,
        frontline1_case_price DECIMAL(18, 2),
        frontline2_case_price DECIMAL(18, 2),
        frontline1_price_per_bottle DECIMAL(18, 2),
        frontline2_price_per_bottle DECIMAL(18, 2),
        liquiditemcount BIGINT,
        site_bottles_per_case BIGINT,
        item_closeout_indicator VARCHAR,
        innovation_item VARCHAR,
        division VARCHAR,
        item_status_cd VARCHAR,
        item_reason_cd VARCHAR,
        otc_portal_community_visibility_cd VARCHAR,
        product_badges VARCHAR,
        required_license VARCHAR,
        excluded_county_numbers VARCHAR,
        control_state_item_id VARCHAR,
        pricegrp1_promobrandnumber BIGINT,
        pricegrp1_promobrandname VARCHAR,
        pricegrp2_promohousebrandnumber BIGINT,
        pricegrp2_promohousebrandname VARCHAR,
        item_sales_company BIGINT,
        item_separate_pricing_ind VARCHAR,
        street_deal_no_on VARCHAR,
        street_deal_no_off VARCHAR,
        street_deal_no_any VARCHAR,
        item_sold_by_desc VARCHAR,
        item_sold_by_cases_ind VARCHAR,
        sales_aggregate_qtr_revenue DECIMAL(18, 2),
        sales_aggregate_half_year_revenue DECIMAL(18, 2),
        month_over_month_sales_growth_percentage DECIMAL(10, 4),
        year_over_year_sales_growth DECIMAL(18, 4),
        unit_sales_same_month_last_year DECIMAL(18, 4),
        sales_revenue_same_month_last_year DECIMAL(18, 2),
        unit_sales_rolling_yoy DECIMAL(18, 4),
        month_over_month_sales_growth DECIMAL(18, 4),
        month_over_month_on_premise_sales_growth DECIMAL(18, 4),
        month_over_month_off_premise_sales_growth DECIMAL(18, 4),
        month_over_month_any_premise_sales_growth DECIMAL(18, 4),
        sales_revenue_on_premise_same_month_last_year DECIMAL(18, 2),
        sales_revenue_off_premise_same_month_last_year DECIMAL(18, 2),
        sales_revenue_any_premise_same_month_last_year DECIMAL(18, 2),
        unit_sales_on_premise_rolling_yoy DECIMAL(18, 4),
        unit_sales_off_premise_rolling_yoy DECIMAL(18, 4),
        unit_sales_any_premise_rolling_yoy DECIMAL(18, 4),
        bestseller_off_premise VARCHAR,
        bestseller_on_premise VARCHAR,
        bestseller_any_premise VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: SITE_PRODUCT_DETAILS
-- ============================================================================

SELECT
  _metadata,
  site_item_pk_product,
  proof_flag_item,
  publish_flag,
  reservetype,
  sitecode,
  sitename,
  site_number,
  itemnumber,
  item_status,
  site_product_premise,
  frontline1_case_price,
  frontline2_case_price,
  frontline1_price_per_bottle,
  frontline2_price_per_bottle,
  liquiditemcount,
  site_bottles_per_case,
  item_closeout_indicator,
  innovation_item,
  division,
  item_status_cd,
  item_reason_cd,
  otc_portal_community_visibility_cd,
  product_badges,
  required_license,
  excluded_county_numbers,
  control_state_item_id,
  pricegrp1_promobrandnumber,
  pricegrp1_promobrandname,
  pricegrp2_promohousebrandnumber,
  pricegrp2_promohousebrandname,
  item_sales_company,
  item_separate_pricing_ind,
  street_deal_no_on,
  street_deal_no_off,
  street_deal_no_any,
  item_sold_by_desc,
  item_sold_by_cases_ind,
  sales_aggregate_qtr_revenue,
  sales_aggregate_half_year_revenue,
  month_over_month_sales_growth_percentage,
  year_over_year_sales_growth,
  unit_sales_same_month_last_year,
  sales_revenue_same_month_last_year,
  unit_sales_rolling_yoy,
  month_over_month_sales_growth,
  month_over_month_on_premise_sales_growth,
  month_over_month_off_premise_sales_growth,
  month_over_month_any_premise_sales_growth,
  sales_revenue_on_premise_same_month_last_year,
  sales_revenue_off_premise_same_month_last_year,
  sales_revenue_any_premise_same_month_last_year,
  unit_sales_on_premise_rolling_yoy,
  unit_sales_off_premise_rolling_yoy,
  unit_sales_any_premise_rolling_yoy,
  bestseller_off_premise,
  bestseller_on_premise,
  bestseller_any_premise
FROM SEED();
