MODEL (
  name web_analytics_seeds.V_D_SITE,
  kind SEED (
    path '../../seeds/v_d_site.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Distribution site location reference data',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('v_d_site'),
  columns (
        site_sk BIGINT,
        site BIGINT,
        site_name VARCHAR,
        appl_display_name VARCHAR,
        site_short_name VARCHAR,
        region_name VARCHAR,
        bdn_site_no BIGINT,
        site_address_1 VARCHAR,
        site_address_2 VARCHAR,
        site_city VARCHAR,
        site_state VARCHAR,
        site_zip_cd BIGINT,
        site_zip_cd_ext BIGINT,
        site_county VARCHAR,
        site_fiscal_year_ccyy BIGINT,
        site_fiscal_period BIGINT,
        lastrundate VARCHAR,
        postingperiod BIGINT,
        posting_prd_sk BIGINT,
        postingday BIGINT,
        tdlinx_storecode_prefix VARCHAR,
        modified_user VARCHAR,
        effective_from_dt VARCHAR,
        effective_thru_dt VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR,
        current_ind VARCHAR,
        src_desc VARCHAR,
        active_ind VARCHAR,
        last_inv_date DATE,
        sap_company_code BIGINT,
        lrd_lastrundate VARCHAR,
        lrd_postingperiod BIGINT,
        lrd_postingday BIGINT,
        postingday_cal_dt VARCHAR,
        depletion_postingperiod BIGINT,
        depletion_posting_prd_sk BIGINT,
        inventory_postingday BIGINT,
        source_system VARCHAR,
        last_closed_posting_period BIGINT,
        last_posting_period_closed_date DATE,
        national_reporting_ind VARCHAR,
        sop_ind VARCHAR,
        site_end_of_day_total_net DECIMAL(18, 2),
        site_end_of_day_total_cases DECIMAL(15, 3),
        site_end_of_day_total_records_processed BIGINT,
        tdlinx_distribution_ind VARCHAR,
        site_geo_region VARCHAR,
        site_geo_sub_region VARCHAR,
        site_geo_region_short_name VARCHAR,
        check_sum VARCHAR,
        rt_posting_prd BIGINT,
        rt_posting_dt DATE,
        rt_posting_prd_sk BIGINT,
        rt_inventory_posting_prd BIGINT,
        rt_inventory_posting_dt DATE,
        inventory_posting_prd_sk BIGINT,
        rt_inventory_posting_prd_sk BIGINT,
        rt_last_refresh_time VARCHAR,
        processed_ind VARCHAR,
        depletion_ind VARCHAR,
        site_abbrev VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: V_D_SITE
-- ============================================================================

SELECT
  site_sk,
  site,
  site_name,
  appl_display_name,
  site_short_name,
  region_name,
  bdn_site_no,
  site_address_1,
  site_address_2,
  site_city,
  site_state,
  site_zip_cd,
  site_zip_cd_ext,
  site_county,
  site_fiscal_year_ccyy,
  site_fiscal_period,
  lastrundate,
  postingperiod,
  posting_prd_sk,
  postingday,
  tdlinx_storecode_prefix,
  modified_user,
  effective_from_dt,
  effective_thru_dt,
  load_dt,
  modified_dt,
  current_ind,
  src_desc,
  active_ind,
  last_inv_date,
  sap_company_code,
  lrd_lastrundate,
  lrd_postingperiod,
  lrd_postingday,
  postingday_cal_dt,
  depletion_postingperiod,
  depletion_posting_prd_sk,
  inventory_postingday,
  source_system,
  last_closed_posting_period,
  last_posting_period_closed_date,
  national_reporting_ind,
  sop_ind,
  site_end_of_day_total_net,
  site_end_of_day_total_cases,
  site_end_of_day_total_records_processed,
  tdlinx_distribution_ind,
  site_geo_region,
  site_geo_sub_region,
  site_geo_region_short_name,
  check_sum,
  rt_posting_prd,
  rt_posting_dt,
  rt_posting_prd_sk,
  rt_inventory_posting_prd,
  rt_inventory_posting_dt,
  inventory_posting_prd_sk,
  rt_inventory_posting_prd_sk,
  rt_last_refresh_time,
  processed_ind,
  depletion_ind,
  site_abbrev
FROM SEED();
