MODEL (
  name web_analytics_seeds.V_D_CUSTOMER_NA_ATTRIBUTES,
  kind SEED (
    path '../../seeds/v_d_customer_na_attributes.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Static customer reference data from source system',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('v_d_customer_na_attributes'),
  columns (
        customer_na_attributes_sk BIGINT,
        site_sk BIGINT,
        site VARCHAR,
        customer_no VARCHAR,
        customer_sk VARCHAR,
        na_national_operator_cd VARCHAR,
        na_national_operator_name VARCHAR,
        rtm_national_acct_vp VARCHAR,
        rtm_national_acct_director VARCHAR,
        rtm_national_channel_code VARCHAR,
        rtm_national_channel_desc VARCHAR,
        na_national_operator_acct_graduation_ind VARCHAR,
        rtm_national_chain_code VARCHAR,
        rtm_national_chain_desc VARCHAR,
        rtm_national_sub_channel_desc VARCHAR,
        rtm_national_sub_channel_code VARCHAR,
        na_national_operator_banner_srv_lvl_cd VARCHAR,
        na_national_operator_banner_srv_lvl_desc VARCHAR,
        na_national_operator_concept_banner_cd VARCHAR,
        na_national_operator_concept_banner_name VARCHAR,
        univ_customer_no VARCHAR,
        na_retailer_store_id VARCHAR,
        na_retailer_store_desc VARCHAR,
        na_national_operator_customer_industry_cd VARCHAR,
        na_national_operator_customer_industry_desc VARCHAR,
        na_national_operator_customer_line_of_business_cd VARCHAR,
        na_national_operator_customer_line_of_business_desc VARCHAR,
        na_national_operator_unit_program_autonomy_cd VARCHAR,
        na_national_operator_unit_program_autonomy_desc VARCHAR,
        na_national_operator_proprietor_franchise_ownership VARCHAR,
        na_national_customer_in_compliance_ind VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR,
        modified_user VARCHAR,
        src_desc VARCHAR,
        source_system VARCHAR,
        is_deleted VARCHAR,
        check_sum VARCHAR,
        retailer_store_id VARCHAR,
        retailer_store_banner VARCHAR,
        retailer_store_assortment_group_desc VARCHAR,
        retailer_store_group_desc VARCHAR,
        retailer_store_beer_group_desc VARCHAR,
        retailer_store_spirit_group_desc VARCHAR,
        retailer_store_wine_group_desc VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: V_D_CUSTOMER_NA_ATTRIBUTES
-- ============================================================================

SELECT
  customer_na_attributes_sk,
  site_sk,
  site,
  customer_no,
  customer_sk,
  na_national_operator_cd,
  na_national_operator_name,
  rtm_national_acct_vp,
  rtm_national_acct_director,
  rtm_national_channel_code,
  rtm_national_channel_desc,
  na_national_operator_acct_graduation_ind,
  rtm_national_chain_code,
  rtm_national_chain_desc,
  rtm_national_sub_channel_desc,
  rtm_national_sub_channel_code,
  na_national_operator_banner_srv_lvl_cd,
  na_national_operator_banner_srv_lvl_desc,
  na_national_operator_concept_banner_cd,
  na_national_operator_concept_banner_name,
  univ_customer_no,
  na_retailer_store_id,
  na_retailer_store_desc,
  na_national_operator_customer_industry_cd,
  na_national_operator_customer_industry_desc,
  na_national_operator_customer_line_of_business_cd,
  na_national_operator_customer_line_of_business_desc,
  na_national_operator_unit_program_autonomy_cd,
  na_national_operator_unit_program_autonomy_desc,
  na_national_operator_proprietor_franchise_ownership,
  na_national_customer_in_compliance_ind,
  load_dt,
  modified_dt,
  modified_user,
  src_desc,
  source_system,
  is_deleted,
  check_sum,
  retailer_store_id,
  retailer_store_banner,
  retailer_store_assortment_group_desc,
  retailer_store_group_desc,
  retailer_store_beer_group_desc,
  retailer_store_spirit_group_desc,
  retailer_store_wine_group_desc
FROM SEED();
