MODEL (
  name web_analytics_seeds.V_D_CURRENT_ACCOUNT_SALESPERSON,
  kind SEED (
    path '../../seeds/v_d_current_account_salesperson.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Historical sales transaction seed data for testing and development',
  tags ('seed', 'reference_data', 'transactional', 'testing'),
  terms ('v_d_current_account_salesperson'),
  columns (
        site_state BIGINT,
        site VARCHAR,
        customer_no VARCHAR,
        item_div VARCHAR,
        salesperson_name VARCHAR,
        type VARCHAR,
        status VARCHAR,
        market VARCHAR,
        salesperson_empl_no VARCHAR,
        last_name VARCHAR,
        first_name VARCHAR,
        middle_int VARCHAR,
        company VARCHAR,
        selling_channel VARCHAR,
        house_salesperson VARCHAR,
        salesperson_type VARCHAR,
        team_name VARCHAR,
        team_email_address VARCHAR,
        team_mgr VARCHAR,
        team_company VARCHAR,
        team_empl_no VARCHAR,
        team_business_center_id VARCHAR,
        team_mgr_salesperson_id VARCHAR,
        territory_desc VARCHAR,
        territory_empl_no VARCHAR,
        territory_email_address VARCHAR,
        territory_mgr VARCHAR,
        territory_business_ctr_no VARCHAR,
        company_group VARCHAR,
        modified_user VARCHAR,
        effective_from_dt VARCHAR,
        effective_thru_dt VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR,
        current_ind VARCHAR,
        src_desc VARCHAR,
        active_ind VARCHAR,
        univ_salesperson_no VARCHAR,
        premise_type VARCHAR,
        salesperson_type_cd VARCHAR,
        salesperson_msc_reg_cd VARCHAR,
        rpt_team_company_code VARCHAR,
        rpt_team_company_desc VARCHAR,
        rpt_team_company_short_desc VARCHAR,
        rpt_company_code VARCHAR,
        rpt_company_desc VARCHAR,
        rpt_company_short_desc VARCHAR,
        salesperson_no VARCHAR,
        team_no VARCHAR,
        team_territory VARCHAR,
        territory VARCHAR,
        division_mgr_no VARCHAR,
        division_mgr_email_address VARCHAR,
        division_mgr_name VARCHAR,
        division_mgr_empl_no VARCHAR,
        division_business_center_id VARCHAR,
        region_mgr_no VARCHAR,
        region_mgr_email_address VARCHAR,
        region_mgr_name VARCHAR,
        region_mgr_empl_no VARCHAR,
        region_business_center_id VARCHAR,
        email_address VARCHAR,
        source_system VARCHAR,
        empl_group_name VARCHAR,
        empl_subgroup_name VARCHAR,
        empl_hire_date VARCHAR,
        empl_terminate_date VARCHAR,
        empl_position_desc VARCHAR,
        profit_center_cd VARCHAR,
        profit_center_short_desc VARCHAR,
        empl_personnel_area_cd VARCHAR,
        empl_personnel_area_name VARCHAR,
        empl_personnel_subarea VARCHAR,
        empl_job_title VARCHAR,
        empl_phone_no VARCHAR,
        cost_center_name VARCHAR,
        cost_center_cd VARCHAR,
        premise_type_desc VARCHAR,
        miscellaneous2 VARCHAR,
        salesperson_mobil_phone_no VARCHAR,
        salesperson_voicemail_no VARCHAR,
        salesperson_assignment_cd VARCHAR,
        miscellaneous1 VARCHAR,
        team_mng_mobil_phone_no VARCHAR,
        team_mng_voicemail_no VARCHAR,
        team_active_cd VARCHAR,
        team_sales_company_cd VARCHAR,
        team_premise_type VARCHAR,
        territory_mng_mobil_phone_no VARCHAR,
        territory_mng_voicemail_no VARCHAR,
        division_mng_mobil_phone_no VARCHAR,
        division_mng_voicemail_no VARCHAR,
        region_mng_mobil_phone_no VARCHAR,
        region_mng_voicemail_no VARCHAR,
        salesperson_transfer_info_1 VARCHAR,
        salesperson_transfer_info_2 VARCHAR,
        salesperson_effective_dt VARCHAR,
        salesperson_change_by VARCHAR,
        salesperson_last_change_dt VARCHAR,
        is_deleted VARCHAR,
        salesperson_type_long_desc VARCHAR,
        assign_salesperson_market_cd VARCHAR,
        assign_salesperson_market_short_desc VARCHAR,
        assign_salesperson_market_long_desc VARCHAR,
        salesperson_item_group_territory_cd VARCHAR,
        salesperson_item_group_territory_desc VARCHAR,
        team_type_cd VARCHAR,
        team_type_short_desc VARCHAR,
        team_type_long_desc VARCHAR,
        team_market_cd VARCHAR,
        team_market_short_desc VARCHAR,
        team_market_long_desc VARCHAR,
        region_mgr_type_cd VARCHAR,
        region_mgr_type_short_desc VARCHAR,
        region_mgr_type_long_desc VARCHAR,
        dept_mgr_type_cd VARCHAR,
        dept_mgr_type_short_desc VARCHAR,
        dept_mgr_type_long_desc VARCHAR,
        area_mgr_type_cd VARCHAR,
        area_mgr_type_short_desc VARCHAR,
        area_mgr_type_long_desc VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: V_D_CURRENT_ACCOUNT_SALESPERSON
-- ============================================================================

SELECT
  site_state,
  site,
  customer_no,
  item_div,
  salesperson_name,
  type,
  status,
  market,
  salesperson_empl_no,
  last_name,
  first_name,
  middle_int,
  company,
  selling_channel,
  house_salesperson,
  salesperson_type,
  team_name,
  team_email_address,
  team_mgr,
  team_company,
  team_empl_no,
  team_business_center_id,
  team_mgr_salesperson_id,
  territory_desc,
  territory_empl_no,
  territory_email_address,
  territory_mgr,
  territory_business_ctr_no,
  company_group,
  modified_user,
  effective_from_dt,
  effective_thru_dt,
  load_dt,
  modified_dt,
  current_ind,
  src_desc,
  active_ind,
  univ_salesperson_no,
  premise_type,
  salesperson_type_cd,
  salesperson_msc_reg_cd,
  rpt_team_company_code,
  rpt_team_company_desc,
  rpt_team_company_short_desc,
  rpt_company_code,
  rpt_company_desc,
  rpt_company_short_desc,
  salesperson_no,
  team_no,
  team_territory,
  territory,
  division_mgr_no,
  division_mgr_email_address,
  division_mgr_name,
  division_mgr_empl_no,
  division_business_center_id,
  region_mgr_no,
  region_mgr_email_address,
  region_mgr_name,
  region_mgr_empl_no,
  region_business_center_id,
  email_address,
  source_system,
  empl_group_name,
  empl_subgroup_name,
  empl_hire_date,
  empl_terminate_date,
  empl_position_desc,
  profit_center_cd,
  profit_center_short_desc,
  empl_personnel_area_cd,
  empl_personnel_area_name,
  empl_personnel_subarea,
  empl_job_title,
  empl_phone_no,
  cost_center_name,
  cost_center_cd,
  premise_type_desc,
  miscellaneous2,
  salesperson_mobil_phone_no,
  salesperson_voicemail_no,
  salesperson_assignment_cd,
  miscellaneous1,
  team_mng_mobil_phone_no,
  team_mng_voicemail_no,
  team_active_cd,
  team_sales_company_cd,
  team_premise_type,
  territory_mng_mobil_phone_no,
  territory_mng_voicemail_no,
  division_mng_mobil_phone_no,
  division_mng_voicemail_no,
  region_mng_mobil_phone_no,
  region_mng_voicemail_no,
  salesperson_transfer_info_1,
  salesperson_transfer_info_2,
  salesperson_effective_dt,
  salesperson_change_by,
  salesperson_last_change_dt,
  is_deleted,
  salesperson_type_long_desc,
  assign_salesperson_market_cd,
  assign_salesperson_market_short_desc,
  assign_salesperson_market_long_desc,
  salesperson_item_group_territory_cd,
  salesperson_item_group_territory_desc,
  team_type_cd,
  team_type_short_desc,
  team_type_long_desc,
  team_market_cd,
  team_market_short_desc,
  team_market_long_desc,
  region_mgr_type_cd,
  region_mgr_type_short_desc,
  region_mgr_type_long_desc,
  dept_mgr_type_cd,
  dept_mgr_type_short_desc,
  dept_mgr_type_long_desc,
  area_mgr_type_cd,
  area_mgr_type_short_desc,
  area_mgr_type_long_desc
FROM SEED();
