MODEL (
  name web_analytics_seeds.V_F_NPW_PRICING,
  kind SEED (
    path '../../seeds/v_f_npw_pricing.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Product pricing reference data',
  tags ('seed', 'reference_data', 'lookup'),
  terms ('v_f_npw_pricing'),
  columns (
        npw_pricing_sk BIGINT,
        site_id BIGINT,
        project_id BIGINT,
        item_no DECIMAL(18, 4),
        pricing_type_sk VARCHAR,
        chain_plan_id VARCHAR,
        customer_no VARCHAR,
        street_deal_no VARCHAR,
        product_type VARCHAR,
        primary_column_value VARCHAR,
        secondary_column_value VARCHAR,
        pricing_name VARCHAR,
        pricing_start_date_sk VARCHAR,
        pricing_end_date_sk VARCHAR,
        pricing_effective_date_sk VARCHAR,
        premise VARCHAR,
        accum_qty VARCHAR,
        accum_uom VARCHAR,
        accum_type VARCHAR,
        order_qty_qualifier VARCHAR,
        reserve_pricing_ind VARCHAR,
        published_pricing VARCHAR,
        price_type DECIMAL(18, 2),
        frontline_case_price DECIMAL(18, 2),
        frontline_case_price2 DECIMAL(18, 2),
        frontline_case_price3 DECIMAL(18, 2),
        frontline_case_price4 DECIMAL(18, 2),
        case_discount_amt DECIMAL(18, 2),
        case_target_price DECIMAL(18, 2),
        additional_net_amt DECIMAL(18, 2),
        fob_amt DECIMAL(18, 2),
        fed_tax_duty_amt DECIMAL(18, 2),
        state_tax_amt DECIMAL(18, 2),
        case_purch_allowance_amt DECIMAL(18, 2),
        laid_in_amt DECIMAL(18, 2),
        da_start_date_sk VARCHAR,
        da_end_date_sk VARCHAR,
        da_bank_id VARCHAR,
        gp_pos_da_amt DECIMAL(18, 2),
        gp_neg_da_amt DECIMAL(18, 2),
        nongp_pos_da_amt DECIMAL(18, 2),
        nongp_neg_da_amt DECIMAL(18, 2),
        dp_start_date_sk VARCHAR,
        dp_end_date_sk VARCHAR,
        dp_combo_id VARCHAR,
        dp_bank_id VARCHAR,
        gp_pos_dp_amt DECIMAL(18, 2),
        gp_neg_dp_amt DECIMAL(18, 2),
        nongp_pos_dp_amt DECIMAL(18, 2),
        nongp_neg_dp_amt DECIMAL(18, 2),
        profit_amt DECIMAL(18, 2),
        profit_pct VARCHAR,
        src VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR,
        premise_desc VARCHAR,
        discount_id VARCHAR,
        brand_no VARCHAR,
        suppl_no VARCHAR,
        price_group_1_no DECIMAL(18, 2),
        item_sales_company VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: V_F_NPW_PRICING
-- ============================================================================

SELECT
  npw_pricing_sk,
  site_id,
  project_id,
  item_no,
  pricing_type_sk,
  chain_plan_id,
  customer_no,
  street_deal_no,
  product_type,
  primary_column_value,
  secondary_column_value,
  pricing_name,
  pricing_start_date_sk,
  pricing_end_date_sk,
  pricing_effective_date_sk,
  premise,
  accum_qty,
  accum_uom,
  accum_type,
  order_qty_qualifier,
  reserve_pricing_ind,
  published_pricing,
  price_type,
  frontline_case_price,
  frontline_case_price2,
  frontline_case_price3,
  frontline_case_price4,
  case_discount_amt,
  case_target_price,
  additional_net_amt,
  fob_amt,
  fed_tax_duty_amt,
  state_tax_amt,
  case_purch_allowance_amt,
  laid_in_amt,
  da_start_date_sk,
  da_end_date_sk,
  da_bank_id,
  gp_pos_da_amt,
  gp_neg_da_amt,
  nongp_pos_da_amt,
  nongp_neg_da_amt,
  dp_start_date_sk,
  dp_end_date_sk,
  dp_combo_id,
  dp_bank_id,
  gp_pos_dp_amt,
  gp_neg_dp_amt,
  nongp_pos_dp_amt,
  nongp_neg_dp_amt,
  profit_amt,
  profit_pct,
  src,
  load_dt,
  modified_dt,
  premise_desc,
  discount_id,
  brand_no,
  suppl_no,
  price_group_1_no,
  item_sales_company
FROM SEED();
