-- Raw seed model for SharePoint metadata CSV
-- All columns are VARCHAR because CSV files contain text data
-- Uses Iceberg catalog for SEED model support
MODEL (
  name GENSLER.RAW.SHAREPOINT_METADATA_SEED,
  kind SEED (
    path '../../seeds/sharepoint_metadata.csv'
  ),
  grains [SURVEYID],
  owner 'shreyasikarwartmdcio',
  profiles (SURVEYID, TITLE, MODIFIED, CREATED, AUTHOR, SURVEYSTATUS),
  description 'Seed model ingesting SharePoint survey metadata from CSV file containing survey properties, ownership, status tracking, and business classification fields for enriching survey analytics with external metadata',
  columns (
        id VARCHAR,
        ContentType VARCHAR,
        Title VARCHAR,
        Modified VARCHAR,
        Created VARCHAR,
        Author VARCHAR,
        Editor VARCHAR,
        _UIVersionString VARCHAR,
        Attachments VARCHAR,
        Edit VARCHAR,
        LinkTitleNoMenu VARCHAR,
        LinkTitle VARCHAR,
        DocIcon VARCHAR,
        ItemChildCount VARCHAR,
        FolderChildCount VARCHAR,
        _ComplianceFlags VARCHAR,
        _ComplianceTag VARCHAR,
        _ComplianceTagWrittenTime VARCHAR,
        _ComplianceTagUserId VARCHAR,
        AppAuthor VARCHAR,
        AppEditor VARCHAR,
        ComplianceAssetId VARCHAR,
        SurveyTitle VARCHAR,
        QualtricsProjectName VARCHAR,
        SurveyDisplayName VARCHAR,
        TemplateCategory VARCHAR,
        SurveyType VARCHAR,
        ProjectDescriptionorScope VARCHAR,
        JobNumber VARCHAR,
        ClientIndustry VARCHAR,
        GenslerDesignMgr VARCHAR,
        OverallFee VARCHAR,
        Locationssurveyed VARCHAR,
        Address VARCHAR,
        City VARCHAR,
        State VARCHAR,
        Country VARCHAR,
        Longitude VARCHAR,
        Latitude VARCHAR,
        TotalPolled VARCHAR,
        Template VARCHAR,
        Template_x003a_SurveyID VARCHAR,
        Survey_x0020_Long_x0020_Name VARCHAR,
        SurveyID VARCHAR,
        NDA_x0020_Signed_x003f_ VARCHAR,
        Survey_x0020_Fee VARCHAR,
        Create_x0020_Survey_x0020_Now_x0 VARCHAR,
        EmailTrigger VARCHAR,
        Close_x0020_Date VARCHAR,
        Preview_x0020_Link VARCHAR,
        Live_x0020_Link VARCHAR,
        Online_x0020_Results VARCHAR,
        Respondents VARCHAR,
        Building_x0020_Locations VARCHAR,
        Status VARCHAR,
        Launch_x0020_Date VARCHAR,
        Created_x0020_Date0 VARCHAR,
        Copy_x0020_from_x0020_Previous_x VARCHAR,
        Copy_x0020_from_x0020_Previous_x0 VARCHAR,
        Copy_x0020_from_x0020_Previous_x1 VARCHAR,
        Platform VARCHAR,
        Client_x0020_Contact VARCHAR,
        _ColorTag VARCHAR,
        Count_x0020_Previews VARCHAR,
        Client_x0020_Short_x0020_Name VARCHAR,
        Copy_x0020_from_x0020_Previous_x3 VARCHAR,
        Currency_x0020_Code VARCHAR,
        API_x0020_Log VARCHAR,
        Survey_x0020_Type_x003a_LongName VARCHAR,
        Survey_x0020_Type_x003a_Title VARCHAR,
        PracticeAreaName VARCHAR,
        SectorName VARCHAR,
        PowerBIFolder VARCHAR,
        project_accountant_email VARCHAR,
        design_manager_email VARCHAR,
        Template_x0020_Category_x003a_Re VARCHAR,
        ItemID_OLD VARCHAR,
        project_accountant VARCHAR,
        rowcount VARCHAR,
        Additional_x0020_Units VARCHAR,
        Calculated_Fee VARCHAR,
        Gensler_x0020_Designed VARCHAR,
        _IsRecord VARCHAR
  )
);
