MODEL (
  name lenovo.ldo.devices_seed_model,
  kind SEED (
    path '../seeds/seed_live_devices_status_cdc.csv'
  ),
  columns (
    _id STRING,
    org_id STRING,
    device_id STRING,
    org_device_id STRING,
    subscription_id STRING,
    device_name STRING,
    manufacturer STRING,
    model_type STRING,
    serial_number STRING,
    family STRING,
    enclosure_type STRING,
    category STRING,
    platform STRING,
    os_name STRING,
    device_groups STRING,
    licenses STRING,
    device_labels STRING,
    time_zone STRING,
    status STRING,
    warranty_status STRING,
    warranty_expiration_date BIGINT,
    country_name STRING,
    version STRING,
    _class STRING,
    deleted STRING,
    _op STRING,
    _collection STRING,
    _source_ts_ms BIGINT,
    _db STRING,
    _nilus_load_id STRING,
    _nilus_id STRING,
    network STRING,
    licenses_map STRING,
    device_licensed STRING,
    connection_id STRING,
    connection_timestamp BIGINT,
    last_seen_date BIGINT,
    date_created BIGINT
  ),
  grains (device_id, _nilus_id)
)