MODEL (
  name web_analytics_seeds.V_TD_STORE,
  kind SEED (
    path '../../seeds/v_td_store.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Retail store location reference data',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('v_td_store'),
  columns (
        stdlinxscd VARCHAR,
        tdlinx_store_sk BIGINT,
        stranscd VARCHAR,
        smodchgind VARCHAR,
        sfiledt BIGINT,
        sstatusind VARCHAR,
        sname VARCHAR,
        sno BIGINT,
        sstreetadd VARCHAR,
        scity VARCHAR,
        sst VARCHAR,
        szip BIGINT,
        splacenm VARCHAR,
        sstcd VARCHAR,
        scntcd VARCHAR,
        scntrynm VARCHAR,
        stradeclcd VARCHAR,
        sformatcd VARCHAR,
        snostrcd BIGINT,
        schainind VARCHAR,
        sfiller1 VARCHAR,
        slat DECIMAL(18, 4),
        slong DECIMAL(18, 4),
        slatlongcd VARCHAR,
        sblockid VARCHAR,
        sfiller2 VARCHAR,
        sareacd VARCHAR,
        sphoneno VARCHAR,
        sfiller3 VARCHAR,
        sannvolcd VARCHAR,
        swklyvol BIGINT,
        ssqft BIGINT,
        sftemploy BIGINT,
        snmchkout BIGINT,
        sfiller4 VARCHAR,
        stdlinxocd VARCHAR,
        sownfamcd VARCHAR,
        sownnm VARCHAR,
        sowncity VARCHAR,
        sownst VARCHAR,
        sownstcd VARCHAR,
        sowncntcd VARCHAR,
        sfiller5 VARCHAR,
        stdlinxpcd VARCHAR,
        ssupfamcd VARCHAR,
        ssupnm VARCHAR,
        ssupcity VARCHAR,
        ssupst VARCHAR,
        ssupstcd VARCHAR,
        ssupcntcd VARCHAR,
        sfiller6 VARCHAR,
        stdlinxgcd VARCHAR,
        sgrpnm VARCHAR,
        sfranind VARCHAR,
        sfiller7 VARCHAR,
        sgas VARCHAR,
        shivolcig VARCHAR,
        spharm VARCHAR,
        sliquor VARCHAR,
        swine VARCHAR,
        sbeer VARCHAR,
        sonprem VARCHAR,
        sfoodtype VARCHAR,
        sfuture1 VARCHAR,
        sfuture2 VARCHAR,
        sfuture3 VARCHAR,
        sfiller8 VARCHAR,
        src_desc VARCHAR,
        cstdlinxscd VARCHAR,
        current_ind VARCHAR,
        trade_channel_desc VARCHAR,
        premise_type VARCHAR,
        tdlinx_premise VARCHAR,
        store_volume_desc VARCHAR,
        chain_indicator_desc VARCHAR,
        food_type_desc VARCHAR,
        format_type_desc VARCHAR,
        lat_long_geo_desc VARCHAR,
        no_of_stores_desc VARCHAR,
        store_status_desc VARCHAR,
        transaction_code_desc VARCHAR,
        htdlinxucd VARCHAR,
        hulname VARCHAR,
        td_store_osk BIGINT,
        source_system VARCHAR,
        ecommerce_provider VARCHAR,
        ecommerce_delivery_ind VARCHAR,
        ecommerce_in_store_pickup_ind VARCHAR,
        ecommerce_curbside_pickup_ind VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR
  )
);

-- ============================================================================
-- SEED DATA: V_TD_STORE
-- ============================================================================

SELECT
  stdlinxscd,
  tdlinx_store_sk,
  stranscd,
  smodchgind,
  sfiledt,
  sstatusind,
  sname,
  sno,
  sstreetadd,
  scity,
  sst,
  szip,
  splacenm,
  sstcd,
  scntcd,
  scntrynm,
  stradeclcd,
  sformatcd,
  snostrcd,
  schainind,
  sfiller1,
  slat,
  slong,
  slatlongcd,
  sblockid,
  sfiller2,
  sareacd,
  sphoneno,
  sfiller3,
  sannvolcd,
  swklyvol,
  ssqft,
  sftemploy,
  snmchkout,
  sfiller4,
  stdlinxocd,
  sownfamcd,
  sownnm,
  sowncity,
  sownst,
  sownstcd,
  sowncntcd,
  sfiller5,
  stdlinxpcd,
  ssupfamcd,
  ssupnm,
  ssupcity,
  ssupst,
  ssupstcd,
  ssupcntcd,
  sfiller6,
  stdlinxgcd,
  sgrpnm,
  sfranind,
  sfiller7,
  sgas,
  shivolcig,
  spharm,
  sliquor,
  swine,
  sbeer,
  sonprem,
  sfoodtype,
  sfuture1,
  sfuture2,
  sfuture3,
  sfiller8,
  src_desc,
  cstdlinxscd,
  current_ind,
  trade_channel_desc,
  premise_type,
  tdlinx_premise,
  store_volume_desc,
  chain_indicator_desc,
  food_type_desc,
  format_type_desc,
  lat_long_geo_desc,
  no_of_stores_desc,
  store_status_desc,
  transaction_code_desc,
  htdlinxucd,
  hulname,
  td_store_osk,
  source_system,
  ecommerce_provider,
  ecommerce_delivery_ind,
  ecommerce_in_store_pickup_ind,
  ecommerce_curbside_pickup_ind,
  load_dt,
  modified_dt
FROM SEED();
