MODEL (
  name web_analytics_seeds.V_D_CURR_ITEM,
  kind SEED (
    path '../../seeds/v_d_curr_item.csv'
  ),
  owner 'rohitrajtmdcio',
  description 'Product catalog seed data with item details and classifications',
  tags ('seed', 'reference_data', 'dimension', 'master_data'),
  terms ('v_d_curr_item'),
  columns (
        item_sk BIGINT,
        site BIGINT,
        item_no BIGINT,
        item_desc VARCHAR,
        brand_no VARCHAR,
        brand_name VARCHAR,
        item_size VARCHAR,
        class_cd VARCHAR,
        class_desc VARCHAR,
        category_cd VARCHAR,
        category_desc VARCHAR,
        group_cd VARCHAR,
        group_desc VARCHAR,
        sub_group_cd VARCHAR,
        sub_group_desc VARCHAR,
        division_cd VARCHAR,
        division_desc VARCHAR,
        division_ind VARCHAR,
        company VARCHAR,
        vintage VARCHAR,
        commodity_type VARCHAR,
        suppl_no BIGINT,
        suppl_name VARCHAR,
        sap_suppl_no BIGINT,
        parent_suppl VARCHAR,
        bottles_case BIGINT,
        upc_cd VARCHAR,
        status VARCHAR,
        proof VARCHAR,
        reptg_case_ratio BIGINT,
        case_conv_fact BIGINT,
        domestic_import VARCHAR,
        allocated_item_cd VARCHAR,
        combo_item_flg VARCHAR,
        blitz_item_flg VARCHAR,
        deactivate_dt VARCHAR,
        sfa_include VARCHAR,
        publication_cd VARCHAR,
        item_type_cd VARCHAR,
        grandfather_flg VARCHAR,
        political_buy_flg VARCHAR,
        ordrable_item_cd VARCHAR,
        state_tax_paid_flg VARCHAR,
        flavor_cd VARCHAR,
        flavor_desc VARCHAR,
        region_id VARCHAR,
        region_desc VARCHAR,
        country_of_origin VARCHAR,
        country_name VARCHAR,
        uom VARCHAR,
        unit_cube_volume BIGINT,
        unit_ship_weight VARCHAR,
        hlday_gift_item_flg VARCHAR,
        privat_lbl_item_flg VARCHAR,
        item_closeout_ind VARCHAR,
        liters_bottle VARCHAR,
        corp_item_sk BIGINT,
        auxillary_cd VARCHAR,
        auxillary_desc VARCHAR,
        ca_cd VARCHAR,
        chain_div VARCHAR,
        demand_forecast VARCHAR,
        dual_commission VARCHAR,
        eff_order_cycle VARCHAR,
        financial_class_cd VARCHAR,
        financial_class_desc VARCHAR,
        future_type VARCHAR,
        gallons_per_bottle VARCHAR,
        label_image_file VARCHAR,
        layers_per_pallet VARCHAR,
        cases_per_pallet BIGINT,
        units_per_layer VARCHAR,
        married_cd VARCHAR,
        non_revenue_item VARCHAR,
        product_image_file VARCHAR,
        regular_inv VARCHAR,
        safety_stock VARCHAR,
        scc_cd VARCHAR,
        trans_atlantic_cd VARCHAR,
        div_mgr_name VARCHAR,
        suppl_status_cd VARCHAR,
        suppl_address_1 VARCHAR,
        suppl_address_2 VARCHAR,
        suppl_city VARCHAR,
        suppl_state VARCHAR,
        suppl_zip_cd VARCHAR,
        suppl_zip_ext VARCHAR,
        suppl_county VARCHAR,
        suppl_country VARCHAR,
        suppl_shipping_point VARCHAR,
        alt_brand_no BIGINT,
        alt_brand_type VARCHAR,
        alt_brand_name VARCHAR,
        alt_brand_category_type VARCHAR,
        alt_suppl_no BIGINT,
        alt_suppl_type VARCHAR,
        alt_suppl_name VARCHAR,
        alt_suppl_fiscal_month VARCHAR,
        modified_user VARCHAR,
        effective_from_dt VARCHAR,
        effective_thru_dt VARCHAR,
        load_dt VARCHAR,
        modified_dt VARCHAR,
        current_ind VARCHAR,
        src_desc VARCHAR,
        active_ind VARCHAR,
        pack_upc VARCHAR,
        unit_heigt VARCHAR,
        unit_width VARCHAR,
        unit_legth VARCHAR,
        company_name VARCHAR,
        company_short_name VARCHAR,
        textsearch VARCHAR,
        selling_company_cd VARCHAR,
        frontline_price DECIMAL(18, 2),
        last_posting_date VARCHAR,
        corp_suppl_f_periodstart VARCHAR,
        corp_item_no VARCHAR,
        corp_item_desc VARCHAR,
        corp_item_long_desc VARCHAR,
        corp_item_prod_num VARCHAR,
        corp_item_brand VARCHAR,
        corp_item_brand_name VARCHAR,
        corp_item_suppl VARCHAR,
        corp_item_suppl_name VARCHAR,
        corp_item_prod_cat VARCHAR,
        corp_item_prod_cat_name VARCHAR,
        corp_item_prod_cat_cd VARCHAR,
        corp_item_prod_class VARCHAR,
        corp_item_prod_class_name VARCHAR,
        corp_item_prod_group VARCHAR,
        corp_item_pgrp_name VARCHAR,
        corp_item_prod_subg VARCHAR,
        corp_item_prod_sb_nm VARCHAR,
        corp_item_prod_super_group VARCHAR,
        corp_item_prod_super_group_name VARCHAR,
        corp_item_sup_suppl VARCHAR,
        corp_item_vintage VARCHAR,
        corp_item_flavor_cd VARCHAR,
        corp_item_flavor VARCHAR,
        corp_item_region VARCHAR,
        corp_item_region_name VARCHAR,
        corp_item_appelation VARCHAR,
        corp_item_appel_name VARCHAR,
        corp_item_cnty_orign VARCHAR,
        corp_item_cnty_name VARCHAR,
        corp_item_size VARCHAR,
        corp_item_uom VARCHAR,
        corp_item_wine_gal VARCHAR,
        corp_item_unit_vol BIGINT,
        corp_item_proof VARCHAR,
        corp_item_unit_cbvol BIGINT,
        corp_item_unit_heigt VARCHAR,
        corp_item_unit_width VARCHAR,
        corp_item_unit_legth VARCHAR,
        corp_item_unit_swght VARCHAR,
        corp_item_units_layr VARCHAR,
        corp_item_layer_palt VARCHAR,
        corp_item_bot_pack VARCHAR,
        corp_item_pack_case BIGINT,
        corp_item_bttls_pcas VARCHAR,
        corp_item_upc VARCHAR,
        corp_item_scc VARCHAR,
        corp_item_pack_upc VARCHAR,
        corp_item_rep_cas_rt VARCHAR,
        corp_item_holgft_itm VARCHAR,
        corp_item_copack_itm VARCHAR,
        corp_item_pvtlbl_itm VARCHAR,
        corp_item_lblimg_fil VARCHAR,
        corp_item_prdimg_fil VARCHAR,
        corp_item_rating VARCHAR,
        corp_item_status VARCHAR,
        corp_item_alcoh_perc VARCHAR,
        corp_item_link_code VARCHAR,
        corp_item_crt_date VARCHAR,
        corp_item_crt_time VARCHAR,
        corp_item_crt_user VARCHAR,
        corp_item_upd_date VARCHAR,
        corp_item_upd_time VARCHAR,
        corp_item_upd_user VARCHAR,
        corp_item_ounc_unit VARCHAR,
        corp_item_ntype VARCHAR,
        corp_suppl_name VARCHAR,
        corp_suppl_ss_flag VARCHAR,
        corp_suppl_f_month VARCHAR,
        corp_suppl_vendor VARCHAR,
        corp_suppl_sapvnd_num VARCHAR,
        corp_suppl_mainvnd_num VARCHAR,
        corp_suppl_name2 VARCHAR,
        corp_suppl_address1 VARCHAR,
        corp_suppl_address2 VARCHAR,
        corp_suppl_address3 VARCHAR,
        corp_suppl_city VARCHAR,
        corp_suppl_region VARCHAR,
        corp_suppl_country VARCHAR,
        corp_suppl_zip VARCHAR,
        corp_suppl_zip_ext VARCHAR,
        corp_suppl_phone VARCHAR,
        corp_suppl_fax VARCHAR,
        corp_suppl_edi VARCHAR,
        corp_suppl_status VARCHAR,
        corp_suppl_listed_ind VARCHAR,
        corp_brand_group_flag VARCHAR,
        corp_brand_sup_brand VARCHAR,
        suppl_brand_name VARCHAR,
        rpt_company_code VARCHAR,
        rpt_company_desc VARCHAR,
        rpt_company_short_desc VARCHAR,
        rpt_div_company_code VARCHAR,
        rpt_div_company_desc VARCHAR,
        rpt_div_company_short_desc VARCHAR,
        type_code VARCHAR,
        subtyp_cod VARCHAR,
        reg_subreg VARCHAR,
        apel_villg_cod VARCHAR,
        apel_villg VARCHAR,
        accolades VARCHAR,
        age_statmt VARCHAR,
        mvintg_flg VARCHAR,
        mvintg_dsc VARCHAR,
        kosher_cod VARCHAR,
        kosher VARCHAR,
        materl_cod VARCHAR,
        material VARCHAR,
        packge_dsc VARCHAR,
        bot_height VARCHAR,
        bot_width VARCHAR,
        bot_length VARCHAR,
        bot_type_cod VARCHAR,
        bot_type VARCHAR,
        cas_ppallt VARCHAR,
        palt_dimns VARCHAR,
        palt_height VARCHAR,
        palt_lngth VARCHAR,
        palt_width VARCHAR,
        box_type_cod VARCHAR,
        box_type VARCHAR,
        closur_cod VARCHAR,
        closure VARCHAR,
        color_cod VARCHAR,
        color VARCHAR,
        design_cod VARCHAR,
        designation VARCHAR,
        dom_imp VARCHAR,
        fob_price DECIMAL(18, 2),
        green_code VARCHAR,
        green VARCHAR,
        cert_green VARCHAR,
        cert_agncy VARCHAR,
        green_detl VARCHAR,
        prodcr_cod VARCHAR,
        producer VARCHAR,
        proprietary VARCHAR,
        shelf_life VARCHAR,
        ttb_code VARCHAR,
        sme_descr VARCHAR,
        classif_by VARCHAR,
        request_by VARCHAR,
        reqby_tims VARCHAR,
        approv_by VARCHAR,
        aprby_tims VARCHAR,
        varietal_code VARCHAR,
        varietal VARCHAR,
        reg_subreg_desc VARCHAR,
        type_desc VARCHAR,
        subtyp_desc VARCHAR,
        dom_botl VARCHAR,
        misc_cod VARCHAR,
        sa_code VARCHAR,
        sa_desc VARCHAR,
        rainbow_item_flag VARCHAR,
        rainbow_component_set_flag VARCHAR,
        ssc_item_ind VARCHAR,
        is_deleted VARCHAR,
        purch_item_no VARCHAR,
        nir_ind VARCHAR,
        item_reason_cd VARCHAR,
        item_status_cd VARCHAR,
        brand_manager_no BIGINT,
        brand_manager_name VARCHAR,
        breakage_amt VARCHAR,
        national_service_model VARCHAR,
        national_brand_manager VARCHAR,
        juice_percent VARCHAR,
        pack_cd VARCHAR,
        pack_cd_desc VARCHAR,
        item_planning_cd VARCHAR,
        functional_area VARCHAR,
        availability_check_cd VARCHAR,
        var_sls_unit_allow_ind VARCHAR,
        fact_ninel VARCHAR,
        fact_supratio VARCHAR,
        fact_batf VARCHAR,
        fact_stdcse VARCHAR,
        site_sk BIGINT,
        corp_item_status_desc VARCHAR,
        pim_item_no VARCHAR,
        pim_item_category_cd VARCHAR,
        pim_item_category_desc VARCHAR,
        pim_item_class_cd VARCHAR,
        pim_item_class_desc VARCHAR,
        pim_item_sub_class_cd VARCHAR,
        pim_item_sub_class_desc VARCHAR,
        pim_suppl_item_desc VARCHAR,
        pim_suppl_item_status VARCHAR,
        pim_suppl_item_discontinued_dt VARCHAR,
        pim_brand_effective_dt VARCHAR,
        pim_requested_label_brand VARCHAR,
        pim_replacement_item_effective_dt VARCHAR,
        pim_ready_approval_ind VARCHAR,
        pim_sample_ind VARCHAR,
        pim_tasting_notes BIGINT,
        age_statmt_uom VARCHAR,
        pim_proof_gallons VARCHAR,
        pim_proof_liters VARCHAR,
        sub_material_cd VARCHAR,
        sub_material_desc VARCHAR,
        pim_cork_type VARCHAR,
        corp_item_rating_dt VARCHAR,
        pim_ttb_cola_id_valid_ind VARCHAR,
        marketing_cd VARCHAR,
        marketing_desc VARCHAR,
        pim_collector_special_label VARCHAR,
        pim_gift_component VARCHAR,
        nielsen_upc VARCHAR,
        pim_premise_type VARCHAR,
        pim_special_container VARCHAR,
        pim_dom_imp_desc VARCHAR,
        pim_bottling_packge_country VARCHAR,
        pim_volume_uom_desc BIGINT,
        pim_volume_uom_cd BIGINT,
        corp_item_unit_height_uom VARCHAR,
        corp_item_unit_length_depth_uom VARCHAR,
        corp_item_unit_width_uom VARCHAR,
        corp_item_liter_per_unit VARCHAR,
        corp_item_case_weight_uom BIGINT,
        corp_item_case_height_uom BIGINT,
        corp_item_case_length_depth_uom BIGINT,
        corp_item_case_width_uom BIGINT,
        corp_item_pallet_height_uom VARCHAR,
        corp_item_pallet_length_depth_uom VARCHAR,
        corp_item_pallet_width_uom VARCHAR,
        corp_item_pack_upc_effective_dt VARCHAR,
        corp_item_pack_upc_override VARCHAR,
        corp_item_pack_ean VARCHAR,
        corp_item_pack_ean_effective_dt VARCHAR,
        corp_item_upc_override VARCHAR,
        corp_item_upc_effective_dt VARCHAR,
        corp_item_ean VARCHAR,
        corp_item_ean_effective_dt VARCHAR,
        corp_item_scc_override VARCHAR,
        corp_item_scc_effective_dt VARCHAR,
        pim_reason_cd VARCHAR,
        pim_reason_desc VARCHAR,
        pim_replacement_id_type_cd VARCHAR,
        pim_replacement_id_type_desc VARCHAR,
        pim_item_status_setup VARCHAR,
        pim_replacement_id VARCHAR,
        pim_replaced_by_user_name VARCHAR,
        pim_notes BIGINT,
        pim_supplier_item_comment VARCHAR,
        pim_supplier_item_comment_dt VARCHAR,
        pim_supplier_item_comment_desc VARCHAR,
        pim_workflow_item_status VARCHAR,
        pim_workflow_item_timestamp VARCHAR,
        pim_workflow_item_user_name VARCHAR,
        supplierid VARCHAR,
        supplier VARCHAR,
        pim_standard_case_conversion BIGINT,
        pim_batf_case_conversion BIGINT,
        pim_9l_case_conversion BIGINT,
        pim_item_juice_perc VARCHAR,
        federal_beverage_tax_cd VARCHAR,
        federal_beverage_tax_cd_desc VARCHAR,
        pim_sizevolume BIGINT,
        pim_product_num VARCHAR,
        pim_review_source_1 VARCHAR,
        pim_rating_1 VARCHAR,
        pim_review_1 VARCHAR,
        pim_rating_1_dt VARCHAR,
        pim_reviewer_1 VARCHAR,
        pim_review_source_2 VARCHAR,
        pim_rating_2 VARCHAR,
        pim_review_2 VARCHAR,
        pim_rating_2_dt VARCHAR,
        pim_reviewer_2 VARCHAR,
        pim_review_source_3 VARCHAR,
        pim_rating_3 VARCHAR,
        pim_review_3 VARCHAR,
        pim_rating_3_dt VARCHAR,
        pim_reviewer_3 VARCHAR,
        pim_review_source_4 VARCHAR,
        pim_rating_4 VARCHAR,
        pim_review_4 VARCHAR,
        pim_rating_4_dt VARCHAR,
        pim_reviewer_4 VARCHAR,
        pim_producer_desc VARCHAR,
        pim_varieta_desc VARCHAR,
        pim_country_desc VARCHAR,
        pim_region_desc VARCHAR,
        pim_appellation_desc VARCHAR,
        pim_romantic_desc VARCHAR,
        corp_item_unit_weight VARCHAR,
        corp_item_unit_weight_uom VARCHAR,
        corp_item_pallet_weight VARCHAR,
        corp_item_pallet_weight_uom VARCHAR,
        pim_comment_subject VARCHAR,
        pim_vintage_brand VARCHAR,
        corp_item_holiday_gift VARCHAR,
        corp_item_outer_pack VARCHAR,
        pim_client_request VARCHAR,
        pim_region_cd VARCHAR,
        pim_sub_region_cd VARCHAR,
        pim_appellation_cd VARCHAR,
        pim_apel_villg_cd VARCHAR,
        pim_product_label_brand_cd VARCHAR,
        pim_product_label_brand_desc VARCHAR,
        pim_product_name VARCHAR,
        pim_product_material_cd VARCHAR,
        pim_product_material_desc VARCHAR,
        pim_product_sub_material_cd VARCHAR,
        pim_product_sub_material_desc VARCHAR,
        pim_product_varietal_cd VARCHAR,
        pim_product_varietal VARCHAR,
        pim_product_flavor_cd VARCHAR,
        pim_product_flavor VARCHAR,
        pim_product_proof VARCHAR,
        pim_product_age_statement VARCHAR,
        pim_product_age_statement_uom VARCHAR,
        pim_product_geo_designation_cd VARCHAR,
        pim_product_geo_designation_desc VARCHAR,
        pim_product_color_cd VARCHAR,
        pim_product_color VARCHAR,
        pim_product_creation_dt VARCHAR,
        pim_product_modified_dt VARCHAR,
        corp_item_sup_suppl_name VARCHAR,
        corp_item_sup_suppl_f_month VARCHAR,
        pim_item_long_desc VARCHAR,
        pim_suppl_name VARCHAR,
        pim_cicategory VARCHAR,
        pim_region VARCHAR,
        pim_country_of_origin VARCHAR,
        pim_sub_region_desc VARCHAR,
        pim_citype VARCHAR,
        pim_cisubtype VARCHAR,
        pim_root_node BIGINT,
        pim_root VARCHAR,
        pim_type_cd VARCHAR,
        pim_type_desc VARCHAR,
        pim_sub_type_cd VARCHAR,
        pim_sub_type_desc VARCHAR,
        pim_cannabinoids_type VARCHAR,
        pim_total_potency VARCHAR,
        pim_dosage VARCHAR,
        pim_fragrance VARCHAR,
        pim_cultivation VARCHAR,
        pim_terpenes VARCHAR,
        pim_anatomy VARCHAR,
        pim_gender VARCHAR,
        pim_count VARCHAR,
        pim_brand_type VARCHAR,
        pim_species VARCHAR,
        pim_strain VARCHAR,
        pim_extract_type VARCHAR,
        corp_suppl_zip_global VARCHAR,
        corp_suppl_zip_ext_global VARCHAR,
        pim_producer_cd VARCHAR,
        corp_item_size_long_desc VARCHAR,
        pim_item_varietal_cd VARCHAR,
        pim_item_varietal_desc VARCHAR,
        pim_item_upc_gtin_12 VARCHAR,
        pim_item_inner_pack_upc_gtin_12 VARCHAR,
        pim_item_is_deleted VARCHAR,
        u_lifecycle_stage VARCHAR,
        link_item_creation_dt VARCHAR,
        price_group_1_no DECIMAL(18, 2),
        price_group_1_name DECIMAL(18, 2),
        price_group_2_no DECIMAL(18, 2),
        price_group_2_name DECIMAL(18, 2),
        item_sold_by_cases_ind BIGINT,
        item_premise_type_sold_at VARCHAR,
        item_portal_visibility VARCHAR,
        sugar_taxable_ind VARCHAR,
        california_item_redemption VARCHAR,
        california_redemption_amt VARCHAR,
        item_updated VARCHAR,
        item_separate_pricing_ind VARCHAR,
        item_reserve_flag VARCHAR,
        cost_code DECIMAL(18, 2),
        item_sales_company VARCHAR,
        item_service_level_group VARCHAR,
        brand_manager_email VARCHAR,
        pim_service_category VARCHAR,
        otc_portal_community_visibility_cd VARCHAR,
        publish_item_ind VARCHAR,
        item_reduction_code VARCHAR,
        item_reduction_desc VARCHAR,
        otc_portal_community_visibility_desc VARCHAR,
        publish_item_desc VARCHAR,
        commodity_type_desc VARCHAR,
        ready_to_drink_ind VARCHAR,
        rtd_manual_override_ind VARCHAR,
        item_repackage_ind VARCHAR,
        value_added_packaging_ind VARCHAR,
        item_sampled_ind VARCHAR,
        upc_ean_check_digit VARCHAR,
        item_active_reason_desc VARCHAR,
        item_status_reason_desc VARCHAR,
        excise_tax_rate VARCHAR,
        item_innovation_desc VARCHAR,
        item_linked_to_site_dt VARCHAR,
        laid_in_cost_per_case DECIMAL(18, 2),
        supplier_item_number VARCHAR,
        mixed_label_brand_flag VARCHAR,
        corp_item_modified_dt VARCHAR,
        organic_desc VARCHAR,
        biodynamic_desc VARCHAR,
        sustainable_desc VARCHAR,
        green_other_desc VARCHAR,
        kosher_type_desc VARCHAR,
        brand_ownership_type_desc VARCHAR,
        nutritional_information_desc VARCHAR,
        trade_practices_desc VARCHAR,
        wine_specific_desc VARCHAR,
        bordeaux_wine_classifications_desc VARCHAR,
        beer_spirits_specific_desc VARCHAR,
        supersession_ultimate_corp_item_no VARCHAR,
        supersession_corp_item_seq_level VARCHAR,
        supersession_type_desc VARCHAR,
        national_service_model_sub_division VARCHAR,
        managing_director VARCHAR,
        regional_manager_east VARCHAR,
        regional_manager_central VARCHAR,
        regional_manager_west VARCHAR,
        avg_price_per_750_bottle_amt DECIMAL(18, 2),
        item_tax_exempt_cd VARCHAR,
        item_type_desc VARCHAR,
        item_otc_updated_dt VARCHAR,
        pim_item_inner_pack_scc VARCHAR,
        formal_planning_scope_ind VARCHAR,
        brand_preferred_case_conversion BIGINT,
        superseded_corp_item_list VARCHAR,
        pod_id VARCHAR,
        pod_name VARCHAR,
        vip_supplier_item_code VARCHAR,
        source_system VARCHAR,
        selling_company_name VARCHAR,
        item_status_descr VARCHAR,
        price_tiers DECIMAL(18, 2)
  )
);

-- ============================================================================
-- SEED DATA: V_D_CURR_ITEM
-- ============================================================================

SELECT
  item_sk,
  site,
  item_no,
  item_desc,
  brand_no,
  brand_name,
  item_size,
  class_cd,
  class_desc,
  category_cd,
  category_desc,
  group_cd,
  group_desc,
  sub_group_cd,
  sub_group_desc,
  division_cd,
  division_desc,
  division_ind,
  company,
  vintage,
  commodity_type,
  suppl_no,
  suppl_name,
  sap_suppl_no,
  parent_suppl,
  bottles_case,
  upc_cd,
  status,
  proof,
  reptg_case_ratio,
  case_conv_fact,
  domestic_import,
  allocated_item_cd,
  combo_item_flg,
  blitz_item_flg,
  deactivate_dt,
  sfa_include,
  publication_cd,
  item_type_cd,
  grandfather_flg,
  political_buy_flg,
  ordrable_item_cd,
  state_tax_paid_flg,
  flavor_cd,
  flavor_desc,
  region_id,
  region_desc,
  country_of_origin,
  country_name,
  uom,
  unit_cube_volume,
  unit_ship_weight,
  hlday_gift_item_flg,
  privat_lbl_item_flg,
  item_closeout_ind,
  liters_bottle,
  corp_item_sk,
  auxillary_cd,
  auxillary_desc,
  ca_cd,
  chain_div,
  demand_forecast,
  dual_commission,
  eff_order_cycle,
  financial_class_cd,
  financial_class_desc,
  future_type,
  gallons_per_bottle,
  label_image_file,
  layers_per_pallet,
  cases_per_pallet,
  units_per_layer,
  married_cd,
  non_revenue_item,
  product_image_file,
  regular_inv,
  safety_stock,
  scc_cd,
  trans_atlantic_cd,
  div_mgr_name,
  suppl_status_cd,
  suppl_address_1,
  suppl_address_2,
  suppl_city,
  suppl_state,
  suppl_zip_cd,
  suppl_zip_ext,
  suppl_county,
  suppl_country,
  suppl_shipping_point,
  alt_brand_no,
  alt_brand_type,
  alt_brand_name,
  alt_brand_category_type,
  alt_suppl_no,
  alt_suppl_type,
  alt_suppl_name,
  alt_suppl_fiscal_month,
  modified_user,
  effective_from_dt,
  effective_thru_dt,
  load_dt,
  modified_dt,
  current_ind,
  src_desc,
  active_ind,
  pack_upc,
  unit_heigt,
  unit_width,
  unit_legth,
  company_name,
  company_short_name,
  textsearch,
  selling_company_cd,
  frontline_price,
  last_posting_date,
  corp_suppl_f_periodstart,
  corp_item_no,
  corp_item_desc,
  corp_item_long_desc,
  corp_item_prod_num,
  corp_item_brand,
  corp_item_brand_name,
  corp_item_suppl,
  corp_item_suppl_name,
  corp_item_prod_cat,
  corp_item_prod_cat_name,
  corp_item_prod_cat_cd,
  corp_item_prod_class,
  corp_item_prod_class_name,
  corp_item_prod_group,
  corp_item_pgrp_name,
  corp_item_prod_subg,
  corp_item_prod_sb_nm,
  corp_item_prod_super_group,
  corp_item_prod_super_group_name,
  corp_item_sup_suppl,
  corp_item_vintage,
  corp_item_flavor_cd,
  corp_item_flavor,
  corp_item_region,
  corp_item_region_name,
  corp_item_appelation,
  corp_item_appel_name,
  corp_item_cnty_orign,
  corp_item_cnty_name,
  corp_item_size,
  corp_item_uom,
  corp_item_wine_gal,
  corp_item_unit_vol,
  corp_item_proof,
  corp_item_unit_cbvol,
  corp_item_unit_heigt,
  corp_item_unit_width,
  corp_item_unit_legth,
  corp_item_unit_swght,
  corp_item_units_layr,
  corp_item_layer_palt,
  corp_item_bot_pack,
  corp_item_pack_case,
  corp_item_bttls_pcas,
  corp_item_upc,
  corp_item_scc,
  corp_item_pack_upc,
  corp_item_rep_cas_rt,
  corp_item_holgft_itm,
  corp_item_copack_itm,
  corp_item_pvtlbl_itm,
  corp_item_lblimg_fil,
  corp_item_prdimg_fil,
  corp_item_rating,
  corp_item_status,
  corp_item_alcoh_perc,
  corp_item_link_code,
  corp_item_crt_date,
  corp_item_crt_time,
  corp_item_crt_user,
  corp_item_upd_date,
  corp_item_upd_time,
  corp_item_upd_user,
  corp_item_ounc_unit,
  corp_item_ntype,
  corp_suppl_name,
  corp_suppl_ss_flag,
  corp_suppl_f_month,
  corp_suppl_vendor,
  corp_suppl_sapvnd_num,
  corp_suppl_mainvnd_num,
  corp_suppl_name2,
  corp_suppl_address1,
  corp_suppl_address2,
  corp_suppl_address3,
  corp_suppl_city,
  corp_suppl_region,
  corp_suppl_country,
  corp_suppl_zip,
  corp_suppl_zip_ext,
  corp_suppl_phone,
  corp_suppl_fax,
  corp_suppl_edi,
  corp_suppl_status,
  corp_suppl_listed_ind,
  corp_brand_group_flag,
  corp_brand_sup_brand,
  suppl_brand_name,
  rpt_company_code,
  rpt_company_desc,
  rpt_company_short_desc,
  rpt_div_company_code,
  rpt_div_company_desc,
  rpt_div_company_short_desc,
  type_code,
  subtyp_cod,
  reg_subreg,
  apel_villg_cod,
  apel_villg,
  accolades,
  age_statmt,
  mvintg_flg,
  mvintg_dsc,
  kosher_cod,
  kosher,
  materl_cod,
  material,
  packge_dsc,
  bot_height,
  bot_width,
  bot_length,
  bot_type_cod,
  bot_type,
  cas_ppallt,
  palt_dimns,
  palt_height,
  palt_lngth,
  palt_width,
  box_type_cod,
  box_type,
  closur_cod,
  closure,
  color_cod,
  color,
  design_cod,
  designation,
  dom_imp,
  fob_price,
  green_code,
  green,
  cert_green,
  cert_agncy,
  green_detl,
  prodcr_cod,
  producer,
  proprietary,
  shelf_life,
  ttb_code,
  sme_descr,
  classif_by,
  request_by,
  reqby_tims,
  approv_by,
  aprby_tims,
  varietal_code,
  varietal,
  reg_subreg_desc,
  type_desc,
  subtyp_desc,
  dom_botl,
  misc_cod,
  sa_code,
  sa_desc,
  rainbow_item_flag,
  rainbow_component_set_flag,
  ssc_item_ind,
  is_deleted,
  purch_item_no,
  nir_ind,
  item_reason_cd,
  item_status_cd,
  brand_manager_no,
  brand_manager_name,
  breakage_amt,
  national_service_model,
  national_brand_manager,
  juice_percent,
  pack_cd,
  pack_cd_desc,
  item_planning_cd,
  functional_area,
  availability_check_cd,
  var_sls_unit_allow_ind,
  fact_ninel,
  fact_supratio,
  fact_batf,
  fact_stdcse,
  site_sk,
  corp_item_status_desc,
  pim_item_no,
  pim_item_category_cd,
  pim_item_category_desc,
  pim_item_class_cd,
  pim_item_class_desc,
  pim_item_sub_class_cd,
  pim_item_sub_class_desc,
  pim_suppl_item_desc,
  pim_suppl_item_status,
  pim_suppl_item_discontinued_dt,
  pim_brand_effective_dt,
  pim_requested_label_brand,
  pim_replacement_item_effective_dt,
  pim_ready_approval_ind,
  pim_sample_ind,
  pim_tasting_notes,
  age_statmt_uom,
  pim_proof_gallons,
  pim_proof_liters,
  sub_material_cd,
  sub_material_desc,
  pim_cork_type,
  corp_item_rating_dt,
  pim_ttb_cola_id_valid_ind,
  marketing_cd,
  marketing_desc,
  pim_collector_special_label,
  pim_gift_component,
  nielsen_upc,
  pim_premise_type,
  pim_special_container,
  pim_dom_imp_desc,
  pim_bottling_packge_country,
  pim_volume_uom_desc,
  pim_volume_uom_cd,
  corp_item_unit_height_uom,
  corp_item_unit_length_depth_uom,
  corp_item_unit_width_uom,
  corp_item_liter_per_unit,
  corp_item_case_weight_uom,
  corp_item_case_height_uom,
  corp_item_case_length_depth_uom,
  corp_item_case_width_uom,
  corp_item_pallet_height_uom,
  corp_item_pallet_length_depth_uom,
  corp_item_pallet_width_uom,
  corp_item_pack_upc_effective_dt,
  corp_item_pack_upc_override,
  corp_item_pack_ean,
  corp_item_pack_ean_effective_dt,
  corp_item_upc_override,
  corp_item_upc_effective_dt,
  corp_item_ean,
  corp_item_ean_effective_dt,
  corp_item_scc_override,
  corp_item_scc_effective_dt,
  pim_reason_cd,
  pim_reason_desc,
  pim_replacement_id_type_cd,
  pim_replacement_id_type_desc,
  pim_item_status_setup,
  pim_replacement_id,
  pim_replaced_by_user_name,
  pim_notes,
  pim_supplier_item_comment,
  pim_supplier_item_comment_dt,
  pim_supplier_item_comment_desc,
  pim_workflow_item_status,
  pim_workflow_item_timestamp,
  pim_workflow_item_user_name,
  supplierid,
  supplier,
  pim_standard_case_conversion,
  pim_batf_case_conversion,
  pim_9l_case_conversion,
  pim_item_juice_perc,
  federal_beverage_tax_cd,
  federal_beverage_tax_cd_desc,
  pim_sizevolume,
  pim_product_num,
  pim_review_source_1,
  pim_rating_1,
  pim_review_1,
  pim_rating_1_dt,
  pim_reviewer_1,
  pim_review_source_2,
  pim_rating_2,
  pim_review_2,
  pim_rating_2_dt,
  pim_reviewer_2,
  pim_review_source_3,
  pim_rating_3,
  pim_review_3,
  pim_rating_3_dt,
  pim_reviewer_3,
  pim_review_source_4,
  pim_rating_4,
  pim_review_4,
  pim_rating_4_dt,
  pim_reviewer_4,
  pim_producer_desc,
  pim_varieta_desc,
  pim_country_desc,
  pim_region_desc,
  pim_appellation_desc,
  pim_romantic_desc,
  corp_item_unit_weight,
  corp_item_unit_weight_uom,
  corp_item_pallet_weight,
  corp_item_pallet_weight_uom,
  pim_comment_subject,
  pim_vintage_brand,
  corp_item_holiday_gift,
  corp_item_outer_pack,
  pim_client_request,
  pim_region_cd,
  pim_sub_region_cd,
  pim_appellation_cd,
  pim_apel_villg_cd,
  pim_product_label_brand_cd,
  pim_product_label_brand_desc,
  pim_product_name,
  pim_product_material_cd,
  pim_product_material_desc,
  pim_product_sub_material_cd,
  pim_product_sub_material_desc,
  pim_product_varietal_cd,
  pim_product_varietal,
  pim_product_flavor_cd,
  pim_product_flavor,
  pim_product_proof,
  pim_product_age_statement,
  pim_product_age_statement_uom,
  pim_product_geo_designation_cd,
  pim_product_geo_designation_desc,
  pim_product_color_cd,
  pim_product_color,
  pim_product_creation_dt,
  pim_product_modified_dt,
  corp_item_sup_suppl_name,
  corp_item_sup_suppl_f_month,
  pim_item_long_desc,
  pim_suppl_name,
  pim_cicategory,
  pim_region,
  pim_country_of_origin,
  pim_sub_region_desc,
  pim_citype,
  pim_cisubtype,
  pim_root_node,
  pim_root,
  pim_type_cd,
  pim_type_desc,
  pim_sub_type_cd,
  pim_sub_type_desc,
  pim_cannabinoids_type,
  pim_total_potency,
  pim_dosage,
  pim_fragrance,
  pim_cultivation,
  pim_terpenes,
  pim_anatomy,
  pim_gender,
  pim_count,
  pim_brand_type,
  pim_species,
  pim_strain,
  pim_extract_type,
  corp_suppl_zip_global,
  corp_suppl_zip_ext_global,
  pim_producer_cd,
  corp_item_size_long_desc,
  pim_item_varietal_cd,
  pim_item_varietal_desc,
  pim_item_upc_gtin_12,
  pim_item_inner_pack_upc_gtin_12,
  pim_item_is_deleted,
  u_lifecycle_stage,
  link_item_creation_dt,
  price_group_1_no,
  price_group_1_name,
  price_group_2_no,
  price_group_2_name,
  item_sold_by_cases_ind,
  item_premise_type_sold_at,
  item_portal_visibility,
  sugar_taxable_ind,
  california_item_redemption,
  california_redemption_amt,
  item_updated,
  item_separate_pricing_ind,
  item_reserve_flag,
  cost_code,
  item_sales_company,
  item_service_level_group,
  brand_manager_email,
  pim_service_category,
  otc_portal_community_visibility_cd,
  publish_item_ind,
  item_reduction_code,
  item_reduction_desc,
  otc_portal_community_visibility_desc,
  publish_item_desc,
  commodity_type_desc,
  ready_to_drink_ind,
  rtd_manual_override_ind,
  item_repackage_ind,
  value_added_packaging_ind,
  item_sampled_ind,
  upc_ean_check_digit,
  item_active_reason_desc,
  item_status_reason_desc,
  excise_tax_rate,
  item_innovation_desc,
  item_linked_to_site_dt,
  laid_in_cost_per_case,
  supplier_item_number,
  mixed_label_brand_flag,
  corp_item_modified_dt,
  organic_desc,
  biodynamic_desc,
  sustainable_desc,
  green_other_desc,
  kosher_type_desc,
  brand_ownership_type_desc,
  nutritional_information_desc,
  trade_practices_desc,
  wine_specific_desc,
  bordeaux_wine_classifications_desc,
  beer_spirits_specific_desc,
  supersession_ultimate_corp_item_no,
  supersession_corp_item_seq_level,
  supersession_type_desc,
  national_service_model_sub_division,
  managing_director,
  regional_manager_east,
  regional_manager_central,
  regional_manager_west,
  avg_price_per_750_bottle_amt,
  item_tax_exempt_cd,
  item_type_desc,
  item_otc_updated_dt,
  pim_item_inner_pack_scc,
  formal_planning_scope_ind,
  brand_preferred_case_conversion,
  superseded_corp_item_list,
  pod_id,
  pod_name,
  vip_supplier_item_code,
  source_system,
  selling_company_name,
  item_status_descr,
  price_tiers
FROM SEED();
