-- Product category performance analysis with trend metrics and insights
-- Provides category-level analytics for merchandising strategy and inventory planning
MODEL (
  name gold_v1.category_performance_analysis,
  kind FULL,
  cron '@daily',
  grains (category, region_id),
  tags ('gold', 'analytics', 'category', 'performance', 'merchandising'),
  terms ('analytics.category_performance', 'merchandising.category_metrics'),
  description 'Category performance analysis model delivering comprehensive insights into product category sales trends, revenue contribution, customer penetration, and inventory health for merchandising decisions and category management',
  column_descriptions (
    analysis_date = 'Date of analysis snapshot - stored as TIMESTAMP',
    category = 'Product category name (aggregation grain)',
    region_id = 'Foreign key to regions table - geographic region (aggregation grain)',
    region_name = 'Name of the region',
    total_products = 'Total number of products in this category',
    active_products = 'Number of products with sales in last 90 days',
    best_seller_products = 'Number of products classified as Best Sellers',
    good_performer_products = 'Number of products classified as Good Performers',
    slow_mover_products = 'Number of products classified as Slow Movers',
    declining_products = 'Number of products classified as Declining (good history, no recent sales)',
    stale_products = 'Number of products classified as Stale (no sales in 90+ days)',
    at_risk_products = 'Number of products classified as At Risk',
    new_products = 'Number of products classified as New (no sales yet)',
    total_customers = 'Total unique customers who purchased from this category',
    total_orders = 'Total number of orders containing category products',
    total_quantity_sold = 'Total quantity of items sold across category',
    total_revenue = 'Total revenue generated by category in USD',
    category_revenue_share = 'Percentage of total company revenue from this category',
    avg_product_revenue = 'Average revenue per product in category',
    avg_order_value = 'Average order value for category purchases',
    avg_items_per_order = 'Average quantity per order',
    revenue_per_customer = 'Average lifetime revenue per customer in category',
    orders_per_customer = 'Average number of orders per customer',
    inventory_turnover_rate = 'Average turnover rate across category products',
    total_revenue_last_30d = 'Revenue in last 30 days',
    total_revenue_last_90d = 'Revenue in last 90 days',
    revenue_growth_30d_pct = 'Revenue growth percentage (last 30d vs previous 30d)',
    order_growth_30d_pct = 'Order growth percentage (last 30d vs previous 30d)',
    top_product_id = 'Product ID with highest revenue in category',
    top_product_name = 'Name of top revenue product',
    top_product_revenue = 'Revenue from top product',
    top_product_revenue_share = 'Percentage of category revenue from top product',
    category_health_score = 'Overall category health score (0-100)',
    category_tier = 'Category classification (Star, Growth, Mature, Declining)',
    recommended_action = 'Strategic recommendation for category management'
  ),
  column_tags (
    analysis_date = ('temporal', 'date'),
    category = ('dimension', 'label', 'grain'),
    region_id = ('foreign_key', 'reference', 'grain'),
    region_name = ('dimension', 'label'),
    total_products = ('measure', 'metric', 'count'),
    active_products = ('measure', 'metric', 'count'),
    best_seller_products = ('measure', 'metric', 'count'),
    good_performer_products = ('measure', 'metric', 'count'),
    slow_mover_products = ('measure', 'metric', 'count'),
    declining_products = ('measure', 'metric', 'count'),
    stale_products = ('measure', 'metric', 'count'),
    at_risk_products = ('measure', 'metric', 'count'),
    new_products = ('measure', 'metric', 'count'),
    total_customers = ('measure', 'metric', 'count'),
    total_orders = ('measure', 'metric', 'count'),
    total_quantity_sold = ('measure', 'metric', 'sum'),
    total_revenue = ('measure', 'financial', 'metric'),
    category_revenue_share = ('measure', 'metric', 'percentage'),
    avg_product_revenue = ('measure', 'financial', 'average'),
    avg_order_value = ('measure', 'financial', 'average'),
    avg_items_per_order = ('measure', 'metric', 'average'),
    revenue_per_customer = ('measure', 'financial', 'average'),
    orders_per_customer = ('measure', 'metric', 'average'),
    inventory_turnover_rate = ('measure', 'metric', 'ratio'),
    total_revenue_last_30d = ('measure', 'financial', 'metric'),
    total_revenue_last_90d = ('measure', 'financial', 'metric'),
    revenue_growth_30d_pct = ('measure', 'metric', 'percentage', 'growth'),
    order_growth_30d_pct = ('measure', 'metric', 'percentage', 'growth'),
    top_product_id = ('dimension', 'identifier'),
    top_product_name = ('dimension', 'label'),
    top_product_revenue = ('measure', 'financial', 'metric'),
    top_product_revenue_share = ('measure', 'metric', 'percentage'),
    category_health_score = ('measure', 'metric', 'score'),
    category_tier = ('dimension', 'classification', 'label'),
    recommended_action = ('dimension', 'label', 'recommendation')
  ),
  column_terms (
    category = ('product.category', 'classification.category'),
    total_revenue = ('category.revenue', 'sales.category_revenue'),
    category_revenue_share = ('analytics.revenue_share', 'category.contribution'),
    category_health_score = ('analytics.health_score', 'category.performance_index'),
    category_tier = ('category.tier', 'classification.category_performance')
  ),
  -- assertions (
  --   unique_combination_of_columns(columns := (category, region_id)),
  --   not_null(columns := (analysis_date, category, region_id, region_name)),
  --   forall(criteria := (
  --     total_products >= 0,
  --     active_products >= 0,
  --     total_customers >= 0,
  --     total_orders >= 0,
  --     total_quantity_sold >= 0,
  --     total_revenue >= 0,
  --     active_products <= total_products,
  --     best_seller_products + good_performer_products + slow_mover_products + declining_products + stale_products + at_risk_products + new_products <= total_products
  --   )),
  --   accepted_range(column := category_revenue_share, min_v := 0, max_v := 1),
  --   accepted_range(column := category_health_score, min_v := 0, max_v := 100),
  --   accepted_values(column := category_tier, is_in := ('Star', 'Growth', 'Mature', 'Declining', 'Emerging'))
  -- ),
  profiles (category, region_name, total_revenue, category_tier, category_health_score)
);

WITH category_product_metrics AS (
  -- Aggregate product-level metrics by category and region
  SELECT
    pp.category,
    cp.region_id,
    cp.region_name,
    COUNT(DISTINCT pp.product_id) AS total_products,
    COUNT(DISTINCT CASE WHEN pp.days_since_last_sale <= 90 THEN pp.product_id END) AS active_products,
    COUNT(DISTINCT CASE WHEN pp.product_performance = 'Best Seller' THEN pp.product_id END) AS best_seller_products,
    COUNT(DISTINCT CASE WHEN pp.product_performance = 'Good Performer' THEN pp.product_id END) AS good_performer_products,
    COUNT(DISTINCT CASE WHEN pp.product_performance = 'Slow Mover' THEN pp.product_id END) AS slow_mover_products,
    COUNT(DISTINCT CASE WHEN pp.product_performance = 'Declining' THEN pp.product_id END) AS declining_products,
    COUNT(DISTINCT CASE WHEN pp.product_performance = 'Stale' THEN pp.product_id END) AS stale_products,
    COUNT(DISTINCT CASE WHEN pp.product_performance = 'At Risk' THEN pp.product_id END) AS at_risk_products,
    COUNT(DISTINCT CASE WHEN pp.product_performance = 'New' THEN pp.product_id END) AS new_products,
    AVG(pp.inventory_turnover_rate) AS avg_inventory_turnover
  FROM silver_v1.dim_product_profile AS pp
  CROSS JOIN (
    SELECT DISTINCT region_id, region_name 
    FROM silver_v1.dim_customer_profile
  ) AS cp
  GROUP BY pp.category, cp.region_id, cp.region_name
),
category_sales_metrics AS (
  -- Aggregate sales metrics from daily sales
  SELECT
    pp.category,
    ds.region_id,
    COUNT(DISTINCT ds.customer_id) AS total_customers,
    COUNT(DISTINCT ds.order_date || '-' || ds.customer_id || '-' || ds.product_id) AS total_orders,
    SUM(ds.total_items_sold) AS total_quantity_sold,
    SUM(ds.total_revenue) AS total_revenue
  FROM silver_v1.fct_daily_sales AS ds
  INNER JOIN silver_v1.dim_product_profile AS pp
    ON ds.product_id = pp.product_id
  GROUP BY pp.category, ds.region_id
),
category_recent_revenue AS (
  -- Calculate revenue for recent periods
  SELECT
    pp.category,
    ds.region_id,
    SUM(CASE WHEN ds.order_date >= CURRENT_DATE - INTERVAL '30 days' THEN ds.total_revenue ELSE 0 END) AS revenue_last_30d,
    SUM(CASE WHEN ds.order_date >= CURRENT_DATE - INTERVAL '90 days' THEN ds.total_revenue ELSE 0 END) AS revenue_last_90d,
    SUM(CASE WHEN ds.order_date >= CURRENT_DATE - INTERVAL '30 days' 
         AND ds.order_date < CURRENT_DATE 
         THEN 1 ELSE 0 END) AS orders_last_30d,
    SUM(CASE WHEN ds.order_date >= CURRENT_DATE - INTERVAL '60 days' 
         AND ds.order_date < CURRENT_DATE - INTERVAL '30 days' 
         THEN ds.total_revenue ELSE 0 END) AS revenue_prev_30d,
    SUM(CASE WHEN ds.order_date >= CURRENT_DATE - INTERVAL '60 days' 
         AND ds.order_date < CURRENT_DATE - INTERVAL '30 days' 
         THEN 1 ELSE 0 END) AS orders_prev_30d
  FROM silver_v1.fct_daily_sales AS ds
  INNER JOIN silver_v1.dim_product_profile AS pp
    ON ds.product_id = pp.product_id
  GROUP BY pp.category, ds.region_id
),
top_products_by_category AS (
  -- Identify top revenue product per category-region
  SELECT
    pp.category,
    ds.region_id,
    pp.product_id,
    pp.product_name,
    SUM(ds.total_revenue) AS product_revenue,
    ROW_NUMBER() OVER (
      PARTITION BY pp.category, ds.region_id 
      ORDER BY SUM(ds.total_revenue) DESC
    ) AS revenue_rank
  FROM silver_v1.fct_daily_sales AS ds
  INNER JOIN silver_v1.dim_product_profile AS pp
    ON ds.product_id = pp.product_id
  GROUP BY pp.category, ds.region_id, pp.product_id, pp.product_name
),
total_revenue_calc AS (
  -- Calculate total revenue across all categories for share calculation
  SELECT
    ds.region_id,
    SUM(ds.total_revenue) AS total_company_revenue
  FROM silver_v1.fct_daily_sales AS ds
  GROUP BY ds.region_id
)
SELECT
  CAST(CURRENT_DATE AS TIMESTAMP) AS analysis_date,
  cpm.category,
  cpm.region_id,
  cpm.region_name,
  
  -- Product Inventory Metrics
  cpm.total_products,
  cpm.active_products,
  cpm.best_seller_products,
  cpm.good_performer_products,
  cpm.slow_mover_products,
  cpm.declining_products,
  cpm.stale_products,
  cpm.at_risk_products,
  cpm.new_products,
  
  -- Sales Metrics
  COALESCE(csm.total_customers, 0) AS total_customers,
  COALESCE(csm.total_orders, 0) AS total_orders,
  COALESCE(csm.total_quantity_sold, 0) AS total_quantity_sold,
  ROUND(COALESCE(csm.total_revenue, 0), 2) AS total_revenue,
  
  -- Revenue Share
  ROUND(
    COALESCE(csm.total_revenue, 0)::NUMERIC / NULLIF(trc.total_company_revenue, 0),
    4
  ) AS category_revenue_share,
  
  -- Averages
  ROUND(COALESCE(csm.total_revenue, 0) / NULLIF(cpm.total_products, 0), 2) AS avg_product_revenue,
  ROUND(COALESCE(csm.total_revenue, 0) / NULLIF(csm.total_orders, 0), 2) AS avg_order_value,
  ROUND(COALESCE(csm.total_quantity_sold, 0)::NUMERIC / NULLIF(csm.total_orders, 0), 2) AS avg_items_per_order,
  ROUND(COALESCE(csm.total_revenue, 0) / NULLIF(csm.total_customers, 0), 2) AS revenue_per_customer,
  ROUND(COALESCE(csm.total_orders, 0)::NUMERIC / NULLIF(csm.total_customers, 0), 2) AS orders_per_customer,
  ROUND(COALESCE(cpm.avg_inventory_turnover, 0), 4) AS inventory_turnover_rate,
  
  -- Recent Period Performance
  ROUND(COALESCE(crr.revenue_last_30d, 0), 2) AS total_revenue_last_30d,
  ROUND(COALESCE(crr.revenue_last_90d, 0), 2) AS total_revenue_last_90d,
  
  -- Growth Metrics
  ROUND(
    (COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC 
    / NULLIF(crr.revenue_prev_30d, 0) * 100,
    2
  ) AS revenue_growth_30d_pct,
  ROUND(
    (COALESCE(crr.orders_last_30d, 0) - COALESCE(crr.orders_prev_30d, 0))::NUMERIC 
    / NULLIF(crr.orders_prev_30d, 0) * 100,
    2
  ) AS order_growth_30d_pct,
  
  -- Top Product
  tp.product_id AS top_product_id,
  tp.product_name AS top_product_name,
  ROUND(COALESCE(tp.product_revenue, 0), 2) AS top_product_revenue,
  ROUND(
    COALESCE(tp.product_revenue, 0)::NUMERIC / NULLIF(csm.total_revenue, 0),
    4
  ) AS top_product_revenue_share,
  
  -- Category Health Score (0-100)
  -- Factors: revenue share (30%), growth (25%), active products (20%), turnover (15%), customer base (10%)
  ROUND(
    LEAST(100, GREATEST(0,
      (COALESCE(csm.total_revenue, 0)::NUMERIC / NULLIF(trc.total_company_revenue, 1) * 300) +
      (CASE 
        WHEN COALESCE(crr.revenue_prev_30d, 0) > 0 
        THEN LEAST(25, (COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC / crr.revenue_prev_30d * 100)
        ELSE 0 
      END) +
      (COALESCE(cpm.active_products, 0)::NUMERIC / NULLIF(cpm.total_products, 1) * 20) +
      (LEAST(15, COALESCE(cpm.avg_inventory_turnover, 0) * 100)) +
      (CASE 
        WHEN COALESCE(csm.total_customers, 0) >= 50 THEN 10
        WHEN COALESCE(csm.total_customers, 0) >= 20 THEN 7
        WHEN COALESCE(csm.total_customers, 0) >= 10 THEN 5
        ELSE 2
      END)
    )),
    0
  ) AS category_health_score,
  
  -- Category Tier Classification
  CASE
    WHEN COALESCE(csm.total_revenue, 0) >= 15000 
         AND ((COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC / NULLIF(crr.revenue_prev_30d, 0)) >= 0.1 
    THEN 'Star'
    WHEN ((COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC / NULLIF(crr.revenue_prev_30d, 0)) >= 0.2 
         AND COALESCE(csm.total_revenue, 0) >= 5000 
    THEN 'Growth'
    WHEN COALESCE(csm.total_revenue, 0) >= 10000 
         AND ((COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC / NULLIF(crr.revenue_prev_30d, 0)) >= -0.05 
    THEN 'Mature'
    WHEN COALESCE(csm.total_revenue, 0) < 5000 
         AND COALESCE(cpm.active_products, 0) >= 5 
    THEN 'Emerging'
    ELSE 'Declining'
  END AS category_tier,
  
  -- Recommended Actions
  CASE
    WHEN COALESCE(csm.total_revenue, 0) >= 15000 
         AND ((COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC / NULLIF(crr.revenue_prev_30d, 0)) >= 0.1 
    THEN 'Expand inventory, promote heavily, maintain stock levels, upsell opportunities'
    WHEN ((COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC / NULLIF(crr.revenue_prev_30d, 0)) >= 0.2 
         AND COALESCE(csm.total_revenue, 0) >= 5000 
    THEN 'Invest in marketing, expand product line, capitalize on growth momentum'
    WHEN COALESCE(csm.total_revenue, 0) >= 10000 
         AND ((COALESCE(crr.revenue_last_30d, 0) - COALESCE(crr.revenue_prev_30d, 0))::NUMERIC / NULLIF(crr.revenue_prev_30d, 0)) >= -0.05 
    THEN 'Maintain current strategy, optimize inventory, cross-sell opportunities'
    WHEN COALESCE(csm.total_revenue, 0) < 5000 
         AND COALESCE(cpm.active_products, 0) >= 5 
    THEN 'Test marketing campaigns, monitor closely, identify winning products'
    WHEN COALESCE(cpm.declining_products, 0) > COALESCE(cpm.best_seller_products, 0) + COALESCE(cpm.good_performer_products, 0)
    THEN 'Address declining products urgently, refresh offerings, promotional push needed'
    WHEN COALESCE(cpm.at_risk_products, 0) + COALESCE(cpm.stale_products, 0) > COALESCE(cpm.active_products, 1) 
    THEN 'Clearance sales, discontinue poor performers, refresh product line'
    WHEN COALESCE(cpm.new_products, 0) > COALESCE(cpm.total_products, 1) * 0.3
    THEN 'Monitor new product performance, provide marketing support, gather customer feedback'
    ELSE 'Re-evaluate category strategy, consider promotional campaigns, analyze customer feedback'
  END AS recommended_action

FROM category_product_metrics AS cpm
LEFT JOIN category_sales_metrics AS csm
  ON cpm.category = csm.category
  AND cpm.region_id = csm.region_id
LEFT JOIN category_recent_revenue AS crr
  ON cpm.category = crr.category
  AND cpm.region_id = crr.region_id
LEFT JOIN top_products_by_category AS tp
  ON cpm.category = tp.category
  AND cpm.region_id = tp.region_id
  AND tp.revenue_rank = 1
LEFT JOIN total_revenue_calc AS trc
  ON cpm.region_id = trc.region_id

